import fs from "node:fs";
const files=["src/App.tsx","src/BoardsScreen.tsx","src/StudentsScreen.tsx","src/AssignmentsScreen.tsx","src/ProgressScreen.tsx","src/App.css"];
for(const p of files)if(!fs.existsSync(p)){console.error("v42: не найден "+p);process.exit(1)}
const patch=(t,n,r,l)=>{if(t.includes(r))return t;if(!t.includes(n)){console.error("v42: не найден фрагмент "+l);process.exit(1)}return t.replace(n,r)};
let a=fs.readFileSync("src/App.tsx","utf8");
a=patch(a,'import ProgressScreen from "./ProgressScreen";','import ProgressScreen from "./ProgressScreen";\nimport ScheduleScreen from "./ScheduleScreen";',"app import");
a=patch(a,': section==="progress"\n          ? <ProgressScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} />\n          : <BoardsScreen',
': section==="progress"\n          ? <ProgressScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} />\n          : section==="schedule"\n          ? <ScheduleScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} onOpenBoard={(board)=>navigate(`/board/${board.id}`)} />\n          : <BoardsScreen',"route");fs.writeFileSync("src/App.tsx",a);
for(const f of ["src/BoardsScreen.tsx","src/StudentsScreen.tsx","src/AssignmentsScreen.tsx","src/ProgressScreen.tsx"]){let s=fs.readFileSync(f,"utf8");s=s.replace(/<button disabled(?: title="Появится в следующих этапах")?>Расписание<\/button>/g,'<button onClick={()=>{window.history.pushState({},"","/?section=schedule");window.dispatchEvent(new PopStateEvent("popstate"))}}>Расписание</button>');fs.writeFileSync(f,s)}
let c=fs.readFileSync("src/App.css","utf8");if(!c.includes("/* v42 · schedule */"))c+=`
/* v42 · schedule */
.schedule-shell{min-height:100vh;background:#f6f6f9;color:#292a34}.schedule-content{max-width:1280px;margin:auto;padding:22px 24px 56px}.schedule-toolbar{display:grid;grid-template-columns:38px 70px 1fr 38px;gap:7px;align-items:center;margin:16px 0}.schedule-toolbar button{height:34px;border:1px solid #e0e1e8;border-radius:8px;background:#fff;cursor:pointer}.schedule-toolbar strong{text-align:center;font-size:12px}.schedule-layout{display:grid;grid-template-columns:minmax(0,1fr) 230px;gap:10px}.week-grid{display:grid;grid-template-columns:repeat(7,minmax(120px,1fr));border:1px solid #e2e3e9;border-radius:13px;background:#fff;overflow-x:auto}.schedule-day{min-height:480px;border-right:1px solid #eeeef2}.schedule-day:last-child{border:0}.schedule-day>header{height:54px;display:flex;flex-direction:column;align-items:center;justify-content:center;border-bottom:1px solid #eeeef2}.schedule-day>header b{font-size:9px;text-transform:uppercase;color:#8a8d98}.schedule-day>header span{font-size:17px;font-weight:850}.schedule-day.today>header{background:#efefff;color:#5052bd}.schedule-day>div{padding:5px;display:grid;align-content:start;gap:5px}.schedule-event{padding:7px;border-left:3px solid #6a6cd4;border-radius:7px;background:#f4f3ff;display:grid;gap:2px}.schedule-event.completed{opacity:.55;border-color:#4ca874}.schedule-event time{font-size:9px;font-weight:850;color:#5658b9}.schedule-event b{font-size:10px}.schedule-event span,.schedule-event small{font-size:8px;color:#747887}.schedule-event>div{display:flex;gap:3px;margin-top:4px}.schedule-event button{border:0;border-radius:5px;padding:4px 5px;background:#fff;font-size:8px;font-weight:800;cursor:pointer}.schedule-event button.danger{color:#b84343}.schedule-add-day{height:25px;border:1px dashed #d7d8e1;border-radius:6px;background:transparent;color:#a0a2ad;cursor:pointer}.schedule-side{padding:13px;border:1px solid #e2e3e9;border-radius:13px;background:#fff;align-self:start}.schedule-side h3{font-size:12px;margin:0 0 8px}.schedule-side article{display:grid;gap:2px;padding:9px 0;border-top:1px solid #f0f0f4}.schedule-side time{font-size:8px;color:#6b6dcc;font-weight:800}.schedule-side b{font-size:10px}.schedule-side span{font-size:9px;color:#858895}.schedule-side button{justify-self:start;border:0;background:transparent;color:#5558c4;font-size:8px;font-weight:800;cursor:pointer}.schedule-modal{max-width:650px}.schedule-form{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.schedule-form label{display:grid;gap:4px}.schedule-form label.wide{grid-column:1/-1}.schedule-form span{font-size:9px;font-weight:850;color:#666a78}.schedule-form input,.schedule-form select,.schedule-form textarea{width:100%;box-sizing:border-box;border:1px solid #dddfe7;border-radius:8px;padding:8px;font:inherit}
@media(max-width:900px){.schedule-layout{grid-template-columns:1fr}.week-grid{grid-template-columns:repeat(7,150px)}.schedule-side{order:-1}}@media(max-width:600px){.schedule-content{padding:14px}.schedule-form{grid-template-columns:1fr}.schedule-form label.wide{grid-column:auto}.schedule-toolbar{grid-template-columns:34px 60px 1fr 34px}}
`;fs.writeFileSync("src/App.css",c);console.log("v42 установлен. Выполните SQL, затем npm run build");
