import fs from "node:fs";
for(const p of ["src/App.tsx","src/backend.ts","src/BoardsScreen.tsx","src/StudentsScreen.tsx","src/AssignmentsScreen.tsx","src/ProgressScreen.tsx","src/ScheduleScreen.tsx","src/App.css"])if(!fs.existsSync(p)){console.error("v44: не найден "+p);process.exit(1)}
const patch=(t,n,r,l)=>{if(t.includes(r))return t;if(!t.includes(n)){console.error("v44: не найден фрагмент "+l);process.exit(1)}return t.replace(n,r)};
let b=fs.readFileSync("src/backend.ts","utf8");
if(!b.includes("export const remoteStorageRequest"))b+=`
export const remoteStorageRequest=async(bucket:string,path:string,blob?:Blob|null,method?:string):Promise<Blob|null>=>{
 const session=await getRemoteSession();if(!session)throw new Error("Сессия истекла. Войдите снова.");
 const verb=method||(blob?"POST":"GET");const response=await fetch(\`\${url}/storage/v1/object/\${verb==="GET"?"authenticated/":""}\${bucket}/\${path}\`,{method:verb,headers:{apikey:anonKey,Authorization:\`Bearer \${session.access_token}\`,...(blob?{"Content-Type":blob.type||"application/octet-stream","x-upsert":"false"}:{})},...(blob?{body:blob}:{})});
 if(!response.ok)throw new Error(await errorMessage(response));return verb==="GET"?response.blob():null;
};
`;fs.writeFileSync("src/backend.ts",b);
let a=fs.readFileSync("src/App.tsx","utf8");a=patch(a,'import ScheduleScreen from "./ScheduleScreen";','import ScheduleScreen from "./ScheduleScreen";\nimport MaterialsScreen from "./MaterialsScreen";',"import");a=patch(a,': section==="schedule"\n          ? <ScheduleScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} onOpenBoard={(board)=>navigate(`/board/${board.id}`)} />\n          : <BoardsScreen',': section==="schedule"\n          ? <ScheduleScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} onOpenBoard={(board)=>navigate(`/board/${board.id}`)} />\n          : section==="materials"\n          ? <MaterialsScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} />\n          : <BoardsScreen',"route");fs.writeFileSync("src/App.tsx",a);
for(const f of ["src/BoardsScreen.tsx","src/StudentsScreen.tsx","src/AssignmentsScreen.tsx","src/ProgressScreen.tsx","src/ScheduleScreen.tsx"]){let s=fs.readFileSync(f,"utf8");s=s.replace(/<button disabled(?: title="Появится в следующих этапах")?>Материалы<\/button>/g,'<button onClick={()=>{window.history.pushState({},"","/?section=materials");window.dispatchEvent(new PopStateEvent("popstate"))}}>Материалы</button>');fs.writeFileSync(f,s)}
let c=fs.readFileSync("src/App.css","utf8");if(!c.includes("/* v44 · materials */"))c+=`
/* v44 · materials */
.materials-shell{min-height:100vh;background:#f6f6f9;color:#292a34}.materials-content{max-width:1180px;margin:auto;padding:22px 24px 56px}.materials-toolbar{display:grid;grid-template-columns:minmax(220px,1fr) 180px auto;gap:8px;align-items:center;margin:16px 0}.materials-toolbar input,.materials-toolbar select{border:1px solid #dedfe7;border-radius:9px;background:#fff;padding:9px}.materials-toolbar span{font-size:9px;color:#858895}.materials-layout{display:grid;grid-template-columns:180px 1fr;gap:12px}.materials-folders{display:grid;align-content:start;gap:4px}.materials-folders button{border:0;border-radius:8px;background:transparent;padding:9px;text-align:left;font-size:10px;display:flex;justify-content:space-between;cursor:pointer}.materials-folders button.active{background:#e9e9fb;color:#5557bd;font-weight:850}.materials-folders b{font-size:9px}.materials-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.material-card{border:1px solid #e2e3ea;border-radius:12px;background:#fff;padding:10px;display:grid;grid-template-columns:48px 1fr;gap:9px}.material-icon{width:48px;height:48px;border-radius:9px;background:#eeeef7;display:grid;place-items:center;font-size:9px;font-weight:900;color:#6567c3}.material-icon.image{background:#edf6ef;color:#44835b}.material-card>div:nth-child(2){min-width:0;display:grid;align-content:center}.material-card b,.material-card span,.material-card small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.material-card b{font-size:10px}.material-card span,.material-card small{font-size:8px;color:#8a8d98}.material-actions{grid-column:1/-1;display:flex;gap:4px}.material-actions button{border:1px solid #e5e5eb;border-radius:6px;background:#fff;padding:5px 7px;font-size:8px;cursor:pointer}.material-actions .danger{margin-left:auto;color:#b74848}.materials-modal{max-width:440px}.materials-modal>label{display:grid;gap:4px;margin:10px 0}.materials-modal>label span{font-size:9px;font-weight:850}.materials-modal input{border:1px solid #dddfe7;border-radius:8px;padding:8px}
@media(max-width:800px){.materials-grid{grid-template-columns:1fr 1fr}.materials-layout{grid-template-columns:1fr}.materials-folders{display:flex;overflow:auto}.materials-folders button{white-space:nowrap;gap:10px}}@media(max-width:560px){.materials-content{padding:14px}.materials-toolbar{grid-template-columns:1fr}.materials-grid{grid-template-columns:1fr}}
`;fs.writeFileSync("src/App.css",c);console.log("v44 установлен. Выполните SQL, затем npm run build");
