import fs from "node:fs";
for(const p of ["src/App.tsx","src/App.css"])if(!fs.existsSync(p)){console.error("v54: не найден "+p);process.exit(1)}
let a=fs.readFileSync("src/App.tsx","utf8");
a=a.replace('type FormulaPaletteTab = "basic" | "greek" | "relations" | "functions" | "templates";','type FormulaPaletteTab = "basic" | "greek" | "relations" | "functions" | "geometry" | "templates";');
if(!a.includes('geometry: ['))a=a.replace('  templates: [','  geometry: [\n    { label: "∠", snippet: "\\\\angle " }, { label: "△", snippet: "\\\\triangle " }, { label: "°", snippet: "^{\\\\circ}" },\n    { label: "∥", snippet: "\\\\parallel " }, { label: "⟂", snippet: "\\\\perp " },\n    { label: "AB⃗", snippet: "\\\\vec{⟦AB⟧}" }, { label: "|AB|", snippet: "\\\\abs{⟦AB⟧}" },\n    { label: "AB̅", snippet: "\\\\overline{⟦AB⟧}" }, { label: "πr²", snippet: "S = \\\\pi r^2" },\n  ],\n  templates: [');
a=a.replace('  emptyset: "∅",','  emptyset: "∅", angle: "∠", triangle: "△", circ: "°",');
if(!a.includes('name === "abs"'))a=a.replace('    if (name === "overline") return <span key={key("bar")} className="formula-overline">{parseGroup()}</span>;','    if (name === "overline") return <span key={key("bar")} className="formula-overline">{parseGroup()}</span>;\n    if (name === "abs") return <span key={key("abs")} className="formula-absolute">|{parseGroup()}|</span>;\n    if (name === "binom") { const top = parseGroup(), bottom = parseGroup(); return <span key={key("binom")} className="formula-binom"><span>(</span><span className="formula-binom-stack"><span>{top}</span><span>{bottom}</span></span><span>)</span></span>; }');
if(!a.includes('formulaHistory'))a=a.replace('  const [formulaPaletteTab, setFormulaPaletteTab] = useState<FormulaPaletteTab>("basic");','  const [formulaPaletteTab, setFormulaPaletteTab] = useState<FormulaPaletteTab>("basic");\n  const [formulaHistory, setFormulaHistory] = useState<string[]>(() => { try { const v=JSON.parse(localStorage.getItem("onlinerepetitor.formula-history.v54")||"[]"); return Array.isArray(v)?v.slice(0,12):[] } catch { return [] } });');
if(!a.includes('onlinerepetitor.formula-history.v54", JSON.stringify(history)'))a=a.replace('    commit(itemsRef.current.map((item) => item.id === formulaEditorId ? {','    if (textValue.trim()) { const history=[textValue,...formulaHistory.filter((value)=>value!==textValue)].slice(0,12); setFormulaHistory(history); localStorage.setItem("onlinerepetitor.formula-history.v54",JSON.stringify(history)); }\n    commit(itemsRef.current.map((item) => item.id === formulaEditorId ? {');
a=a.replace('(["basic","greek","relations","functions","templates"] as FormulaPaletteTab[])','(["basic","greek","relations","functions","geometry","templates"] as FormulaPaletteTab[])');
a=a.replace('tab === "functions" ? "Функции" : "Шаблоны"','tab === "functions" ? "Функции" : tab === "geometry" ? "Геометрия" : "Шаблоны"');
if(!a.includes('className="formula-history"'))a=a.replace('                  <div className="formula-help">','                  {formulaHistory.length > 0 && <div className="formula-history"><div><strong>Недавние формулы</strong><button onClick={()=>{setFormulaHistory([]);localStorage.removeItem("onlinerepetitor.formula-history.v54")}}>Очистить</button></div><div>{formulaHistory.map((value,index)=><button key={index} title={value} onClick={()=>insertFormulaSnippet(value,true)}><FormulaView text={value} fontSize={17}/></button>)}</div></div>}\n                  <div className="formula-help">');
const anchor='{ label: "ā", snippet: "\\\\overline{⟦a⟧}", title: "Черта сверху" },';
if(a.includes(anchor)&&!a.includes('title: "Модуль"'))a=a.replace(anchor,anchor+' { label: "|x|", snippet: "\\\\abs{⟦x⟧}", title: "Модуль" }, { label: "(n k)", snippet: "\\\\binom{⟦n⟧}{k}", title: "Биномиальный коэффициент" },');
fs.writeFileSync("src/App.tsx",a);
let c=fs.readFileSync("src/App.css","utf8");
if(!c.includes("/* v54 · formulas */"))c+=`\n/* v54 · formulas */\n.formula-absolute{display:inline-flex;align-items:center;border-left:1.5px solid currentColor;border-right:1.5px solid currentColor;padding:0 .12em}.formula-binom{display:inline-flex;align-items:center;gap:.08em}.formula-binom-stack{display:inline-grid;grid-template-rows:1fr 1fr;font-size:.72em;line-height:1.02;text-align:center}.formula-history{border-top:1px solid #ececf1;margin-top:12px;padding-top:10px}.formula-history>div:first-child{display:flex;justify-content:space-between;align-items:center;font-size:9px}.formula-history>div:first-child button{border:0;background:transparent;color:#777b88;font-size:8px;cursor:pointer}.formula-history>div:last-child{display:flex;gap:5px;overflow-x:auto;padding:6px 0}.formula-history>div:last-child>button{flex:0 0 auto;max-width:180px;min-height:38px;padding:5px 9px;border:1px solid #e0e1e8;border-radius:8px;background:#fff;cursor:pointer;overflow:hidden}.formula-history .formula-view{white-space:nowrap}\n`;
fs.writeFileSync("src/App.css",c);
console.log("v54 установлен. Запустите npm run build");
