import fs from "node:fs";
for(const p of ["src/App.tsx","src/App.css","src/main.tsx","public/sw.js","public/manifest.webmanifest"])if(!fs.existsSync(p)){console.error("v63: не найден "+p);process.exit(1)}
let main=fs.readFileSync("src/main.tsx","utf8");
main=main.replace('void navigator.serviceWorker.register("/sw.js").catch((error) => console.warn("Service worker registration failed", error));','void navigator.serviceWorker.register("/sw.js").then((registration)=>{const announce=()=>window.dispatchEvent(new CustomEvent("or-sw-update",{detail:{registration}}));if(registration.waiting)announce();registration.addEventListener("updatefound",()=>{const worker=registration.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="installed"&&navigator.serviceWorker.controller)announce()})})}).catch((error) => console.warn("Service worker registration failed", error));');
if(!main.includes("controllerchange"))main+='\nlet orReloading=false;\nif ("serviceWorker" in navigator) navigator.serviceWorker.addEventListener("controllerchange",()=>{if(orReloading)return;orReloading=true;window.location.reload()});\n';
fs.writeFileSync("src/main.tsx",main);
let a=fs.readFileSync("src/App.tsx","utf8");
a=a.replace('  const [isStandalone,setIsStandalone]=useState(()=>window.matchMedia?.("(display-mode: standalone)").matches===true);','  const [isStandalone,setIsStandalone]=useState(()=>window.matchMedia?.("(display-mode: standalone)").matches===true);\n  const [online,setOnline]=useState(()=>navigator.onLine);\n  const [updateReady,setUpdateReady]=useState<ServiceWorkerRegistration|null>(null);');
if(!a.includes('or-sw-update'))a=a.replace('  const installApp=async()=>','  useEffect(()=>{const sync=()=>setOnline(navigator.onLine);const update=((e:Event)=>setUpdateReady((e as CustomEvent<{registration:ServiceWorkerRegistration}>).detail.registration)) as EventListener;window.addEventListener("online",sync);window.addEventListener("offline",sync);window.addEventListener("or-sw-update",update);return()=>{window.removeEventListener("online",sync);window.removeEventListener("offline",sync);window.removeEventListener("or-sw-update",update)}},[]);\n  const applyUpdate=()=>{updateReady?.waiting?.postMessage({type:"SKIP_WAITING"})};\n  const installApp=async()=>');
a=a.replace('<header className="topbar">','{!online&&<div className="offline-banner" role="status"><strong>Офлайн</strong><span>Можно продолжать работу с уже открытой локальной доской. Серверная синхронизация возобновится после подключения.</span></div>}{updateReady&&<div className="update-banner" role="status"><span>Доступна новая версия OnlineRepetitor.</span><button type="button" onClick={applyUpdate}>Обновить</button><button type="button" className="secondary" onClick={()=>setUpdateReady(null)}>Позже</button></div>}<header className="topbar">');
fs.writeFileSync("src/App.tsx",a);
let css=fs.readFileSync("src/App.css","utf8");
if(!css.includes("/* v63 · PWA reliability */"))css+='\n/* v63 · PWA reliability */\n.offline-banner,.update-banner{flex-shrink:0;z-index:29;display:flex;align-items:center;justify-content:center;gap:10px;min-height:36px;padding:6px 12px;font-size:12px}.offline-banner{background:#fff5d8;color:#705313;border-bottom:1px solid #ead79e}.offline-banner strong{padding:2px 7px;border-radius:999px;background:#e9b93f;color:#fff}.update-banner{background:#ededff;color:#3f419c;border-bottom:1px solid #d3d4f5}.update-banner button{padding:5px 9px;border-radius:7px;background:#5355c9;color:#fff;cursor:pointer}.update-banner button.secondary{background:#fff;color:#5355c9;border:1px solid #cfd0f1}@media(max-width:620px){.offline-banner,.update-banner{justify-content:flex-start;flex-wrap:wrap;font-size:11px}.offline-banner span{flex:1;min-width:210px}}\n';
fs.writeFileSync("src/App.css",css);
fs.copyFileSync(new URL("./v63_files/public/sw.js",import.meta.url),"public/sw.js");
fs.copyFileSync(new URL("./v63_files/public/manifest.webmanifest",import.meta.url),"public/manifest.webmanifest");
console.log("v63 установлен. Запустите npm run build");
