import fs from "node:fs";
const p="src/App.tsx",c="src/App.css";
if(!fs.existsSync(p)||!fs.existsSync(c)){console.error("v38: App.tsx/App.css не найдены");process.exit(1)}
let s=fs.readFileSync(p,"utf8"),css=fs.readFileSync(c,"utf8");
const P=(n,r,l)=>{if(s.includes(r))return;if(!s.includes(n)){console.error("v38: не найден "+l);process.exit(1)}s=s.replace(n,r)};
P('import StudentsScreen from "./StudentsScreen";','import StudentsScreen from "./StudentsScreen";\nimport { finishLesson, getActiveLesson, startLesson, type LiveLesson } from "./lessonStore";',"import");
P('  const [sharing, setSharing] = useState(false);','  const [sharing, setSharing] = useState(false);\n  const [liveLesson,setLiveLesson]=useState<LiveLesson|null>(null);\n  const [lessonOpen,setLessonOpen]=useState(false),[lessonFinishOpen,setLessonFinishOpen]=useState(false);\n  const [lessonStudentId,setLessonStudentId]=useState(""),[lessonTopic,setLessonTopic]=useState("");\n  const [lessonResult,setLessonResult]=useState(""),[lessonHomework,setLessonHomework]=useState(""),[lessonClock,setLessonClock]=useState(Date.now());',"states");
P('  const remoteEditingCount = Object.values(remoteWork).filter((state) => state.editingId).length;','  const remoteEditingCount = Object.values(remoteWork).filter((state) => state.editingId).length;\n  const lessonStudents=presenceUsers.filter((u)=>u.userId!==authUser.id);\n  const lessonSeconds=liveLesson?Math.max(0,Math.floor((lessonClock-Date.parse(liveLesson.startedAt))/1000)):0;\n  const lessonTime=`${String(Math.floor(lessonSeconds/3600)).padStart(2,"0")}:${String(Math.floor((lessonSeconds%3600)/60)).padStart(2,"0")}:${String(lessonSeconds%60).padStart(2,"0")}`;',"derived");
const marker='  return (\n    <div className={`app ${presentation ? "presentation-mode" : ""} ${!canEdit ? "viewer-mode" : ""}`}>';
const before=`  useEffect(()=>{if(boardSummary.role==="owner")void getActiveLesson(boardSummary.id).then(setLiveLesson).catch(()=>undefined)},[boardSummary.id,boardSummary.role]);
  useEffect(()=>{if(!liveLesson)return;setLessonClock(Date.now());const t=window.setInterval(()=>setLessonClock(Date.now()),1000);return()=>window.clearInterval(t)},[liveLesson?.id]);
  const beginLiveLesson=async()=>{const student=lessonStudents.find(u=>u.userId===lessonStudentId);if(!student){setNotice("Выберите ученика, который сейчас на доске");return}try{const lesson=await startLesson(boardSummary.id,student.userId,student.name,lessonTopic);setLiveLesson(lesson);setLessonOpen(false);setPresentationElapsed(0);setPresentationTimerMode("elapsed");setPresentationTimerRunning(true);setNotice("Урок начат")}catch{setNotice("Не удалось начать урок")}};
  const completeLiveLesson=async()=>{if(!liveLesson)return;try{const done=await finishLesson(liveLesson,lessonResult,lessonHomework);setLiveLesson(null);setLessonFinishOpen(false);setPresentationTimerRunning(false);setLessonResult("");setLessonHomework("");setNotice(\`Урок завершён · \${done.minutes} мин. Запись добавлена в историю\`)}catch{setNotice("Не удалось завершить урок")}};

`+marker;
P(marker,before,"render");
const share='{boardSummary.role === "owner" && <button className="lesson-button" onClick={() => setSharing(true)}>Поделиться</button>}';
P(share,`{boardSummary.role === "owner" && (liveLesson ? <div className="live-lesson-chip"><span className="live-lesson-dot"/><span><b>{liveLesson.studentName}</b><small>{liveLesson.topic||"Урок"} · {lessonTime}</small></span><button onClick={()=>setLessonFinishOpen(true)}>Завершить</button></div> : <button className="lesson-button start-live-lesson" onClick={()=>{setLessonStudentId(lessonStudents[0]?.userId||"");setLessonOpen(true)}}>Начать урок</button>)}
          ${share}`,"topbar");
const sharing='{sharing && <ShareDialog board={boardSummary} user={authUser} onClose={() => setSharing(false)}/>}';
const modals=`${sharing}
      {lessonOpen && <div className="access-backdrop"><section className="access-modal lesson-live-modal"><div className="access-head"><div><h2>Начать урок</h2><p>Текущая доска станет рабочим пространством занятия.</p></div><button onClick={()=>setLessonOpen(false)}>×</button></div><label><span>Ученик</span><select value={lessonStudentId} onChange={e=>setLessonStudentId(e.target.value)}><option value="">Выберите</option>{lessonStudents.map(u=><option key={u.userId} value={u.userId}>{u.name}</option>)}</select></label><label><span>Тема</span><input value={lessonTopic} onChange={e=>setLessonTopic(e.target.value)} placeholder="Тема занятия"/></label><div className="session-actions"><button className="students-primary" onClick={()=>void beginLiveLesson()}>Начать и запустить таймер</button><button className="boards-secondary" onClick={()=>setLessonOpen(false)}>Отмена</button></div></section></div>}
      {lessonFinishOpen && liveLesson && <div className="access-backdrop"><section className="access-modal lesson-live-modal"><div className="access-head"><div><h2>Завершить урок</h2><p>{liveLesson.studentName} · {lessonTime}</p></div><button onClick={()=>setLessonFinishOpen(false)}>×</button></div><label><span>Итог</span><textarea rows={4} value={lessonResult} onChange={e=>setLessonResult(e.target.value)}/></label><label><span>Домашнее задание</span><textarea rows={4} value={lessonHomework} onChange={e=>setLessonHomework(e.target.value)}/></label><div className="session-actions"><button className="students-primary" onClick={()=>void completeLiveLesson()}>Завершить и сохранить</button><button className="boards-secondary" onClick={()=>setLessonFinishOpen(false)}>Продолжить</button></div></section></div>}`;
P(sharing,modals,"modals");
fs.writeFileSync(p,s,"utf8");
if(!css.includes("/* v38 · live lesson */")){css+=`
/* v38 · live lesson */
.start-live-lesson{background:#4f50bd!important;color:#fff!important}.live-lesson-chip{display:flex;align-items:center;gap:8px;padding:4px 5px 4px 9px;border:1px solid #d9d7f7;border-radius:10px;background:#f4f3ff}.live-lesson-dot{width:8px;height:8px;border-radius:50%;background:#39b86d;box-shadow:0 0 0 4px rgba(57,184,109,.12)}.live-lesson-chip>span:nth-child(2){display:flex;flex-direction:column}.live-lesson-chip b{font-size:10px}.live-lesson-chip small{font-size:9px;color:#73768a}.live-lesson-chip button{border:0;border-radius:7px;background:#fff0f0;color:#a53e3e;padding:6px 8px;font-size:9px;font-weight:800;cursor:pointer}.lesson-live-modal{max-width:520px}.lesson-live-modal>label{display:grid;gap:5px;margin-top:13px}.lesson-live-modal>label>span{font-size:10px;font-weight:800}.lesson-live-modal select,.lesson-live-modal input,.lesson-live-modal textarea{box-sizing:border-box;width:100%;border:1px solid #dddde7;border-radius:9px;padding:10px;font:inherit;resize:vertical}
`;fs.writeFileSync(c,css,"utf8")}
console.log("v38 установлен. Выполните SQL, затем npm run build");
