import fs from "node:fs";
for(const p of ["src/NotificationsScreen.tsx","src/BoardsScreen.tsx","src/App.css"])if(!fs.existsSync(p)){console.error("v50: не найден "+p);process.exit(1)}
let n=fs.readFileSync("src/NotificationsScreen.tsx","utf8");
if(!n.includes("notificationSettingsStore"))n=n.replace('import { listNotifications,markAllNotificationsRead,markNotificationRead,type AppNotification,type NotificationKind } from "./notificationsStore";','import { listNotifications,markAllNotificationsRead,markNotificationRead,type AppNotification,type NotificationKind } from "./notificationsStore";\nimport { defaultNotificationSettings,getNotificationSettings,saveNotificationSettings,type NotificationSettings } from "./notificationSettingsStore";');
n=n.replace('const [rows,setRows]=useState<AppNotification[]>([]),[filter,setFilter]=useState<"all"|"unread">("all"),[loading,setLoading]=useState(true);','const [rows,setRows]=useState<AppNotification[]>([]),[filter,setFilter]=useState<"all"|"unread">("all"),[loading,setLoading]=useState(true);const [settings,setSettings]=useState<NotificationSettings>(defaultNotificationSettings),[settingsOpen,setSettingsOpen]=useState(false);');
n=n.replace('const load=async()=>{setLoading(true);try{setRows(await listNotifications())}finally{setLoading(false)}};useEffect(()=>{void load()},[user.id]);','const load=async()=>{setLoading(true);try{const [items,prefs]=await Promise.all([listNotifications(),getNotificationSettings()]);setRows(items);setSettings(prefs)}finally{setLoading(false)}};useEffect(()=>{void load()},[user.id]);');
n=n.replace('{unread>0&&<button className="boards-secondary"','<button className="boards-secondary" onClick={()=>setSettingsOpen(true)}>⚙ Настройки</button>{unread>0&&<button className="boards-secondary"');
const modal=`{settingsOpen&&<div className="access-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSettingsOpen(false)}}><section className="access-modal notification-settings"><div className="access-head"><div><h2>Настройки уведомлений</h2><p>Выберите нужные события и напоминания.</p></div><button onClick={()=>setSettingsOpen(false)}>×</button></div>{([["assignment","Новые задания"],["submission","Сданные работы"],["review","Результаты проверки"],["lesson","Новые занятия"],["material","Новые материалы"],["lessonReminder","Напоминать перед занятием"],["assignmentReminder","Напоминать о сроке задания"]] as [keyof NotificationSettings,string][]).map(([key,label])=><label className="notification-toggle" key={key}><span>{label}</span><input type="checkbox" checked={settings[key]} onChange={e=>setSettings(x=>({...x,[key]:e.target.checked}))}/></label>)}<div className="session-actions"><button className="students-primary" onClick={async()=>{await saveNotificationSettings(settings);setSettingsOpen(false)}}>Сохранить</button></div></section></div>}`;
n=n.replace('</section></main>',modal+'</section></main>');fs.writeFileSync("src/NotificationsScreen.tsx",n);
let b=fs.readFileSync("src/BoardsScreen.tsx","utf8");
if(!b.includes('from "./notificationsStore"'))b=b.replace('export default function BoardsScreen','import { listNotifications } from "./notificationsStore";\n\nexport default function BoardsScreen');
if(!b.includes("notificationUnreadCount")){b=b.replace('export default function BoardsScreen({user,onOpenBoard,onLogout}:Props){','export default function BoardsScreen({user,onOpenBoard,onLogout}:Props){\n const [notificationUnreadCount,setNotificationUnreadCount]=useState(0);\n useEffect(()=>{void listNotifications().then(x=>setNotificationUnreadCount(x.filter(v=>!v.readAt).length)).catch(()=>{})},[user.id]);');b=b.replace('>Уведомления</button>','>Уведомления{notificationUnreadCount>0&&<b className="nav-badge">{notificationUnreadCount>99?"99+":notificationUnreadCount}</b>}</button>')}
fs.writeFileSync("src/BoardsScreen.tsx",b);
let c=fs.readFileSync("src/App.css","utf8");if(!c.includes("/* v50 · notification preferences */"))c+=`
/* v50 · notification preferences */
.dashboard-nav button{position:relative}.nav-badge{margin-left:5px;min-width:15px;height:15px;padding:0 4px;border-radius:999px;background:#5b5dc4;color:white;display:inline-grid;place-items:center;font-size:7px}.notification-settings{max-width:460px}.notification-toggle{display:flex;justify-content:space-between;align-items:center;padding:10px 2px;border-bottom:1px solid #eeeef3;font-size:10px}.notification-toggle input{width:17px;height:17px;accent-color:#5b5dc4}
`;fs.writeFileSync("src/App.css",c);console.log("v50 установлен. Выполните SQL, затем npm run build");
