import fs from "node:fs";
for(const p of ["src/App.tsx","src/boardModel.ts","src/App.css"])if(!fs.existsSync(p)){console.error("v57: не найден "+p);process.exit(1)}
let m=fs.readFileSync("src/boardModel.ts","utf8");
m=m.replace('  graphShowLabels?: boolean;\n  resolved?: boolean;','  graphShowLabels?: boolean;\n  graphSegments?: { a:number; b:number; kind:"segment"|"line"|"ray"; label:string; measure:boolean }[];\n  graphAngles?: { a:number; vertex:number; b:number; label:string }[];\n  resolved?: boolean;');
if(!m.includes("Повреждены геометрические связи графика"))m=m.replace('      if (i.graphShowLabels != null && typeof i.graphShowLabels !== "boolean") throw new Error("Повреждены подписи графика");',`      if (i.graphShowLabels != null && typeof i.graphShowLabels !== "boolean") throw new Error("Повреждены подписи графика");
      if (i.graphSegments != null && (!Array.isArray(i.graphSegments) || i.graphSegments.length > 60 || !i.graphSegments.every((s: unknown) => !!s && typeof s === "object" && Number.isInteger((s as {a:number}).a) && Number.isInteger((s as {b:number}).b) && ["segment","line","ray"].includes((s as {kind:string}).kind) && typeof (s as {label:string}).label === "string" && typeof (s as {measure:boolean}).measure === "boolean"))) throw new Error("Повреждены геометрические связи графика");
      if (i.graphAngles != null && (!Array.isArray(i.graphAngles) || i.graphAngles.length > 40 || !i.graphAngles.every((g: unknown) => !!g && typeof g === "object" && Number.isInteger((g as {a:number}).a) && Number.isInteger((g as {vertex:number}).vertex) && Number.isInteger((g as {b:number}).b) && typeof (g as {label:string}).label === "string"))) throw new Error("Повреждены углы графика");`);
fs.writeFileSync("src/boardModel.ts",m);
let a=fs.readFileSync("src/App.tsx","utf8");
a=a.replace('points:{x:number;y:number;label:string}[];showLabels:boolean}|null>(null);','points:{x:number;y:number;label:string}[];showLabels:boolean;segments:{a:number;b:number;kind:"segment"|"line"|"ray";label:string;measure:boolean}[];angles:{a:number;vertex:number;b:number;label:string}[]}|null>(null);');
a=a.replace('showLabels:item.graphShowLabels!==false});','showLabels:item.graphShowLabels!==false,segments:(item.graphSegments??[]).map(s=>({...s})),angles:(item.graphAngles??[]).map(g=>({...g}))});');
a=a.replace('graphShowLabels:d.showLabels}:item));','graphShowLabels:d.showLabels,graphSegments:d.segments,graphAngles:d.angles}:item));');
a=a.replace('graphShowLabels:true,color:"#5355c9"','graphShowLabels:true,graphSegments:[],graphAngles:[],color:"#5355c9"');
a=a.replace('graphShowLabels:graphDraft.showLabels}}/>','graphShowLabels:graphDraft.showLabels,graphSegments:graphDraft.segments,graphAngles:graphDraft.angles}}/>');

const marker='  const path=pts.map((p,i)=>(i?"L":"M")+p[0].toFixed(1)+" "+p[1].toFixed(1)).join(" ");';
a=a.replace(marker,marker+`
  const gp=item.graphPoints??[];
  const extend=(pa:{x:number;y:number},pb:{x:number;y:number},kind:"segment"|"line"|"ray")=>{let ax=sx(pa.x),ay=sy(pa.y),bx=sx(pb.x),by=sy(pb.y);if(kind==="segment")return {ax,ay,bx,by};const dx=bx-ax,dy=by-ay,len=Math.hypot(dx,dy)||1,ux=dx/len,uy=dy/len,L=1400;if(kind==="ray")return {ax,ay,bx:bx+ux*L,by:by+uy*L};return {ax:ax-ux*L,ay:ay-uy*L,bx:bx+ux*L,by:by+uy*L}};
  const angleDeg=(p1:{x:number;y:number},v:{x:number;y:number},p2:{x:number;y:number})=>{const a1=Math.atan2(p1.y-v.y,p1.x-v.x),a2=Math.atan2(p2.y-v.y,p2.x-v.x);let d=Math.abs((a2-a1)*180/Math.PI)%360;return d>180?360-d:d};`);
a=a.replace('<path className="graph-curve" d={path}/>{(item.graphPoints??[]).map',`<path className="graph-curve" d={path}/><g className="graph-geometry">{(item.graphSegments??[]).map((s,i)=>{const pa=gp[s.a],pb=gp[s.b];if(!pa||!pb||s.a===s.b)return null;const e=extend(pa,pb,s.kind),mx=(sx(pa.x)+sx(pb.x))/2,my=(sy(pa.y)+sy(pb.y))/2,dist=Math.hypot(pb.x-pa.x,pb.y-pa.y);return <g key={"seg"+i}><line x1={e.ax} y1={e.ay} x2={e.bx} y2={e.by}/>{(s.label||s.measure)&&<text x={mx+7} y={my-7}>{s.label}{s.label&&s.measure?" · ":""}{s.measure?dist.toFixed(2):""}</text>}</g>})}{(item.graphAngles??[]).map((g,i)=>{const p1=gp[g.a],v=gp[g.vertex],p2=gp[g.b];if(!p1||!v||!p2)return null;const deg=angleDeg(p1,v,p2);return <text className="graph-angle-label" key={"ang"+i} x={sx(v.x)+12} y={sy(v.y)+20}>{g.label?g.label+" · ":""}{deg.toFixed(1)}°</text>})}</g>{(item.graphPoints??[]).map`);

const pointEnd='</div>{graphDraft.points.length===0?';
a=a.replace(pointEnd,`</div>{graphDraft.points.length>=2&&<><div className="graph-geometry-section"><div className="graph-points-head"><strong>Линии и отрезки</strong><button type="button" onClick={()=>setGraphDraft({...graphDraft,segments:[...graphDraft.segments,{a:0,b:1,kind:"segment",label:"",measure:true}]})}>+ Связь</button></div>{graphDraft.segments.map((s,i)=><div className="graph-geometry-row" key={i}><select value={s.a} onChange={e=>setGraphDraft({...graphDraft,segments:graphDraft.segments.map((q,j)=>j===i?{...q,a:Number(e.target.value)}:q)})}>{graphDraft.points.map((p,j)=><option key={j} value={j}>{p.label||j+1}</option>)}</select><select value={s.kind} onChange={e=>setGraphDraft({...graphDraft,segments:graphDraft.segments.map((q,j)=>j===i?{...q,kind:e.target.value as "segment"|"line"|"ray"}:q)})}><option value="segment">Отрезок</option><option value="line">Прямая</option><option value="ray">Луч</option></select><select value={s.b} onChange={e=>setGraphDraft({...graphDraft,segments:graphDraft.segments.map((q,j)=>j===i?{...q,b:Number(e.target.value)}:q)})}>{graphDraft.points.map((p,j)=><option key={j} value={j}>{p.label||j+1}</option>)}</select><label className="graph-measure"><input type="checkbox" checked={s.measure} onChange={e=>setGraphDraft({...graphDraft,segments:graphDraft.segments.map((q,j)=>j===i?{...q,measure:e.target.checked}:q)})}/>↔</label><button type="button" onClick={()=>setGraphDraft({...graphDraft,segments:graphDraft.segments.filter((_,j)=>j!==i)})}>×</button></div>)}</div>{graphDraft.points.length>=3&&<div className="graph-geometry-section"><div className="graph-points-head"><strong>Углы</strong><button type="button" onClick={()=>setGraphDraft({...graphDraft,angles:[...graphDraft.angles,{a:0,vertex:1,b:2,label:""}]})}>+ Угол</button></div>{graphDraft.angles.map((g,i)=><div className="graph-angle-row" key={i}>{(["a","vertex","b"] as const).map(k=><select key={k} value={g[k]} onChange={e=>setGraphDraft({...graphDraft,angles:graphDraft.angles.map((q,j)=>j===i?{...q,[k]:Number(e.target.value)}:q)})}>{graphDraft.points.map((p,j)=><option key={j} value={j}>{p.label||j+1}</option>)}</select>)}<button type="button" onClick={()=>setGraphDraft({...graphDraft,angles:graphDraft.angles.filter((_,j)=>j!==i)})}>×</button></div>)}</div>}</>}{graphDraft.points.length===0?`);

fs.writeFileSync("src/App.tsx",a);
let c=fs.readFileSync("src/App.css","utf8");
if(!c.includes("/* v57 · geometry measurements */"))c+=`
/* v57 · geometry measurements */
.graph-geometry line{stroke:#d34f66;stroke-width:2.2;vector-effect:non-scaling-stroke}.graph-geometry text{fill:#a3384b;font-size:12px;font-weight:700;paint-order:stroke;stroke:#fff;stroke-width:4px}.graph-angle-label{fill:#176c59!important}.graph-geometry-section{border-top:1px solid #ececf1;margin-top:8px;padding-top:9px;display:flex;flex-direction:column;gap:6px}.graph-geometry-row{display:grid;grid-template-columns:1fr 1.4fr 1fr 34px 28px;gap:4px}.graph-angle-row{display:grid;grid-template-columns:1fr 1fr 1fr 28px;gap:4px}.graph-geometry-row select,.graph-angle-row select{min-width:0;border:1px solid #dfe0e7;border-radius:7px;padding:5px;background:#fff}.graph-geometry-row button,.graph-angle-row button{border:1px solid #eadde0;background:#fff7f8;color:#b74455;border-radius:7px;cursor:pointer}.graph-measure{display:flex!important;align-items:center!important;justify-content:center;gap:2px!important}
`;
fs.writeFileSync("src/App.css",c);
console.log("v57 установлен. Запустите npm run build");
