import fs from "node:fs";
for(const p of ["src/App.tsx","src/MaterialsScreen.tsx","src/materialsStore.ts","src/App.css"])if(!fs.existsSync(p)){console.error("v45: не найден "+p);process.exit(1)}
let m=fs.readFileSync("src/MaterialsScreen.tsx","utf8");
m=m.replace('deleteMaterial,downloadMaterial,listMaterials,renameMaterial,uploadMaterial,type Material','deleteMaterial,downloadMaterial,listMaterials,renameMaterial,setMaterialFavorite,uploadMaterial,type Material');
m=m.replace('const [rows,setRows]=useState<Material[]>([]),[query,setQuery]=useState(""),[folder,setFolder]=useState("all")','const [rows,setRows]=useState<Material[]>([]),[query,setQuery]=useState(""),[folder,setFolder]=useState("all"),[favoritesOnly,setFavoritesOnly]=useState(false)');
m=m.replace('const visible=rows.filter(x=>(folder==="all"||x.folder===folder)&&(!query.trim()||`${x.title} ${x.fileName} ${x.folder}`.toLowerCase().includes(query.toLowerCase())));','const visible=rows.filter(x=>(!favoritesOnly||x.favorite)&&(folder==="all"||x.folder===folder)&&(!query.trim()||`${x.title} ${x.fileName} ${x.folder}`.toLowerCase().includes(query.toLowerCase())));');
m=m.replace('<span>{visible.length} файлов · {size(visible.reduce((n,x)=>n+x.size,0))}</span>','<button className={favoritesOnly?"materials-fav active":"materials-fav"} onClick={()=>setFavoritesOnly(x=>!x)}>★ Избранное</button><span>{visible.length} файлов · {size(visible.reduce((n,x)=>n+x.size,0))}</span>');
m=m.replace('<div className="material-actions"><button onClick={()=>void downloadMaterial(m).catch(e=>setNotice(e.message))}>Скачать</button>','<div className="material-actions"><button className={m.favorite?"favorite active":"favorite"} title="Избранное" onClick={async()=>{await setMaterialFavorite(m.id,!m.favorite);await load()}}>★</button><button onClick={()=>{sessionStorage.setItem("onlinerepetitor.material.pick",JSON.stringify({id:m.id,title:m.title,fileName:m.fileName,mime:m.mime,storagePath:m.storagePath}));setNotice("Материал выбран. Откройте нужную доску, чтобы вставить его.")}}>На доску</button><button onClick={()=>void downloadMaterial(m).catch(e=>setNotice(e.message))}>Скачать</button>');
fs.writeFileSync("src/MaterialsScreen.tsx",m);

let a=fs.readFileSync("src/App.tsx","utf8");
if(!a.includes('from "./materialsStore"'))a=a.replace('import MaterialsScreen from "./MaterialsScreen";','import MaterialsScreen from "./MaterialsScreen";\nimport { materialBlob,markMaterialUsed,type Material } from "./materialsStore";');
const anchor='  const openMediaAsset = async (item: Item) => {';
if(!a.includes("onlinerepetitor.material.pick")){if(!a.includes(anchor)){console.error("v45: не найден addMediaFile");process.exit(1)}a=a.replace(anchor,`  useEffect(()=>{if(!canEdit)return;let raw=sessionStorage.getItem("onlinerepetitor.material.pick");if(!raw)return;sessionStorage.removeItem("onlinerepetitor.material.pick");(async()=>{try{const picked=JSON.parse(raw) as Pick<Material,"id"|"title"|"fileName"|"mime"|"storagePath">;if(!picked.id||!(picked.mime.startsWith("image/")||picked.mime==="application/pdf")){setNotice("На доску сейчас можно вставить изображение или PDF");return}const blob=await materialBlob(picked as Material);const file=new File([blob],picked.fileName,{type:picked.mime});await addMediaFile(file);await markMaterialUsed(picked.id);setNotice(\`Материал «\${picked.title}» добавлен на доску\`)}catch(e){setNotice(e instanceof Error?e.message:"Не удалось добавить материал")}})()},[boardSummary.id,canEdit]);\n\n${anchor}`)}
fs.writeFileSync("src/App.tsx",a);
let c=fs.readFileSync("src/App.css","utf8");if(!c.includes("/* v45 · reusable materials */"))c+=`
/* v45 · reusable materials */
.materials-toolbar{grid-template-columns:minmax(220px,1fr) 180px auto auto}.materials-fav{border:1px solid #dedfe7;border-radius:8px;background:#fff;padding:8px 10px;font-size:9px;cursor:pointer}.materials-fav.active,.material-actions .favorite.active{background:#fff3c9;color:#8b6b00;border-color:#ecd77b}.material-actions .favorite{font-size:11px;padding:3px 7px}.material-card:has(.favorite.active){border-color:#e5d486;box-shadow:0 2px 12px #d7c66c20}
@media(max-width:560px){.materials-toolbar{grid-template-columns:1fr}}
`;fs.writeFileSync("src/App.css",c);console.log("v45 установлен. Выполните SQL, затем npm run build");
