import fs from "node:fs";
for(const p of ["src/App.tsx","src/BoardsScreen.tsx","src/App.css"])if(!fs.existsSync(p)){console.error("v46: не найден "+p);process.exit(1)}
let a=fs.readFileSync("src/App.tsx","utf8");
a=a.replace('import MaterialsScreen from "./MaterialsScreen";','import MaterialsScreen from "./MaterialsScreen";\nimport TemplatesScreen from "./TemplatesScreen";\nimport { createTemplate } from "./templatesStore";');
a=a.replace(': section==="materials"\n          ? <MaterialsScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} />\n          : <BoardsScreen',': section==="materials"\n          ? <MaterialsScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} />\n          : section==="templates"\n          ? <TemplatesScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} onOpenBoard={(board)=>navigate(`/board/${board.id}`)} />\n          : <BoardsScreen');
const anchor='  const commit = (next: Item[]) => {';
if(!a.includes("onlinerepetitor.template.apply"))a=a.replace(anchor,`  useEffect(()=>{const raw=sessionStorage.getItem("onlinerepetitor.template.apply");if(!raw||!canEdit)return;sessionStorage.removeItem("onlinerepetitor.template.apply");try{const x=JSON.parse(raw);if(!x?.document?.items)return;const data={...x.document,title:boardSummary.title,view:{x:0,y:0,zoom:1}};applyDocument(data);setNotice("Шаблон применён к новой доске")}catch{setNotice("Не удалось применить шаблон")}},[boardSummary.id,canEdit]);\n\n${anchor}`);
const saveAnchor='  const finishEdit = () => {';
if(!a.includes("Сохранить текущую доску как шаблон"))a=a.replace(saveAnchor,`  const saveAsTemplate=async()=>{if(boardSummary.role!=="owner"){setNotice("Только владелец может создавать шаблоны");return}const title=window.prompt("Название шаблона",boardSummary.title);if(!title)return;const category=window.prompt("Категория шаблона, например «Алгебра»","")??"";const description=window.prompt("Краткое описание","")??"";try{await createTemplate(authUser.id,title,description,category,currentDocument());setNotice("Шаблон сохранён. Он появился в разделе «Шаблоны».")}catch(e){setNotice(e instanceof Error?e.message:"Не удалось сохранить шаблон")}};\n\n${saveAnchor}`);
const marker='<button className="topbar-button" onClick={exportBackup} title="Скачать резервную копию доски">';
// add toolbar button near backup export when that anchor exists
if 'onClick={()=>void saveAsTemplate()}' not in a:
    needle='title="Скачать резервную копию доски"'
    const pos=a.indexOf(needle);if(pos>=0){const start=a.lastIndexOf("<button",pos);a=a.slice(0,start)+'<button className="topbar-button" onClick={()=>void saveAsTemplate()} title="Сохранить текущую доску как шаблон">Шаблон</button>'+a.slice(start)}else console.warn("v46: кнопка шаблона не добавлена, якорь не найден")
fs.writeFileSync("src/App.tsx",a)
let b=fs.readFileSync("src/BoardsScreen.tsx","utf8");b=b.replace('<button onClick={()=>{window.history.pushState({},"","/?section=materials");window.dispatchEvent(new PopStateEvent("popstate"))}}>Материалы</button>','<button onClick={()=>{window.history.pushState({},"","/?section=materials");window.dispatchEvent(new PopStateEvent("popstate"))}}>Материалы</button><button onClick={()=>{window.history.pushState({},"","/?section=templates");window.dispatchEvent(new PopStateEvent("popstate"))}}>Шаблоны</button>');fs.writeFileSync("src/BoardsScreen.tsx",b);
let c=fs.readFileSync("src/App.css","utf8");if(!c.includes("/* v46 · templates */"))c+=`
/* v46 · templates */
.templates-shell{min-height:100vh;background:#f6f6f9;color:#292a34}.templates-content{max-width:1180px;margin:auto;padding:22px 24px 56px}.templates-toolbar{display:grid;grid-template-columns:1fr 190px auto;gap:8px;align-items:center;margin:16px 0}.templates-toolbar input,.templates-toolbar select{border:1px solid #dedfe7;border-radius:9px;background:#fff;padding:9px}.templates-toolbar span{font-size:9px;color:#858895}.templates-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.template-card{border:1px solid #e1e2e9;border-radius:13px;background:#fff;overflow:hidden}.template-preview{height:120px;position:relative;display:grid;place-content:center;background:#fafafe;color:#5c5fc2}.template-preview .board-card-grid{position:absolute;inset:0}.template-preview b,.template-preview small{z-index:1;text-align:center}.template-preview b{font-size:22px}.template-preview small{font-size:8px}.template-card>div:last-child{padding:11px;display:grid;gap:5px}.template-card strong{font-size:11px}.template-card span{font-size:8px;color:#858895}.template-card p{font-size:9px;min-height:28px;margin:3px 0;color:#666a76}.template-card>div:last-child>div{display:flex;gap:6px}.template-card .danger{border:1px solid #eee0e0;background:#fff;border-radius:7px;color:#a64a4a;padding:6px 8px;font-size:8px}
@media(max-width:800px){.templates-grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.templates-content{padding:14px}.templates-toolbar{grid-template-columns:1fr}.templates-grid{grid-template-columns:1fr}}
`;fs.writeFileSync("src/App.css",c);console.log("v46 установлен. Выполните SQL, затем npm run build");
