import fs from "node:fs";
for(const p of ["src/App.tsx","src/boardModel.ts","src/App.css"])if(!fs.existsSync(p)){console.error("v55: не найден "+p);process.exit(1)}
let m=fs.readFileSync("src/boardModel.ts","utf8");
m=m.replace(' | "formula" | "checklist"',' | "formula" | "graph" | "checklist"');
m=m.replace('  tableCompact?: boolean;\n  resolved?: boolean;','  tableCompact?: boolean;\n  graphType?: "linear" | "quadratic" | "sin" | "cos";\n  graphA?: number; graphB?: number; graphC?: number;\n  graphXMin?: number; graphXMax?: number; graphYMin?: number; graphYMax?: number;\n  graphGrid?: boolean;\n  resolved?: boolean;');
m=m.replace('"comment","table","formula","checklist"','"comment","table","formula","graph","checklist"');
if(!m.includes('if (i.kind === "graph")'))m=m.replace('    if (i.kind === "table") {',`    if (i.kind === "graph") {
      if (i.graphType != null && !["linear","quadratic","sin","cos"].includes(i.graphType)) throw new Error("Повреждён тип графика");
      for (const value of [i.graphA,i.graphB,i.graphC,i.graphXMin,i.graphXMax,i.graphYMin,i.graphYMax]) if (value != null && !finite(value)) throw new Error("Повреждены параметры графика");
      if (i.graphGrid != null && typeof i.graphGrid !== "boolean") throw new Error("Повреждена сетка графика");
      if ((i.graphXMin ?? -10) >= (i.graphXMax ?? 10) || (i.graphYMin ?? -10) >= (i.graphYMax ?? 10)) throw new Error("Повреждён диапазон графика");
    }
    if (i.kind === "table") {`);
fs.writeFileSync("src/boardModel.ts",m);

let a=fs.readFileSync("src/App.tsx","utf8");
a=a.replace('  | "formula"\n  | "checklist"','  | "formula"\n  | "graph"\n  | "checklist"');
a=a.replace('    case "formula": return <><path d="M5 7h7l-5 10h7"/><path d="M16 8c1.8 0 3 1.2 3 3s-1.2 3-3 3M18.5 7.5l1.5-1.5"/></>;','    case "formula": return <><path d="M5 7h7l-5 10h7"/><path d="M16 8c1.8 0 3 1.2 3 3s-1.2 3-3 3M18.5 7.5l1.5-1.5"/></>;\n    case "graph": return <><path d="M4 19V5M4 12h16"/><path d="M6 16c3-1 4-8 7-8s3 5 7 3"/></>;');
a=a.replace('  { id: "formula", icon: "formula", label: "Формула · X / Ч" },','  { id: "formula", icon: "formula", label: "Формула · X / Ч" },\n  { id: "graph", icon: "graph", label: "График функции · Y / Н" },');
a=a.replace('  KeyX: "formula",','  KeyX: "formula",\n  KeyY: "graph",');
if(!a.includes('function GraphView('))a=a.replace('function TableView({ item }',`function GraphView({ item }: { item: Item }) {
  const type=item.graphType ?? "quadratic", A=item.graphA ?? 1, B=item.graphB ?? 0, C=item.graphC ?? 0;
  const xMin=item.graphXMin ?? -10, xMax=item.graphXMax ?? 10, yMin=item.graphYMin ?? -10, yMax=item.graphYMax ?? 10;
  const W=600,H=360, sx=(x:number)=>(x-xMin)/(xMax-xMin)*W, sy=(y:number)=>H-(y-yMin)/(yMax-yMin)*H;
  const f=(x:number)=>type==="linear"?A*x+B:type==="quadratic"?A*x*x+B*x+C:type==="sin"?A*Math.sin(B*x+C):A*Math.cos(B*x+C);
  const pts=Array.from({length:241},(_,i)=>{const x=xMin+(xMax-xMin)*i/240;return [sx(x),sy(f(x))] as const}).filter(p=>Number.isFinite(p[1])&&p[1]>-H*3&&p[1]<H*4);
  const path=pts.map((p,i)=>(i?"L":"M")+p[0].toFixed(1)+" "+p[1].toFixed(1)).join(" ");
  const gridX=Array.from({length:Math.min(21,Math.max(0,Math.floor(xMax-xMin)+1))},(_,i)=>Math.ceil(xMin)+i).filter(v=>v<=xMax);
  const gridY=Array.from({length:Math.min(21,Math.max(0,Math.floor(yMax-yMin)+1))},(_,i)=>Math.ceil(yMin)+i).filter(v=>v<=yMax);
  const label=type==="linear"?\`y = \${A}x \${B>=0?"+ ":"- "}\${Math.abs(B)}\`:type==="quadratic"?\`y = \${A}x² \${B>=0?"+ ":"- "}\${Math.abs(B)}x \${C>=0?"+ ":"- "}\${Math.abs(C)}\`:type==="sin"?\`y = \${A}·sin(\${B}x \${C>=0?"+ ":"- "}\${Math.abs(C)})\`:\`y = \${A}·cos(\${B}x \${C>=0?"+ ":"- "}\${Math.abs(C)})\`;
  return <div className="graph-view"><div className="graph-label">{label}</div><svg viewBox={\`0 0 \${W} \${H}\`} preserveAspectRatio="none">{item.graphGrid!==false&&<g className="graph-grid">{gridX.map(x=><line key={"x"+x} x1={sx(x)} x2={sx(x)} y1="0" y2={H}/>)}{gridY.map(y=><line key={"y"+y} x1="0" x2={W} y1={sy(y)} y2={sy(y)}/>)}</g>}<g className="graph-axes">{xMin<=0&&xMax>=0&&<line x1={sx(0)} x2={sx(0)} y1="0" y2={H}/>} {yMin<=0&&yMax>=0&&<line x1="0" x2={W} y1={sy(0)} y2={sy(0)}/>}</g><path className="graph-curve" d={path}/></svg></div>;
}

function TableView({ item }`);
if(!a.includes('graphEditorId'))a=a.replace('  const [formulaEditorId, setFormulaEditorId] = useState<string | null>(null);','  const [graphEditorId, setGraphEditorId] = useState<string | null>(null);\n  const [graphDraft, setGraphDraft] = useState<{type:"linear"|"quadratic"|"sin"|"cos";a:number;b:number;c:number;xMin:number;xMax:number;yMin:number;yMax:number;grid:boolean}|null>(null);\n  const [formulaEditorId, setFormulaEditorId] = useState<string | null>(null);');
if(!a.includes('const openGraphEditor ='))a=a.replace('  const openFormulaEditor = (item: Item) => {',`  const openGraphEditor = (item: Item) => {
    if(item.kind!=="graph"||item.locked)return; setSelected([item.id]); setGraphEditorId(item.id);
    setGraphDraft({type:item.graphType??"quadratic",a:item.graphA??1,b:item.graphB??0,c:item.graphC??0,xMin:item.graphXMin??-10,xMax:item.graphXMax??10,yMin:item.graphYMin??-10,yMax:item.graphYMax??10,grid:item.graphGrid!==false});
  };
  const closeGraphEditor=()=>{setGraphEditorId(null);setGraphDraft(null)};
  const saveGraphEditor=()=>{if(!graphEditorId||!graphDraft){closeGraphEditor();return} const d={...graphDraft,xMin:Math.min(graphDraft.xMin,graphDraft.xMax-1),xMax:Math.max(graphDraft.xMax,graphDraft.xMin+1),yMin:Math.min(graphDraft.yMin,graphDraft.yMax-1),yMax:Math.max(graphDraft.yMax,graphDraft.yMin+1)}; commit(itemsRef.current.map(item=>item.id===graphEditorId?{...item,graphType:d.type,graphA:d.a,graphB:d.b,graphC:d.c,graphXMin:d.xMin,graphXMax:d.xMax,graphYMin:d.yMin,graphYMax:d.yMax,graphGrid:d.grid}:item)); closeGraphEditor(); setNotice("График сохранён")};

  const openFormulaEditor = (item: Item) => {`);
a=a.replace('    } else if (tool === "formula") {','    } else if (tool === "graph") {\n      e.preventDefault(); const item: Item={id:crypto.randomUUID(),kind:"graph",x:p.x-260,y:p.y-170,width:520,height:340,text:"",graphType:"quadratic",graphA:1,graphB:0,graphC:0,graphXMin:-10,graphXMax:10,graphYMin:-10,graphYMax:10,graphGrid:true,color:"#5355c9"}; commit([...itemsRef.current,item]);setSelected([item.id]);setTool("select");window.setTimeout(()=>openGraphEditor(item),0);return;\n    } else if (tool === "formula") {');
a=a.replace('  if (item.kind === "formula") return item.text.trim().replace(/\\s+/g, " ").slice(0, 44) || "Формула";','  if (item.kind === "formula") return item.text.trim().replace(/\\s+/g, " ").slice(0, 44) || "Формула";\n  if (item.kind === "graph") return "График функции";');
a=a.replace('  if (item.kind === "formula") return "Формула";','  if (item.kind === "formula") return "Формула";\n  if (item.kind === "graph") return "График функции";');
a=a.replace('  if (item.kind === "formula") return "formula";','  if (item.kind === "formula") return "formula";\n  if (item.kind === "graph") return "graph";');
a=a.replace('{item.kind === "formula" && <FormulaView text={item.text} fontSize={item.fontSize ?? 28} color={item.color ?? "#20242c"} />}','{item.kind === "formula" && <FormulaView text={item.text} fontSize={item.fontSize ?? 28} color={item.color ?? "#20242c"} />}\n                {item.kind === "graph" && <GraphView item={item}/>}');
a=a.replace('} else if (tool === "select" && !space && !item.locked && item.kind === "quiz") {','} else if (tool === "select" && !space && !item.locked && item.kind === "graph") { setSelected([item.id]); openGraphEditor(item);\n                  } else if (tool === "select" && !space && !item.locked && item.kind === "quiz") {');
if(!a.includes('className="graph-editor-backdrop"'))a=a.replace('        {formulaEditorId && formulaDraft && (',`        {graphEditorId && graphDraft && (<div className="graph-editor-backdrop" onPointerDown={closeGraphEditor}><div className="graph-editor-modal" role="dialog" aria-modal="true" onPointerDown={(e)=>e.stopPropagation()}><div className="graph-editor-header"><div><strong>График функции</strong><span>Координатная плоскость и параметры функции</span></div><button onClick={closeGraphEditor}><Icon name="close" size={17}/></button></div><div className="graph-editor-body"><div className="graph-editor-form"><label><span>Тип функции</span><select value={graphDraft.type} onChange={e=>setGraphDraft({...graphDraft,type:e.target.value as "linear"|"quadratic"|"sin"|"cos"})}><option value="linear">Линейная y = ax + b</option><option value="quadratic">Парабола y = ax² + bx + c</option><option value="sin">Синус y = a·sin(bx+c)</option><option value="cos">Косинус y = a·cos(bx+c)</option></select></label><div className="graph-coefficients">{(["a","b","c"] as const).map(k=><label key={k}><span>{k}</span><input type="number" step="0.1" value={graphDraft[k]} onChange={e=>setGraphDraft({...graphDraft,[k]:Number(e.target.value)})}/></label>)}</div><strong>Диапазон осей</strong><div className="graph-ranges"><label>X min<input type="number" value={graphDraft.xMin} onChange={e=>setGraphDraft({...graphDraft,xMin:Number(e.target.value)})}/></label><label>X max<input type="number" value={graphDraft.xMax} onChange={e=>setGraphDraft({...graphDraft,xMax:Number(e.target.value)})}/></label><label>Y min<input type="number" value={graphDraft.yMin} onChange={e=>setGraphDraft({...graphDraft,yMin:Number(e.target.value)})}/></label><label>Y max<input type="number" value={graphDraft.yMax} onChange={e=>setGraphDraft({...graphDraft,yMax:Number(e.target.value)})}/></label></div><label className="graph-grid-toggle"><input type="checkbox" checked={graphDraft.grid} onChange={e=>setGraphDraft({...graphDraft,grid:e.target.checked})}/> Показывать сетку</label></div><div className="graph-editor-preview"><GraphView item={{id:"preview",kind:"graph",x:0,y:0,width:520,height:340,text:"",graphType:graphDraft.type,graphA:graphDraft.a,graphB:graphDraft.b,graphC:graphDraft.c,graphXMin:graphDraft.xMin,graphXMax:graphDraft.xMax,graphYMin:graphDraft.yMin,graphYMax:graphDraft.yMax,graphGrid:graphDraft.grid}}/></div></div><div className="graph-editor-footer"><span>Ctrl+Enter — сохранить</span><div><button className="secondary" onClick={closeGraphEditor}>Отмена</button><button className="primary" onClick={saveGraphEditor}><Icon name="check" size={15}/> Сохранить</button></div></div></div></div>)}
        {formulaEditorId && formulaDraft && (`);
// v54 repair: the data tab existed, but the visible tab list missed it
a=a.replace('["functions", "Функции"], ["templates", "Шаблоны"],','["functions", "Функции"], ["geometry", "Геометрия"], ["templates", "Шаблоны"],');
fs.writeFileSync("src/App.tsx",a);
let c=fs.readFileSync("src/App.css","utf8");
if(!c.includes("/* v55 · graphs */"))c+=`\n/* v55 · graphs */\n.graph-view{width:100%;height:100%;position:relative;background:#fff;border-radius:10px;overflow:hidden}.graph-view svg{width:100%;height:100%;display:block}.graph-label{position:absolute;left:10px;top:8px;z-index:1;background:rgba(255,255,255,.9);padding:4px 7px;border-radius:6px;font-size:12px;font-weight:600}.graph-grid line{stroke:#e8e9ef;stroke-width:1}.graph-axes line{stroke:#747887;stroke-width:1.6}.graph-curve{fill:none;stroke:#5355c9;stroke-width:3;vector-effect:non-scaling-stroke}.graph-editor-backdrop{position:fixed;inset:0;z-index:1200;background:rgba(25,27,36,.38);display:grid;place-items:center;padding:24px}.graph-editor-modal{width:min(940px,94vw);max-height:90vh;overflow:auto;background:#fff;border-radius:16px;box-shadow:0 24px 70px rgba(20,22,30,.24)}.graph-editor-header,.graph-editor-footer{display:flex;align-items:center;justify-content:space-between;padding:15px 18px;border-bottom:1px solid #ececf1}.graph-editor-header div{display:flex;flex-direction:column;gap:2px}.graph-editor-header span,.graph-editor-footer>span{font-size:12px;color:#777b88}.graph-editor-header button{border:0;background:transparent;cursor:pointer}.graph-editor-body{display:grid;grid-template-columns:300px 1fr;gap:18px;padding:18px}.graph-editor-form{display:flex;flex-direction:column;gap:13px}.graph-editor-form label{display:flex;flex-direction:column;gap:5px;font-size:12px}.graph-editor-form input,.graph-editor-form select{border:1px solid #dfe0e7;border-radius:8px;padding:8px;background:#fff}.graph-coefficients,.graph-ranges{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.graph-ranges{grid-template-columns:repeat(2,1fr)}.graph-grid-toggle{flex-direction:row!important;align-items:center}.graph-editor-preview{min-height:360px;border:1px solid #e5e6ed;border-radius:12px;overflow:hidden}.graph-editor-footer{border-top:1px solid #ececf1;border-bottom:0}.graph-editor-footer>div{display:flex;gap:8px}@media(max-width:760px){.graph-editor-body{grid-template-columns:1fr}.graph-editor-preview{min-height:280px}}\n`;
fs.writeFileSync("src/App.css",c);
console.log("v55 установлен. Запустите npm run build");
