import fs from "node:fs";
for(const p of ["src/App.tsx","src/BoardsScreen.tsx","src/App.css"])if(!fs.existsSync(p)){console.error("v51: не найден "+p);process.exit(1)}
let a=fs.readFileSync("src/App.tsx","utf8");
if(!a.includes('ProfileScreen'))a=a.replace('import NotificationsScreen from "./NotificationsScreen";','import NotificationsScreen from "./NotificationsScreen";\nimport ProfileScreen from "./ProfileScreen";\nimport { applyProfileAppearance,getProfileSettings } from "./profileStore";');
a=a.replace(': section==="notifications"\n          ? <NotificationsScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} />\n          : <BoardsScreen',': section==="notifications"\n          ? <NotificationsScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} />\n          : section==="profile"\n          ? <ProfileScreen user={authUser} onBack={()=>{window.history.pushState({}, "", "/");window.dispatchEvent(new PopStateEvent("popstate"))}} />\n          : <BoardsScreen');
fs.writeFileSync("src/App.tsx",a);
let b=fs.readFileSync("src/BoardsScreen.tsx","utf8");
b=b.replace('<button className="boards-secondary" onClick={onLogout}>Выйти</button>','<button className="boards-secondary" onClick={()=>{window.history.pushState({},"","/?section=profile");window.dispatchEvent(new PopStateEvent("popstate"))}}>⚙ Настройки</button><button className="boards-secondary" onClick={onLogout}>Выйти</button>');
fs.writeFileSync("src/BoardsScreen.tsx",b);
for(const f of ["src/StudentsScreen.tsx","src/AssignmentsScreen.tsx","src/ProgressScreen.tsx","src/ScheduleScreen.tsx","src/MaterialsScreen.tsx","src/NotificationsScreen.tsx"]){if(!fs.existsSync(f))continue;let s=fs.readFileSync(f,"utf8");if(!s.includes('/?section=profile')){const nav='</nav>';const i=s.indexOf(nav);if(i>=0)s=s.slice(0,i)+'<button onClick={()=>{window.history.pushState({},"","/?section=profile");window.dispatchEvent(new PopStateEvent("popstate"))}}>Настройки</button>'+s.slice(i)}fs.writeFileSync(f,s)}
let c=fs.readFileSync("src/App.css","utf8");if(!c.includes("/* v51 · profile */"))c+=`
/* v51 · profile */
.profile-shell{min-height:100vh;background:#f6f6f9;color:#292a34}.profile-content{max-width:1080px;margin:auto;padding:22px 24px 60px}.profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}.profile-card{background:#fff;border:1px solid #e1e2e9;border-radius:12px;padding:16px;display:grid;gap:12px}.profile-card h2{font-size:13px;margin:0}.profile-card label{display:grid;gap:5px;font-size:9px}.profile-card input,.profile-card select{border:1px solid #dcdde5;border-radius:8px;padding:9px;background:#fff}.profile-card small{font-size:8px;color:#858895}.profile-check{grid-template-columns:1fr auto!important;align-items:center}.profile-check input{width:18px;height:18px;accent-color:#5b5dc4}.compact-ui .boards-content,.compact-ui .students-content,.compact-ui .assignments-content,.compact-ui .progress-content,.compact-ui .schedule-content,.compact-ui .materials-content,.compact-ui .notifications-content,.compact-ui .profile-content{padding-top:12px}.compact-ui .board-card-body{padding:8px}[data-theme="dark"] .profile-shell{background:#1d1e24;color:#eee}[data-theme="dark"] .profile-card{background:#272830;border-color:#3a3b45}[data-theme="dark"] .profile-card input,[data-theme="dark"] .profile-card select{background:#202127;color:#eee;border-color:#454650}@media(max-width:720px){.profile-grid{grid-template-columns:1fr}}
`;fs.writeFileSync("src/App.css",c);console.log("v51 установлен. Выполните SQL, затем npm run build");
