import fs from "node:fs";
for(const p of ["src/StudentsScreen.tsx","src/AssignmentsScreen.tsx","src/studentsStore.ts","src/App.css"])if(!fs.existsSync(p)){console.error("v48: не найден "+p);process.exit(1)}
let st=fs.readFileSync("src/studentsStore.ts","utf8");
if(!st.includes("export async function saveStudentProfile"))st+=`
export async function saveStudentProfile(userId:string,note:string,tags:string[]){
 saveLocal(NOTES_KEY,userId,note);saveLocal(TAGS_KEY,userId,tags);
 if(!isRemoteBackendEnabled())return;
 await remoteRequest("/rest/v1/student_profiles?on_conflict=teacher_id,student_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({student_id:userId,note,tags})});
}
`;
fs.writeFileSync("src/studentsStore.ts",st);
let s=fs.readFileSync("src/StudentsScreen.tsx","utf8");
s=s.replace("deleteStudentSession,getStudentsForTeacher,saveStudentNote,saveStudentSession,saveStudentTags,","deleteStudentSession,getStudentsForTeacher,saveStudentProfile,saveStudentSession,");
if(!s.includes('from "./materialLinksStore"'))s=s.replace('} from "./studentsStore";','} from "./studentsStore";\nimport { listStudentMaterials,unlinkMaterial,type MaterialLink } from "./materialLinksStore";\nimport { downloadMaterial,type Material } from "./materialsStore";');
s=s.replace('const [note,setNote]=useState(""),[tags,setTags]=useState(""),[notice,setNotice]=useState("");','const [note,setNote]=useState(""),[tags,setTags]=useState(""),[notice,setNotice]=useState("");\n const [linkedMaterials,setLinkedMaterials]=useState<MaterialLink[]>([]);');
s=s.replace('useEffect(()=>{setNote(student?.note||"");setTags(student?.tags.join(", ")||"")},[selected,student?.note]);','useEffect(()=>{setNote(student?.note||"");setTags(student?.tags.join(", ")||"");if(student)void listStudentMaterials(student.userId).then(setLinkedMaterials).catch(()=>setLinkedMaterials([]));else setLinkedMaterials([])},[selected,student?.note]);');
s=s.replace('void Promise.all([saveStudentNote(student.userId,note),saveStudentTags(student.userId,parsed)]).catch(()=>setNotice("Не удалось сохранить карточку на сервере"));','void saveStudentProfile(student.userId,note,parsed).catch(()=>setNotice("Не удалось сохранить карточку на сервере"));');
const boards='<div className="student-boards"><h3>Доски ученика</h3>';
const mats=`<div className="student-materials"><div className="student-section-head"><h3>Материалы ученика</h3><span>{linkedMaterials.length}</span></div>{linkedMaterials.length===0?<div className="student-history-empty">Материалы пока не назначены.</div>:linkedMaterials.map(m=><article key={m.id}><div><b>{m.materialTitle}</b><span>{m.assignmentId?"К заданию":"Личный материал"}</span></div><div><button onClick={()=>void downloadMaterial({id:m.materialId,ownerId:user.id,folder:"",title:m.materialTitle,fileName:m.fileName,mime:m.mime,size:0,storagePath:m.storagePath,createdAt:m.createdAt,favorite:false,useCount:0,lastUsedAt:null} as Material).catch(e=>setNotice(e.message))}>Скачать</button><button className="danger" onClick={async()=>{await unlinkMaterial(m.id);setLinkedMaterials(x=>x.filter(v=>v.id!==m.id))}}>Убрать</button></div></article>)}</div>`;
if(s.includes(boards)&&!s.includes('className="student-materials"'))s=s.replace(boards,mats+boards);
fs.writeFileSync("src/StudentsScreen.tsx",s);

let a=fs.readFileSync("src/AssignmentsScreen.tsx","utf8");
if(!a.includes('from "./materialsStore"'))a=a.replace('import { createAssignment,deleteAssignment,listAssignments,reviewAssignment,submitAssignment,type Assignment } from "./assignmentsStore";','import { createAssignment,deleteAssignment,listAssignments,reviewAssignment,submitAssignment,type Assignment } from "./assignmentsStore";\nimport { listMaterials,type Material } from "./materialsStore";\nimport { linkMaterial,listStudentMaterials,type MaterialLink } from "./materialLinksStore";');
a=a.replace('const [active,setActive]=useState<Assignment|null>(null),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState(""),[score,setScore]=useState("");','const [active,setActive]=useState<Assignment|null>(null),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState(""),[score,setScore]=useState("");\n const [materials,setMaterials]=useState<Material[]>([]),[materialId,setMaterialId]=useState(""),[linked,setLinked]=useState<MaterialLink[]>([]);');
a=a.replace('useEffect(()=>{void load()},[user.id]);','useEffect(()=>{void load();void listMaterials(user.id).then(setMaterials).catch(()=>setMaterials([]))},[user.id]);');
a=a.replace('const openRow=(a:Assignment)=>{setActive(a);setAnswer(a.submissionText);setFeedback(a.feedback);setScore(a.score==null?"":String(a.score))};','const openRow=(a:Assignment)=>{setActive(a);setAnswer(a.submissionText);setFeedback(a.feedback);setScore(a.score==null?"":String(a.score));void listStudentMaterials(a.studentId).then(x=>setLinked(x.filter(v=>v.assignmentId===a.id))).catch(()=>setLinked([]))};');
a=a.replace('<label className="wide"><span>Условие / инструкция</span><textarea rows={6} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Что нужно выполнить, какие материалы использовать…"/></label>','<label className="wide"><span>Условие / инструкция</span><textarea rows={6} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Что нужно выполнить, какие материалы использовать…"/></label><label className="wide"><span>Материал ученику</span><select value={materialId} onChange={e=>setMaterialId(e.target.value)}><option value="">Без материала</option>{materials.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label>');
a=a.replace('const a=await createAssignment({teacherId:user.id,studentId,boardId,boardTitle:board?.title||"Без доски",title,description,dueAt:due?new Date(due).toISOString():null,maxScore:Math.max(1,Number(maxScore)||100)});setRows','const a=await createAssignment({teacherId:user.id,studentId,boardId,boardTitle:board?.title||"Без доски",title,description,dueAt:due?new Date(due).toISOString():null,maxScore:Math.max(1,Number(maxScore)||100)});if(materialId)await linkMaterial(materialId,studentId,a.id);setMaterialId("");setRows');
a=a.replace('<p>{active.description||"Дополнительных инструкций нет."}</p>','<p>{active.description||"Дополнительных инструкций нет."}</p>{linked.length>0&&<div className="assignment-materials"><b>Материалы к заданию</b>{linked.map(m=><span key={m.id}>📎 {m.materialTitle}</span>)}</div>}');
fs.writeFileSync("src/AssignmentsScreen.tsx",a);
let c=fs.readFileSync("src/App.css","utf8");if(!c.includes("/* v48 · student materials */"))c+=`
/* v48 · student materials */
.student-materials{margin-top:16px}.student-materials article{display:flex;justify-content:space-between;gap:8px;padding:9px 0;border-top:1px solid #eeeef2}.student-materials article>div{display:grid;gap:2px}.student-materials b{font-size:10px}.student-materials span{font-size:8px;color:#858895}.student-materials button{border:1px solid #e1e2e8;background:#fff;border-radius:6px;padding:5px 7px;font-size:8px;cursor:pointer}.student-materials .danger{color:#a94a4a}.assignment-materials{display:grid;gap:4px;margin:10px 0;padding:9px;border-radius:9px;background:#f5f5fb}.assignment-materials b,.assignment-materials span{font-size:9px}
`;fs.writeFileSync("src/App.css",c);
console.log("v48 установлен. Выполните SQL, затем npm run build");
