import fs from "node:fs";
for(const p of ["src/App.tsx","src/AssignmentsScreen.tsx","src/ScheduleScreen.tsx","src/App.css"])if(!fs.existsSync(p)){console.error("v83: не найден "+p);process.exit(1)}

let a=fs.readFileSync("src/App.tsx","utf8");
a=a.replace('<AssignmentsScreen user={authUser} onBack=', '<AssignmentsScreen user={authUser} accountRole={accountRole} onBack=');
a=a.replace('<ScheduleScreen user={authUser} onBack=', '<ScheduleScreen user={authUser} accountRole={accountRole} onBack=');
a=a.replace(': section==="students"\n          ? <StudentsScreen', ': section==="students" && accountRole==="teacher"\n          ? <StudentsScreen');
fs.writeFileSync("src/App.tsx",a);

let x=fs.readFileSync("src/AssignmentsScreen.tsx","utf8");
x=x.replace('import type { AuthUser } from "./authStore";','import type { AuthUser } from "./authStore";\nimport type { AccountRole } from "./accountRoleStore";');
x=x.replace('type Props={user:AuthUser;onBack:()=>void;onOpenBoard:(board:BoardSummary)=>void};','type Props={user:AuthUser;accountRole:AccountRole;onBack:()=>void;onOpenBoard:(board:BoardSummary)=>void};');
x=x.replace('export default function AssignmentsScreen({user,onBack,onOpenBoard}:Props){','export default function AssignmentsScreen({user,accountRole,onBack,onOpenBoard}:Props){');
x=x.replace('const load=async()=>{setLoading(true);try{const [a,b,s]=await Promise.all([listAssignments(user.id),getUserBoards(user),getStudentsForTeacher(user).catch(()=>[])]);setRows(a);setBoards(b);setStudents(s)}catch(e){setNotice(e instanceof Error?e.message:"Не удалось загрузить задания")}finally{setLoading(false)}};',
'const load=async()=>{setLoading(true);try{const [a,b,s]=await Promise.all([listAssignments(user.id),getUserBoards(user),accountRole==="teacher"?getStudentsForTeacher(user).catch(()=>[]):Promise.resolve([])]);setRows(a);setBoards(b);setStudents(s)}catch(e){setNotice(e instanceof Error?e.message:"Не удалось загрузить задания")}finally{setLoading(false)}};');
x=x.replace('useEffect(()=>{void load();void listMaterials(user.id).then(setMaterials).catch(()=>setMaterials([]))},[user.id]);','useEffect(()=>{void load();if(accountRole==="teacher")void listMaterials(user.id).then(setMaterials).catch(()=>setMaterials([]));else setMaterials([])},[user.id,accountRole]);');
x=x.replace('const teacherRows=rows.filter(a=>a.teacherId===user.id);\n const isTeacher=teacherRows.length>0||students.length>0;','const isTeacher=accountRole==="teacher";');
const nav='<nav className="dashboard-nav"><button onClick={onBack}>Доски</button><button onClick={()=>{window.history.pushState({},"","/?section=students");window.dispatchEvent(new PopStateEvent("popstate"))}}>Ученики</button><button className="active">Задания</button><button onClick={()=>{window.history.pushState({},"","/?section=progress");window.dispatchEvent(new PopStateEvent("popstate"))}}>Прогресс</button><button onClick={()=>{window.history.pushState({},"","/?section=schedule");window.dispatchEvent(new PopStateEvent("popstate"))}}>Расписание</button><button onClick={()=>{window.history.pushState({},"","/?section=materials");window.dispatchEvent(new PopStateEvent("popstate"))}}>Материалы</button><button onClick={()=>{window.history.pushState({},"","/?section=notifications");window.dispatchEvent(new PopStateEvent("popstate"))}}>Уведомления</button><button onClick={()=>{window.history.pushState({},"","/?section=profile");window.dispatchEvent(new PopStateEvent("popstate"))}}>Настройки</button></nav>';
if(!x.includes(nav)){console.error("v83: assignments nav anchor не найден");process.exit(1)}
x=x.replace(nav,`<nav className="dashboard-nav"><button onClick={onBack}>Доски</button>{isTeacher&&<button onClick={()=>{window.history.pushState({},"","/?section=students");window.dispatchEvent(new PopStateEvent("popstate"))}}>Ученики</button>}<button className="active">Задания</button>{isTeacher&&<button onClick={()=>{window.history.pushState({},"","/?section=progress");window.dispatchEvent(new PopStateEvent("popstate"))}}>Прогресс</button>}<button onClick={()=>{window.history.pushState({},"","/?section=schedule");window.dispatchEvent(new PopStateEvent("popstate"))}}>Расписание</button>{isTeacher&&<button onClick={()=>{window.history.pushState({},"","/?section=materials");window.dispatchEvent(new PopStateEvent("popstate"))}}>Материалы</button>}<button onClick={()=>{window.history.pushState({},"","/?section=notifications");window.dispatchEvent(new PopStateEvent("popstate"))}}>Уведомления</button><button onClick={()=>{window.history.pushState({},"","/?section=profile");window.dispatchEvent(new PopStateEvent("popstate"))}}>Настройки</button></nav>{!isTeacher&&<div className="student-role-banner"><b>Мои задания</b><span>Здесь только работы, которые выдал преподаватель. Создание и проверка заданий ученику недоступны.</span></div>}`);
x=x.replace('{a.teacherId===user.id&&<button className="assignment-delete"', '{isTeacher&&a.teacherId===user.id&&<button className="assignment-delete"');
x=x.replace('{active.studentId===user.id&&active.teacherId!==user.id?', '{!isTeacher&&active.studentId===user.id?');
fs.writeFileSync("src/AssignmentsScreen.tsx",x);

let s=fs.readFileSync("src/ScheduleScreen.tsx","utf8");
s=s.replace('import type { AuthUser } from "./authStore";','import type { AuthUser } from "./authStore";\nimport type { AccountRole } from "./accountRoleStore";');
s=s.replace('type Props={user:AuthUser;onBack:()=>void;onOpenBoard:(b:BoardSummary)=>void};','type Props={user:AuthUser;accountRole:AccountRole;onBack:()=>void;onOpenBoard:(b:BoardSummary)=>void};');
s=s.replace('export default function ScheduleScreen({user,onBack,onOpenBoard}:Props){','export default function ScheduleScreen({user,accountRole,onBack,onOpenBoard}:Props){');
s=s.replace('const load=async()=>{setLoading(true);try{const [r,s,b]=await Promise.all([listScheduledLessons(user.id),getStudentsForTeacher(user).catch(()=>[]),getUserBoards(user)]);setRows(r);setStudents(s);setBoards(b)}catch(e){setNotice(e instanceof Error?e.message:"Не удалось загрузить расписание")}finally{setLoading(false)}};',
'const load=async()=>{setLoading(true);try{const [r,s,b]=await Promise.all([listScheduledLessons(user.id),accountRole==="teacher"?getStudentsForTeacher(user).catch(()=>[]):Promise.resolve([]),getUserBoards(user)]);setRows(r);setStudents(s);setBoards(b)}catch(e){setNotice(e instanceof Error?e.message:"Не удалось загрузить расписание")}finally{setLoading(false)}};');
s=s.replace('useEffect(()=>{void load()},[user.id]);','useEffect(()=>{void load()},[user.id,accountRole]);');
s=s.replace('const teacher=students.length>0||rows.some(x=>x.teacherId===user.id);','const teacher=accountRole==="teacher";');
nav2='<nav className="dashboard-nav"><button onClick={onBack}>Доски</button><button onClick={()=>{window.history.pushState({},"","/?section=students");window.dispatchEvent(new PopStateEvent("popstate"))}}>Ученики</button><button onClick={()=>{window.history.pushState({},"","/?section=assignments");window.dispatchEvent(new PopStateEvent("popstate"))}}>Задания</button><button onClick={()=>{window.history.pushState({},"","/?section=progress");window.dispatchEvent(new PopStateEvent("popstate"))}}>Прогресс</button><button className="active">Расписание</button><button onClick={()=>{window.history.pushState({},"","/?section=materials");window.dispatchEvent(new PopStateEvent("popstate"))}}>Материалы</button><button onClick={()=>{window.history.pushState({},"","/?section=notifications");window.dispatchEvent(new PopStateEvent("popstate"))}}>Уведомления</button><button onClick={()=>{window.history.pushState({},"","/?section=profile");window.dispatchEvent(new PopStateEvent("popstate"))}}>Настройки</button></nav>';
if(!s.includes(nav2)){console.error("v83: schedule nav anchor не найден");process.exit(1)}
s=s.replace(nav2,`<nav className="dashboard-nav"><button onClick={onBack}>Доски</button>{teacher&&<button onClick={()=>{window.history.pushState({},"","/?section=students");window.dispatchEvent(new PopStateEvent("popstate"))}}>Ученики</button>}<button onClick={()=>{window.history.pushState({},"","/?section=assignments");window.dispatchEvent(new PopStateEvent("popstate"))}}>Задания</button>{teacher&&<button onClick={()=>{window.history.pushState({},"","/?section=progress");window.dispatchEvent(new PopStateEvent("popstate"))}}>Прогресс</button>}<button className="active">Расписание</button>{teacher&&<button onClick={()=>{window.history.pushState({},"","/?section=materials");window.dispatchEvent(new PopStateEvent("popstate"))}}>Материалы</button>}<button onClick={()=>{window.history.pushState({},"","/?section=notifications");window.dispatchEvent(new PopStateEvent("popstate"))}}>Уведомления</button><button onClick={()=>{window.history.pushState({},"","/?section=profile");window.dispatchEvent(new PopStateEvent("popstate"))}}>Настройки</button></nav>{!teacher&&<div className="student-role-banner"><b>Моё расписание</b><span>Занятия назначает преподаватель. Ученик может просматривать время и открывать доступную доску занятия.</span></div>}`);
s=s.replace('{x.teacherId===user.id&&<button onClick={()=>start(x)}>Начать</button>}', '{teacher&&x.teacherId===user.id&&<button onClick={()=>start(x)}>Начать</button>}');
s=s.replace('{x.teacherId===user.id&&<button onClick={async()=>{await updateScheduledLesson', '{teacher&&x.teacherId===user.id&&<button onClick={async()=>{await updateScheduledLesson');
s=s.replace('{x.teacherId===user.id&&<button className="danger"', '{teacher&&x.teacherId===user.id&&<button className="danger"');
s=s.replace('{x.teacherId===user.id&&<button onClick={()=>start(x)}>Открыть доску →</button>}', '{teacher&&x.teacherId===user.id&&<button onClick={()=>start(x)}>Открыть доску →</button>}{!teacher&&x.boardId&&boards.some(b=>b.id===x.boardId)&&<button onClick={()=>start(x)}>Открыть доску →</button>}');
fs.writeFileSync("src/ScheduleScreen.tsx",s);

let c=fs.readFileSync("src/App.css","utf8");
if(!c.includes("/* v83 · role workspaces */"))c+=`
/* v83 · role workspaces */
.student-role-banner{display:flex;gap:10px;align-items:baseline;margin:12px 0;padding:11px 14px;border:1px solid var(--line,#dfe1e7);border-radius:13px;background:var(--panel,#fff)}.student-role-banner span{font-size:12px;opacity:.72}@media(max-width:650px){.student-role-banner{align-items:flex-start;flex-direction:column;gap:4px}}
`;
fs.writeFileSync("src/App.css",c);
console.log("v83 установлен. Выполните supabase/v83_role_workspaces.sql, затем npm run build.");
