import fs from "node:fs";
for(const p of ["src/App.tsx","src/boardModel.ts","src/App.css"])if(!fs.existsSync(p)){console.error("v60: не найден "+p);process.exit(1)}
let m=fs.readFileSync("src/boardModel.ts","utf8");
m=m.replace('  graphAxisLabels?: boolean;\n  resolved?: boolean;','  graphAxisLabels?: boolean;\n  graphGridStep?: number;\n  graphShowCurve?: boolean;\n  graphProjections?: boolean;\n  resolved?: boolean;');
if(!m.includes("Повреждён шаг сетки графика"))m=m.replace('      if (i.graphAxisLabels != null && typeof i.graphAxisLabels !== "boolean") throw new Error("Повреждены подписи осей графика");','      if (i.graphAxisLabels != null && typeof i.graphAxisLabels !== "boolean") throw new Error("Повреждены подписи осей графика");\n      if (i.graphGridStep != null && (!finite(i.graphGridStep) || i.graphGridStep <= 0 || i.graphGridStep > 1000)) throw new Error("Повреждён шаг сетки графика");\n      if (i.graphShowCurve != null && typeof i.graphShowCurve !== "boolean") throw new Error("Повреждена видимость функции графика");\n      if (i.graphProjections != null && typeof i.graphProjections !== "boolean") throw new Error("Повреждены проекции точек графика");');
fs.writeFileSync("src/boardModel.ts",m);

let a=fs.readFileSync("src/App.tsx","utf8");
a=a.replace('showLabels:boolean;snap:boolean;axisLabels:boolean;segments:', 'showLabels:boolean;snap:boolean;axisLabels:boolean;gridStep:number;showCurve:boolean;projections:boolean;segments:');
a=a.replace('axisLabels:item.graphAxisLabels!==false,segments:', 'axisLabels:item.graphAxisLabels!==false,gridStep:item.graphGridStep??1,showCurve:item.graphShowCurve!==false,projections:item.graphProjections===true,segments:');
a=a.replace('graphAxisLabels:d.axisLabels,graphSegments:', 'graphAxisLabels:d.axisLabels,graphGridStep:d.gridStep,graphShowCurve:d.showCurve,graphProjections:d.projections,graphSegments:');
a=a.replace('graphAxisLabels:true,graphSegments:', 'graphAxisLabels:true,graphGridStep:1,graphShowCurve:true,graphProjections:false,graphSegments:');
a=a.replace('graphAxisLabels:graphDraft.axisLabels,graphSegments:', 'graphAxisLabels:graphDraft.axisLabels,graphGridStep:graphDraft.gridStep,graphShowCurve:graphDraft.showCurve,graphProjections:graphDraft.projections,graphSegments:');

a=a.replace('  const gridX=Array.from({length:Math.min(21,Math.max(0,Math.floor(xMax-xMin)+1))},(_,i)=>Math.ceil(xMin)+i).filter(v=>v<=xMax);\n  const gridY=Array.from({length:Math.min(21,Math.max(0,Math.floor(yMax-yMin)+1))},(_,i)=>Math.ceil(yMin)+i).filter(v=>v<=yMax);','  const step=Math.max(.1,item.graphGridStep??1);\n  const gridValues=(min:number,max:number)=>{const first=Math.ceil(min/step)*step,count=Math.min(101,Math.max(0,Math.floor((max-first)/step)+1));return Array.from({length:count},(_,i)=>Number((first+i*step).toFixed(6)))};\n  const gridX=gridValues(xMin,xMax),gridY=gridValues(yMin,yMax);');
a=a.replace('if(item.graphSnap!==false){x=Math.round(x);y=Math.round(y)}return {x,y}', 'if(item.graphSnap!==false){const st=Math.max(.1,item.graphGridStep??1);x=Math.round(x/st)*st;y=Math.round(y/st)*st}return {x:Number(x.toFixed(6)),y:Number(y.toFixed(6))}');
a=a.replace('if(item.graphSnap!==false){x=Math.round(x);y=Math.round(y)}onPointMove(i,x,y)', 'if(item.graphSnap!==false){const st=Math.max(.1,item.graphGridStep??1);x=Math.round(x/st)*st;y=Math.round(y/st)*st}onPointMove(i,Number(x.toFixed(6)),Number(y.toFixed(6)))');
a=a.replace('<path className="graph-curve" d={path}/>','{item.graphShowCurve!==false&&<path className="graph-curve" d={path}/>}');
a=a.replace('<g className="graph-geometry">{(item.graphSegments??[])','{item.graphProjections===true&&<g className="graph-projections">{gp.map((p,i)=><g key={"proj"+i}>{xMin<=0&&xMax>=0&&<line x1={sx(p.x)} x2={sx(0)} y1={sy(p.y)} y2={sy(p.y)}/>} {yMin<=0&&yMax>=0&&<line x1={sx(p.x)} x2={sx(p.x)} y1={sy(p.y)} y2={sy(0)}/>}</g>)}</g>}<g className="graph-geometry">{(item.graphSegments??[])');

const axisToggle='<label className="graph-grid-toggle"><input type="checkbox" checked={graphDraft.axisLabels} onChange={e=>setGraphDraft({...graphDraft,axisLabels:e.target.checked})}/> Числа на осях</label>';
a=a.replace(axisToggle,axisToggle+'<label><span>Шаг сетки</span><select value={graphDraft.gridStep} onChange={e=>setGraphDraft({...graphDraft,gridStep:Number(e.target.value)})}><option value={0.5}>0,5</option><option value={1}>1</option><option value={2}>2</option><option value={5}>5</option><option value={10}>10</option></select></label><label className="graph-grid-toggle"><input type="checkbox" checked={graphDraft.showCurve} onChange={e=>setGraphDraft({...graphDraft,showCurve:e.target.checked})}/> Показывать график функции</label><label className="graph-grid-toggle"><input type="checkbox" checked={graphDraft.projections} onChange={e=>setGraphDraft({...graphDraft,projections:e.target.checked})}/> Проекции точек на оси</label><div className="graph-quick-actions"><button type="button" onClick={()=>setGraphDraft({...graphDraft,xMin:-10,xMax:10,yMin:-10,yMax:10})}>Центр -10...10</button><button type="button" disabled={!graphDraft.points.length} onClick={()=>{if(!graphDraft.points.length)return;const xs=graphDraft.points.map(p=>p.x),ys=graphDraft.points.map(p=>p.y),pad=2;setGraphDraft({...graphDraft,xMin:Math.floor(Math.min(...xs)-pad),xMax:Math.ceil(Math.max(...xs)+pad),yMin:Math.floor(Math.min(...ys)-pad),yMax:Math.ceil(Math.max(...ys)+pad)})}}>Вместить точки</button></div>');

const typeLabel='<label><span>Тип функции</span><select value={graphDraft.type}';
a=a.replace(typeLabel,'<div className="graph-presets"><button type="button" onClick={()=>setGraphDraft({...graphDraft,type:"linear",a:1,b:0,c:0})}>y=x</button><button type="button" onClick={()=>setGraphDraft({...graphDraft,type:"quadratic",a:1,b:0,c:0})}>y=x²</button><button type="button" onClick={()=>setGraphDraft({...graphDraft,type:"sin",a:1,b:1,c:0})}>sin x</button><button type="button" onClick={()=>setGraphDraft({...graphDraft,type:"cos",a:1,b:1,c:0})}>cos x</button></div>'+typeLabel);

a=a.replace('className={`table-cell ${header && index < cols ? "table-cell-header" : ""}`}','className={`table-cell ${header && index < cols ? "table-cell-header" : ""} ${item.tableStripe && Math.floor(index / cols) % 2 === 1 ? "table-cell-striped" : ""}`}');
fs.writeFileSync("src/App.tsx",a);

let c=fs.readFileSync("src/App.css","utf8");
c=c.replace('.table-view.table-striped .table-cell:nth-child(6n+4),.table-view.table-striped .table-cell:nth-child(6n+5),.table-view.table-striped .table-cell:nth-child(6n+6){background:rgba(91,93,196,.045)}','.table-view.table-striped .table-cell-striped{background:rgba(91,93,196,.045)}');
if(!c.includes("/* v60 · math finish */"))c+='\n/* v60 · math finish */\n.graph-projections line{stroke:#9da0ad;stroke-width:1.2;stroke-dasharray:5 4;vector-effect:non-scaling-stroke}.graph-presets,.graph-quick-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}.graph-presets{grid-template-columns:repeat(4,minmax(0,1fr))}.graph-presets button,.graph-quick-actions button{border:1px solid #dfe0e7;background:#fff;border-radius:7px;padding:6px 5px;cursor:pointer;font-size:11px}.graph-presets button:hover,.graph-quick-actions button:hover{border-color:#b9baf0;background:#f5f5ff}.graph-quick-actions button:disabled{opacity:.45;cursor:default}\n';
fs.writeFileSync("src/App.css",c);
console.log("v60 установлен. Запустите npm run build");
