import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import type { AuthUser } from "./authStore";
import { deleteDirectMessage,editDirectMessage,ensureDirectChat,getDirectChatReadState,listDirectChatContacts,listDirectChats,listDirectMessages,markDirectChatRead,sendDirectMessage,type DirectChatContact,type DirectChatConversation,type DirectChatMessage } from "./directChatStore";
import { subscribeDirectChat } from "./directChatRealtime";

type Props={user:AuthUser;onBack:()=>void};
const time=(iso:string|null)=>iso?new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(iso)):"";
const clock=(iso:string)=>new Intl.DateTimeFormat("ru-RU",{hour:"2-digit",minute:"2-digit"}).format(new Date(iso));

export default function ChatScreen({user,onBack}:Props){
 const [chats,setChats]=useState<DirectChatConversation[]>([]),[contacts,setContacts]=useState<DirectChatContact[]>([]),[messages,setMessages]=useState<DirectChatMessage[]>([]);
 const [active,setActive]=useState<string|null>(null),[draft,setDraft]=useState(""),[query,setQuery]=useState(""),[messageQuery,setMessageQuery]=useState(""),[busy,setBusy]=useState(true),[error,setError]=useState("");
 const [editing,setEditing]=useState<string|null>(null),[editDraft,setEditDraft]=useState(""),[otherReadAt,setOtherReadAt]=useState<string|null>(null);
 const bottom=useRef<HTMLDivElement>(null);
 const refreshChats=useCallback(async()=>setChats(await listDirectChats()),[]);
 const refreshMessages=useCallback(async(id:string)=>{const [rows,read]=await Promise.all([listDirectMessages(id),getDirectChatReadState(id)]);setMessages(rows);setOtherReadAt(read.other_last_read_at);await markDirectChatRead(id);await refreshChats()},[refreshChats]);
 useEffect(()=>{let alive=true;Promise.all([listDirectChats(),listDirectChatContacts()]).then(([a,b])=>{if(!alive)return;setChats(a);setContacts(b);setActive(a[0]?.id??null)}).catch(e=>alive&&setError(e instanceof Error?e.message:"Не удалось загрузить чат")).finally(()=>alive&&setBusy(false));return()=>{alive=false}},[]);
 useEffect(()=>{setEditing(null);setMessageQuery("");if(active)void refreshMessages(active).catch(e=>setError(e instanceof Error?e.message:"Не удалось загрузить сообщения"));else setMessages([])},[active,refreshMessages]);
 useEffect(()=>subscribeDirectChat(user.id,()=>{void refreshChats();if(active)void refreshMessages(active)}),[user.id,active,refreshChats,refreshMessages]);
 useEffect(()=>{if(!messageQuery)bottom.current?.scrollIntoView({behavior:"smooth"})},[messages.length,active,messageQuery]);
 const current=chats.find(x=>x.id===active);
 const filtered=useMemo(()=>chats.filter(x=>(x.other_name+" "+(x.last_message||"")).toLowerCase().includes(query.trim().toLowerCase())),[chats,query]);
 const visibleMessages=useMemo(()=>{const q=messageQuery.trim().toLowerCase();return q?messages.filter(m=>m.body.toLowerCase().includes(q)):messages},[messages,messageQuery]);
 const start=async(contact:DirectChatContact)=>{setError("");try{const id=await ensureDirectChat(contact.user_id);await refreshChats();setActive(id)}catch(e){setError(e instanceof Error?e.message:"Не удалось открыть диалог")}};
 const send=async()=>{const body=draft.trim();if(!active||!body)return;setDraft("");try{await sendDirectMessage(active,body);await refreshMessages(active)}catch(e){setDraft(body);setError(e instanceof Error?e.message:"Не удалось отправить сообщение")}};
 const beginEdit=(m:DirectChatMessage)=>{if(m.deleted_at)return;setEditing(m.id);setEditDraft(m.body)};
 const saveEdit=async()=>{if(!editing||!active)return;try{await editDirectMessage(editing,editDraft);setEditing(null);setEditDraft("");await refreshMessages(active)}catch(e){setError(e instanceof Error?e.message:"Не удалось изменить сообщение")}};
 const remove=async(m:DirectChatMessage)=>{if(!active||m.deleted_at||!confirm("Удалить это сообщение?"))return;try{await deleteDirectMessage(m.id);if(editing===m.id)setEditing(null);await refreshMessages(active)}catch(e){setError(e instanceof Error?e.message:"Не удалось удалить сообщение")}};
 const existing=new Set(chats.map(x=>x.other_user_id));
 return <main className="chat-hub-shell"><header className="chat-hub-header"><button onClick={onBack}>← Доски</button><div><strong>Сообщения</strong><span>Личные диалоги преподавателя и ученика</span></div><span className="chat-hub-user">{user.name}</span></header>
 <div className="chat-hub-layout"><aside className={`chat-hub-sidebar ${active?"mobile-hidden":""}`}><div className="chat-hub-search"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск диалогов"/></div>{busy?<div className="chat-hub-empty">Загрузка…</div>:filtered.length?<div className="chat-hub-list">{filtered.map(chat=><button key={chat.id} className={active===chat.id?"active":""} onClick={()=>setActive(chat.id)}><span className="chat-avatar">{chat.other_name.charAt(0).toUpperCase()}</span><span className="chat-list-copy"><b>{chat.other_name}</b><small>{chat.last_message||"Диалог создан"}</small></span><span className="chat-list-side"><small>{time(chat.last_message_at)}</small>{chat.unread_count>0&&<b>{chat.unread_count>99?"99+":chat.unread_count}</b>}</span></button>)}</div>:<div className="chat-hub-empty">Диалогов пока нет</div>}
 {contacts.some(x=>!existing.has(x.user_id))&&<div className="chat-hub-contacts"><strong>Начать диалог</strong>{contacts.filter(x=>!existing.has(x.user_id)).slice(0,20).map(c=><button key={c.user_id} onClick={()=>void start(c)}><span className="chat-avatar">{c.display_name.charAt(0).toUpperCase()}</span><span><b>{c.display_name}</b><small>{c.email||"Участник ваших досок"}</small></span><i>＋</i></button>)}</div>}</aside>
 <section className={`chat-hub-thread ${!active?"mobile-hidden":""}`}>{current?<><div className="chat-thread-head"><button className="chat-mobile-back" onClick={()=>setActive(null)}>←</button><span className="chat-avatar">{current.other_name.charAt(0).toUpperCase()}</span><div><b>{current.other_name}</b><small>{current.other_email||"Участник OnlineRepetitor"}</small></div><input className="chat-message-search" type="search" value={messageQuery} onChange={e=>setMessageQuery(e.target.value)} placeholder="Найти в переписке"/></div><div className="chat-thread-messages">{visibleMessages.length===0&&<div className="chat-hub-empty">{messageQuery?"Ничего не найдено":"Начните переписку. Сообщения сохраняются на сервере."}</div>}{visibleMessages.map(m=><article key={m.id} className={`${m.sender_id===user.id?"mine":"theirs"} ${m.deleted_at?"deleted":""}`}><small>{m.sender_id===user.id?"Вы":m.sender_name}</small>{editing===m.id?<div className="chat-edit-box"><textarea value={editDraft} maxLength={4000} autoFocus onChange={e=>setEditDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Escape")setEditing(null);if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void saveEdit()}}}/><span><button onClick={()=>setEditing(null)}>Отмена</button><button disabled={!editDraft.trim()} onClick={()=>void saveEdit()}>Сохранить</button></span></div>:<div>{m.body}</div>}<footer><time>{clock(m.created_at)}{m.edited_at?" · изменено":""}</time>{m.sender_id===user.id&&!m.deleted_at&&editing!==m.id&&<span className="chat-message-actions"><button onClick={()=>beginEdit(m)}>Изменить</button><button onClick={()=>void remove(m)}>Удалить</button></span>}{m.sender_id===user.id&&!m.deleted_at&&otherReadAt&&Date.parse(otherReadAt)>=Date.parse(m.created_at)&&<i className="chat-read-mark" title="Прочитано">✓✓</i>}</footer></article>)}<div ref={bottom}/></div><div className="chat-thread-compose"><textarea value={draft} maxLength={4000} placeholder="Сообщение…" onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}}/><button disabled={!draft.trim()} onClick={()=>void send()}>Отправить</button></div></>:<div className="chat-thread-placeholder"><span>💬</span><strong>Выберите диалог</strong><p>Переписка доступна независимо от открытой доски.</p></div>}</section></div>{error&&<div className="chat-hub-error" onClick={()=>setError("")}>{error}</div>}</main>;
}
