import { useEffect,useMemo,useState } from "react";
import type { AuthUser } from "./authStore";
import { getUserBoards,type BoardSummary } from "./boardStore";
import { getStudentsForTeacher,type StudentRecord } from "./studentsStore";
import { createAssignment,deleteAssignment,listAssignments,reviewAssignment,submitAssignment,type Assignment } from "./assignmentsStore";

type Props={user:AuthUser;onBack:()=>void;onOpenBoard:(board:BoardSummary)=>void};
const fmt=(iso:string|null)=>iso?new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(iso)):"Без срока";
const dateInput=(d:Date)=>{const p=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};

export default function AssignmentsScreen({user,onBack,onOpenBoard}:Props){
 const [rows,setRows]=useState<Assignment[]>([]),[students,setStudents]=useState<StudentRecord[]>([]),[boards,setBoards]=useState<BoardSummary[]>([]);
 const [loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[filter,setFilter]=useState<"all"|"assigned"|"submitted"|"reviewed">("all");
 const [createOpen,setCreateOpen]=useState(false),[studentId,setStudentId]=useState(""),[boardId,setBoardId]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[due,setDue]=useState(""),[maxScore,setMaxScore]=useState("100");
 const [active,setActive]=useState<Assignment|null>(null),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState(""),[score,setScore]=useState("");
 const load=async()=>{setLoading(true);try{const [a,b,s]=await Promise.all([listAssignments(user.id),getUserBoards(user),getStudentsForTeacher(user).catch(()=>[])]);setRows(a);setBoards(b);setStudents(s)}catch(e){setNotice(e instanceof Error?e.message:"Не удалось загрузить задания")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[user.id]);
 const teacherRows=rows.filter(a=>a.teacherId===user.id);
 const isTeacher=teacherRows.length>0||students.length>0;
 const visible=useMemo(()=>rows.filter(a=>(a.teacherId===user.id||a.studentId===user.id)&&(filter==="all"||a.status===filter)),[rows,filter,user.id]);
 const studentName=(id:string)=>students.find(s=>s.userId===id)?.name||"Ученик";
 const openCreate=()=>{const s=students[0];setStudentId(s?.userId||"");setBoardId(s?.boardIds[0]||"");setTitle("");setDescription("");const d=new Date();d.setDate(d.getDate()+7);d.setHours(20,0,0,0);setDue(dateInput(d));setMaxScore("100");setCreateOpen(true)};
 const save=async()=>{if(!studentId||!title.trim()){setNotice("Выберите ученика и укажите название задания");return}const board=boards.find(b=>b.id===boardId);try{const a=await createAssignment({teacherId:user.id,studentId,boardId,boardTitle:board?.title||"Без доски",title,description,dueAt:due?new Date(due).toISOString():null,maxScore:Math.max(1,Number(maxScore)||100)});setRows(r=>[a,...r]);setCreateOpen(false);setNotice("Задание выдано ученику")}catch{setNotice("Не удалось создать задание")}};
 const openRow=(a:Assignment)=>{setActive(a);setAnswer(a.submissionText);setFeedback(a.feedback);setScore(a.score==null?"":String(a.score))};
 const submit=async()=>{if(!active)return;try{await submitAssignment(active,answer);setActive(null);setNotice("Работа отправлена преподавателю");await load()}catch{setNotice("Не удалось отправить работу")}};
 const review=async()=>{if(!active)return;const n=score.trim()===""?null:Math.min(active.maxScore,Math.max(0,Number(score)));try{await reviewAssignment(active,n,feedback);setActive(null);setNotice("Проверка сохранена");await load()}catch{setNotice("Не удалось сохранить проверку")}};
 const stats={all:visible.length,assigned:rows.filter(a=>a.status==="assigned"&&(a.teacherId===user.id||a.studentId===user.id)).length,submitted:rows.filter(a=>a.status==="submitted"&&(a.teacherId===user.id||a.studentId===user.id)).length,reviewed:rows.filter(a=>a.status==="reviewed"&&(a.teacherId===user.id||a.studentId===user.id)).length};
 return <main className="assignments-shell">
  <header className="students-header"><div><button className="boards-secondary" onClick={onBack}>← Доски</button><div><strong>Задания</strong><span>Выдача, сдача, проверка и результаты</span></div></div>{isTeacher&&<button className="boards-create" onClick={openCreate}>+ Новое задание</button>}</header>
  <section className="assignments-content">
   <nav className="dashboard-nav"><button onClick={onBack}>Доски</button><button onClick={()=>{window.history.pushState({},"","/?section=students");window.dispatchEvent(new PopStateEvent("popstate"))}}>Ученики</button><button className="active">Задания</button><button onClick={()=>{window.history.pushState({},"","/?section=progress");window.dispatchEvent(new PopStateEvent("popstate"))}}>Прогресс</button><button disabled>Расписание</button><button disabled>Материалы</button></nav>
   {notice&&<div className="access-notice">{notice}</div>}
   <div className="assignment-stats"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}><b>{rows.filter(a=>a.teacherId===user.id||a.studentId===user.id).length}</b><span>Все</span></button><button className={filter==="assigned"?"active":""} onClick={()=>setFilter("assigned")}><b>{stats.assigned}</b><span>Ожидают</span></button><button className={filter==="submitted"?"active":""} onClick={()=>setFilter("submitted")}><b>{stats.submitted}</b><span>На проверке</span></button><button className={filter==="reviewed"?"active":""} onClick={()=>setFilter("reviewed")}><b>{stats.reviewed}</b><span>Проверены</span></button></div>
   {loading?<div className="boards-empty"><strong>Загружаем задания…</strong></div>:visible.length===0?<div className="boards-empty"><strong>Здесь пока пусто</strong><span>{isTeacher?"Создайте первое задание для ученика.":"Новых заданий пока нет."}</span></div>:<div className="assignment-list">{visible.map(a=><article key={a.id} className={`assignment-card status-${a.status}`}><button className="assignment-main" onClick={()=>openRow(a)}><span className="assignment-status">{a.status==="assigned"?"Ожидает выполнения":a.status==="submitted"?"На проверке":"Проверено"}</span><h3>{a.title}</h3><p>{a.description||"Без дополнительного описания"}</p><div><span>{a.teacherId===user.id?studentName(a.studentId):"От преподавателя"}</span><span>{a.boardTitle}</span><span>Срок: {fmt(a.dueAt)}</span>{a.status==="reviewed"&&a.score!=null&&<strong>{a.score}/{a.maxScore}</strong>}</div></button>{a.teacherId===user.id&&<button className="assignment-delete" onClick={async()=>{if(confirm("Удалить задание?")){await deleteAssignment(a.id);setRows(r=>r.filter(x=>x.id!==a.id))}}}>Удалить</button>}</article>)}</div>}
  </section>
  {createOpen&&<div className="access-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setCreateOpen(false)}}><section className="access-modal assignment-modal"><div className="access-head"><div><h2>Новое задание</h2><p>Выдайте работу конкретному ученику.</p></div><button onClick={()=>setCreateOpen(false)}>×</button></div><div className="assignment-form"><label><span>Ученик</span><select value={studentId} onChange={e=>{setStudentId(e.target.value);const st=students.find(s=>s.userId===e.target.value);setBoardId(st?.boardIds[0]||"")}}>{students.map(s=><option key={s.userId} value={s.userId}>{s.name}</option>)}</select></label><label><span>Доска</span><select value={boardId} onChange={e=>setBoardId(e.target.value)}><option value="">Без доски</option>{boards.filter(b=>students.find(s=>s.userId===studentId)?.boardIds.includes(b.id)).map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><label><span>Срок</span><input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><label><span>Макс. балл</span><input type="number" min="1" max="10000" value={maxScore} onChange={e=>setMaxScore(e.target.value)}/></label><label className="wide"><span>Название</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Домашняя работа №4"/></label><label className="wide"><span>Условие / инструкция</span><textarea rows={6} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Что нужно выполнить, какие материалы использовать…"/></label></div><div className="session-actions"><button className="students-primary" onClick={()=>void save()}>Выдать задание</button><button className="boards-secondary" onClick={()=>setCreateOpen(false)}>Отмена</button></div></section></div>}
  {active&&<div className="access-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setActive(null)}}><section className="access-modal assignment-modal"><div className="access-head"><div><h2>{active.title}</h2><p>{active.boardTitle} · срок {fmt(active.dueAt)}</p></div><button onClick={()=>setActive(null)}>×</button></div><div className="assignment-detail"><p>{active.description||"Дополнительных инструкций нет."}</p>{active.boardId&&boards.some(b=>b.id===active.boardId)&&<button className="boards-secondary" onClick={()=>{const b=boards.find(x=>x.id===active.boardId);if(b)onOpenBoard(b)}}>Открыть доску задания</button>}</div>
   {active.studentId===user.id&&active.teacherId!==user.id?<><label className="assignment-answer"><span>Мой ответ / комментарий к работе</span><textarea rows={7} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Опишите выполненную работу, приложите пояснение или ссылку…"/></label>{active.status==="reviewed"&&<div className="assignment-feedback"><b>Результат: {active.score??"—"}/{active.maxScore}</b><p>{active.feedback||"Комментарий преподавателя не указан."}</p></div>}<div className="session-actions"><button className="students-primary" onClick={()=>void submit()}>{active.submittedAt?"Отправить повторно":"Сдать работу"}</button></div></>:<>{active.submittedAt?<><label className="assignment-answer"><span>Ответ ученика</span><textarea rows={6} readOnly value={active.submissionText}/></label><div className="assignment-review-grid"><label><span>Балл из {active.maxScore}</span><input type="number" min="0" max={active.maxScore} value={score} onChange={e=>setScore(e.target.value)}/></label><label><span>Комментарий преподавателя</span><textarea rows={4} value={feedback} onChange={e=>setFeedback(e.target.value)}/></label></div><button className="students-primary" onClick={()=>void review()}>Сохранить проверку</button></>:<div className="student-history-empty">Ученик ещё не сдал работу.</div>}</>}
  </section></div>}
 </main>
}
