import { useEffect, useMemo, useState } from "react";
import { BOARD_ROLE_LABELS, isRemoteBackendEnabled, type AuthUser, type BoardRole } from "./authStore";
import { createBoard, deleteBoard, ensureUserBoards, getUserBoards, renameBoard, inviteToBoard, getBoardAccess, changeMemberRole, removeMember, revokeInvitation, type BoardAccessMember, type BoardInvitation, type BoardSummary } from "./boardStore";

type Props={user:AuthUser;onOpenBoard:(b:BoardSummary)=>void;onLogout:()=>void};
const fmt=(iso:string)=>new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(iso));

export default function BoardsScreen({user,onOpenBoard,onLogout}:Props){
 const [boards,setBoards]=useState<BoardSummary[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [editingId,setEditingId]=useState<string|null>(null); const [draftTitle,setDraftTitle]=useState("");
 const [manage,setManage]=useState<BoardSummary|null>(null); const [email,setEmail]=useState(""); const [role,setRole]=useState<Exclude<BoardRole,"owner">>("editor"); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
 const [access,setAccess]=useState<{members:BoardAccessMember[];invites:BoardInvitation[]}>({members:[],invites:[]});
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?boards.filter(b=>b.title.toLowerCase().includes(q)):boards},[boards,query]);
 const refresh=async()=>setBoards(await getUserBoards(user));
 const loadAccess=async(board=manage)=>{if(!board)return;setAccess(await getBoardAccess(user.id,board.id))};
 useEffect(()=>{let alive=true;(async()=>{try{const list=await ensureUserBoards(user);if(alive)setBoards(list)}catch(e){if(alive)setNotice(e instanceof Error?e.message:"Не удалось загрузить доски")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[user.id]);
 useEffect(()=>{if(manage)void loadAccess(manage);else setAccess({members:[],invites:[]})},[manage?.id]);
 const add=async()=>{if(busy)return;setBusy(true);try{const b=await createBoard(user);await refresh();onOpenBoard(b)}catch(e){setNotice(e instanceof Error?e.message:"Не удалось создать доску")}finally{setBusy(false)}};
 const saveRename=async(b:BoardSummary)=>{await renameBoard(user.id,b.id,draftTitle);setEditingId(null);await refresh()};
 const sendInvite=async()=>{if(!manage||busy)return;setBusy(true);try{const kind=await inviteToBoard(user.id,manage.id,email,role);setEmail("");setNotice(kind==="member"?"Пользователь добавлен на доску":"Приглашение сохранено. Оно появится у пользователя после входа с этим email.");await loadAccess(manage)}catch(e){setNotice(e instanceof Error?e.message:"Не удалось пригласить")}finally{setBusy(false)}};
 return <main className="boards-shell"><header className="boards-header"><div className="boards-brand"><div className="auth-logo">B</div><div><strong>Учебная доска</strong><span>{isRemoteBackendEnabled()?"Серверная синхронизация включена":"Локальный режим"}</span></div></div><div className="boards-account"><div className="account-chip"><span className="account-avatar">{user.name.charAt(0).toUpperCase()}</span><span className="account-copy"><strong>{user.name}</strong><small>{user.email}</small></span></div><button className="boards-secondary" onClick={onLogout}>Выйти</button></div></header>
 <section className="boards-content"><div className="boards-heading-row"><div><h1>Мои доски</h1><p>{isRemoteBackendEnabled()?"Доски и доступы синхронизируются через сервер.":"Сейчас данные хранятся в этом браузере. Сервер можно подключить позже."}</p></div><button className="boards-create" disabled={busy} onClick={()=>void add()}>+ Новая доска</button></div><div className="boards-toolbar"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по названию доски"/><span>{loading?"Загрузка…":`${boards.length} досок`}</span></div>
 {notice&&<div className="access-notice" style={{marginBottom:12}}>{notice}</div>}
 <div className="boards-grid">{visible.map(b=><article className="board-card" key={b.id}><button className="board-card-preview" onClick={()=>onOpenBoard(b)}><span className="board-card-grid"/><span className="board-card-letter">B</span></button><div className="board-card-body">{editingId===b.id?<input className="board-card-rename" value={draftTitle} onChange={e=>setDraftTitle(e.target.value)} onBlur={()=>void saveRename(b)} onKeyDown={e=>{if(e.key==="Enter")void saveRename(b);if(e.key==="Escape")setEditingId(null)}} autoFocus/>:<button className="board-card-title" onClick={()=>onOpenBoard(b)}>{b.title}</button>}<div className="board-card-meta"><span>{BOARD_ROLE_LABELS[b.role]}</span><span>Изменено {fmt(b.updatedAt)}</span></div><div className="board-card-actions">{b.role==="owner"&&<><button onClick={()=>{setEditingId(b.id);setDraftTitle(b.title)}}>Переименовать</button><button onClick={()=>{setManage(b);setNotice("")}}>Участники</button><button className="danger" onClick={async()=>{if(confirm(`Удалить доску «${b.title}»?`)){await deleteBoard(user.id,b.id);await refresh()}}}>Удалить</button></>} {b.role!=="owner"&&<button onClick={()=>onOpenBoard(b)}>Открыть</button>}</div></div></article>)}</div></section>
 {manage&&<div className="access-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setManage(null)}}><section className="access-modal"><div className="access-head"><div><h2>Участники</h2><p>{manage.title}</p></div><button onClick={()=>setManage(null)}>×</button></div><div className="invite-row"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email пользователя"/><select value={role} onChange={e=>setRole(e.target.value as Exclude<BoardRole,"owner">)}><option value="editor">Редактор</option><option value="viewer">Только просмотр</option></select><button disabled={busy} onClick={()=>void sendInvite()}>{busy?"Подождите…":"Пригласить"}</button></div>{notice&&<div className="access-notice">{notice}</div>}<div className="access-list"><div className="access-person"><div><strong>{user.name}</strong><span>{user.email}</span></div><b>Владелец</b></div>{access.members.map(m=><div className="access-person" key={m.userId}><div><strong>{m.user?.name||"Пользователь"}</strong><span>{m.user?.email||m.userId}</span></div><select value={m.role} onChange={async e=>{await changeMemberRole(user.id,manage.id,m.userId,e.target.value as Exclude<BoardRole,"owner">);await loadAccess(manage)}}><option value="editor">Редактор</option><option value="viewer">Просмотр</option></select><button className="danger" onClick={async()=>{await removeMember(user.id,manage.id,m.userId);await loadAccess(manage)}}>Удалить</button></div>)}{access.invites.map(i=><div className="access-person pending" key={i.id}><div><strong>{i.email}</strong><span>Ожидает входа</span></div><b>{BOARD_ROLE_LABELS[i.role]}</b><button onClick={async()=>{await revokeInvitation(user.id,manage.id,i.id);await loadAccess(manage)}}>Отменить</button></div>)}</div></section></div>}
 </main>}
