import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { listRecentBoardCallSignals,sendBoardCallSignal,type BoardCallSignal } from "./boardCallStore";
import { subscribeBoardCallSignals } from "./boardCallRealtime";

export type BoardCallParticipant={userId:string;name:string};
type Props={boardId:string;userId:string;participants:BoardCallParticipant[]};
type CallState="idle"|"incoming"|"calling"|"connecting"|"connected";

export default function BoardVideoCallPanel({boardId,userId,participants}:Props){
 const [state,setState]=useState<CallState>("idle"),[open,setOpen]=useState(false),[chooser,setChooser]=useState(false),[targetId,setTargetId]=useState<string|null>(null),[incomingId,setIncomingId]=useState<string|null>(null),[muted,setMuted]=useState(false),[cameraOff,setCameraOff]=useState(false),[error,setError]=useState("");
 const stateRef=useRef<CallState>("idle"),localVideo=useRef<HTMLVideoElement>(null),remoteVideo=useRef<HTMLVideoElement>(null),pc=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null),pendingOffer=useRef<RTCSessionDescriptionInit|null>(null),candidateQueue=useRef<RTCIceCandidateInit[]>([]),seen=useRef(new Set<string>());
 const setCallState=(next:CallState)=>{stateRef.current=next;setState(next)};
 const peerId=incomingId||targetId; const peerName=useMemo(()=>participants.find(p=>p.userId===peerId)?.name||"Участник доски",[participants,peerId]);
 const stopMedia=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(localVideo.current)localVideo.current.srcObject=null;if(remoteVideo.current)remoteVideo.current.srcObject=null};
 const closePeer=()=>{pc.current?.close();pc.current=null;candidateQueue.current=[]};
 const reset=useCallback(()=>{closePeer();stopMedia();pendingOffer.current=null;setCallState("idle");setOpen(false);setChooser(false);setTargetId(null);setIncomingId(null);setMuted(false);setCameraOff(false)},[]);
 const media=async()=>{if(stream.current)return stream.current;if(!navigator.mediaDevices?.getUserMedia)throw new Error("Браузер не поддерживает камеру и микрофон");const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});stream.current=s;if(localVideo.current)localVideo.current.srcObject=s;return s};
 const createPeer=async(otherId:string)=>{const s=await media();const peer=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});pc.current=peer;s.getTracks().forEach(track=>peer.addTrack(track,s));peer.ontrack=e=>{if(remoteVideo.current)remoteVideo.current.srcObject=e.streams[0]};peer.onicecandidate=e=>{if(e.candidate)void sendBoardCallSignal(boardId,otherId,"candidate",e.candidate.toJSON()).catch(()=>{})};peer.onconnectionstatechange=()=>{if(peer.connectionState==="connected")setCallState("connected");if(["failed","closed"].includes(peer.connectionState)){if(peer.connectionState==="failed")setError("Не удалось установить прямое соединение");reset()}};return peer};
 const flushCandidates=async()=>{if(!pc.current?.remoteDescription)return;for(const c of candidateQueue.current.splice(0)){try{await pc.current.addIceCandidate(c)}catch{}}};
 const handleSignal=useCallback(async(signal:BoardCallSignal)=>{if(signal.board_id!==boardId||signal.receiver_id!==userId||seen.current.has(signal.id))return;seen.current.add(signal.id);try{if(signal.kind==="offer"){pendingOffer.current=signal.payload as RTCSessionDescriptionInit;setIncomingId(signal.sender_id);if(stateRef.current==="idle"){setCallState("incoming");setOpen(true)}}else if(signal.kind==="answer"&&pc.current&&signal.sender_id===targetId){await pc.current.setRemoteDescription(signal.payload as RTCSessionDescriptionInit);await flushCandidates();setCallState("connecting")}else if(signal.kind==="candidate"&&signal.sender_id===peerId){const c=signal.payload as RTCIceCandidateInit;if(pc.current?.remoteDescription)await pc.current.addIceCandidate(c);else candidateQueue.current.push(c)}else if(signal.kind==="hangup"&&signal.sender_id===peerId){setError("Звонок завершён");reset()}}catch(e){setError(e instanceof Error?e.message:"Ошибка видеозвонка")}},[boardId,userId,targetId,peerId,reset]);
 useEffect(()=>{const since=new Date(Date.now()-15000).toISOString();const off=subscribeBoardCallSignals(userId,s=>void handleSignal(s));void listRecentBoardCallSignals(boardId,since).then(rows=>rows.forEach(s=>void handleSignal(s))).catch(()=>{});return()=>{off();closePeer();stopMedia()}},[boardId,userId,handleSignal]);
 const call=async(otherId:string)=>{setError("");setChooser(false);setTargetId(otherId);setOpen(true);setCallState("calling");try{const peer=await createPeer(otherId);const offer=await peer.createOffer();await peer.setLocalDescription(offer);await sendBoardCallSignal(boardId,otherId,"offer",offer)}catch(e){setError(e instanceof Error?e.message:"Не удалось начать звонок");reset()}};
 const accept=async()=>{const offer=pendingOffer.current,otherId=incomingId;if(!offer||!otherId)return;setError("");setCallState("connecting");try{const peer=await createPeer(otherId);await peer.setRemoteDescription(offer);await flushCandidates();const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await sendBoardCallSignal(boardId,otherId,"answer",answer)}catch(e){setError(e instanceof Error?e.message:"Не удалось принять звонок");reset()}};
 const hangup=async()=>{const otherId=peerId;try{if(otherId)await sendBoardCallSignal(boardId,otherId,"hangup",{})}catch{}reset()};
 const toggleMute=()=>{const next=!muted;stream.current?.getAudioTracks().forEach(t=>t.enabled=!next);setMuted(next)};const toggleCamera=()=>{const next=!cameraOff;stream.current?.getVideoTracks().forEach(t=>t.enabled=!next);setCameraOff(next)};
 const others=participants.filter(p=>p.userId!==userId);
 return <div className="board-call-control"><button className="top-button board-call-button" disabled={state!=="idle"||others.length===0} onClick={()=>others.length===1?void call(others[0].userId):setChooser(v=>!v)} title={others.length?"Видеозвонок участнику этой доски":"Для звонка нужен ещё один участник на доске"} aria-label="Видеозвонок">📹<span>Звонок</span></button>{chooser&&state==="idle"&&<div className="board-call-chooser"><strong>Позвонить</strong>{others.map(p=><button key={p.userId} onClick={()=>void call(p.userId)}><span>{p.name.trim().charAt(0).toUpperCase()||"U"}</span><b>{p.name}</b></button>)}</div>}{open&&<div className="video-call-backdrop"><section className="video-call-card"><header><div><strong>{state==="incoming"?`${peerName} звонит`:state==="connected"?`Разговор с ${peerName}`:`Соединяем с ${peerName}`}</strong><span>Видеозвонок работает только пока вы на этой доске</span></div></header><div className="video-call-stage"><video ref={remoteVideo} autoPlay playsInline className="video-call-remote"/><video ref={localVideo} autoPlay muted playsInline className="video-call-local"/><div className="video-call-placeholder">{state==="incoming"?"📞":state==="connected"?"":"Подключаем видео…"}</div></div>{error&&<div className="video-call-error">{error}</div>}<footer>{state==="incoming"?<><button className="video-call-decline" onClick={()=>void hangup()}>Отклонить</button><button className="video-call-accept" onClick={()=>void accept()}>Принять</button></>:<><button onClick={toggleMute}>{muted?"🔇 Включить микрофон":"🎙 Микрофон"}</button><button onClick={toggleCamera}>{cameraOff?"📷 Включить камеру":"📹 Камера"}</button><button className="video-call-decline" onClick={()=>void hangup()}>Завершить</button></>}</footer></section></div>}</div>;
}
