import { useCallback,useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent } from "react";
import { listRecentBoardCallSignals,sendBoardCallSignal,type BoardCallSignal } from "./boardCallStore";
import { subscribeBoardCallSignals } from "./boardCallRealtime";
import { getBoardCallIceConfig,hasTurnServer,type BoardCallIceMode } from "./webrtcConfig";

export type BoardCallParticipant={userId:string;name:string};
type Props={boardId:string;userId:string;participants:BoardCallParticipant[]};
type CallState="idle"|"incoming"|"calling"|"connecting"|"connected";
type Position={x:number;y:number};

export default function BoardVideoCallPanel({boardId,userId,participants}:Props){
 const [state,setState]=useState<CallState>("idle"),[open,setOpen]=useState(false),[chooser,setChooser]=useState(false),[targetId,setTargetId]=useState<string|null>(null),[incomingId,setIncomingId]=useState<string|null>(null),[muted,setMuted]=useState(false),[cameraOff,setCameraOff]=useState(false),[sharingScreen,setSharingScreen]=useState(false),[minimized,setMinimized]=useState(false),[error,setError]=useState("");
 const [position,setPosition]=useState<Position|null>(null),[iceMode,setIceMode]=useState<BoardCallIceMode|null>(null);
 const stateRef=useRef<CallState>("idle"),localVideo=useRef<HTMLVideoElement>(null),remoteVideo=useRef<HTMLVideoElement>(null),pc=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null),cameraTrack=useRef<MediaStreamTrack|null>(null),screenTrack=useRef<MediaStreamTrack|null>(null),disconnectTimer=useRef<number|null>(null),pendingOffer=useRef<RTCSessionDescriptionInit|null>(null),candidateQueue=useRef<RTCIceCandidateInit[]>([]),seen=useRef(new Set<string>()),drag=useRef<{dx:number;dy:number}|null>(null);
 const setCallState=(next:CallState)=>{stateRef.current=next;setState(next)};
 const peerId=incomingId||targetId;
 const peerName=useMemo(()=>participants.find(p=>p.userId===peerId)?.name||"Участник доски",[participants,peerId]);
 const activeCall=state!=="idle";
 const stopScreen=useCallback(async()=>{const peer=pc.current,original=cameraTrack.current;screenTrack.current?.stop();screenTrack.current=null;setSharingScreen(false);if(peer&&original){const sender=peer.getSenders().find(s=>s.track?.kind==="video");if(sender)try{await sender.replaceTrack(original)}catch{} }if(stream.current&&original&&!stream.current.getVideoTracks().includes(original)){stream.current.getVideoTracks().forEach(t=>stream.current?.removeTrack(t));stream.current.addTrack(original)}if(localVideo.current&&stream.current)localVideo.current.srcObject=stream.current},[]);
 const stopMedia=()=>{screenTrack.current?.stop();screenTrack.current=null;cameraTrack.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(localVideo.current)localVideo.current.srcObject=null;if(remoteVideo.current)remoteVideo.current.srcObject=null};
 const clearDisconnectTimer=()=>{if(disconnectTimer.current!==null){window.clearTimeout(disconnectTimer.current);disconnectTimer.current=null}};
 const closePeer=()=>{clearDisconnectTimer();pc.current?.close();pc.current=null;candidateQueue.current=[]};
 const reset=useCallback(()=>{closePeer();stopMedia();pendingOffer.current=null;setCallState("idle");setOpen(false);setChooser(false);setTargetId(null);setIncomingId(null);setMuted(false);setCameraOff(false);setSharingScreen(false);setMinimized(false);setPosition(null);setIceMode(null);drag.current=null},[]);
 const media=async()=>{if(stream.current)return stream.current;if(!navigator.mediaDevices?.getUserMedia)throw new Error("Браузер не поддерживает камеру и микрофон");const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});stream.current=s;cameraTrack.current=s.getVideoTracks()[0]??null;if(localVideo.current)localVideo.current.srcObject=s;return s};
 const createPeer=async(otherId:string)=>{const s=await media();const iceConfig=await getBoardCallIceConfig();setIceMode(iceConfig.mode);const peer=new RTCPeerConnection({iceServers:iceConfig.iceServers,iceCandidatePoolSize:4});pc.current=peer;s.getTracks().forEach(track=>peer.addTrack(track,s));peer.ontrack=e=>{if(remoteVideo.current)remoteVideo.current.srcObject=e.streams[0]};peer.onicecandidate=e=>{if(e.candidate)void sendBoardCallSignal(boardId,otherId,"candidate",e.candidate.toJSON()).catch(()=>{})};peer.onconnectionstatechange=()=>{
  const connectionState=peer.connectionState;
  if(connectionState==="connected"){clearDisconnectTimer();setError("");setCallState("connected");return}
  if(connectionState==="disconnected"){
   clearDisconnectTimer();
   disconnectTimer.current=window.setTimeout(()=>{
    if(pc.current===peer&&peer.connectionState==="disconnected"){setError("Связь прервалась. Пытаемся восстановить звонок…");void peer.restartIce()}
   },3000);
   return;
  }
  if(connectionState==="failed"){
   clearDisconnectTimer();
   void hasTurnServer().then(hasTurn=>setError(hasTurn?"Соединение потеряно. Повторите звонок.":"Соединение потеряно. TURN-сервер пока недоступен."));
   reset();
  }
 };return peer};
 const flushCandidates=async()=>{if(!pc.current?.remoteDescription)return;for(const c of candidateQueue.current.splice(0)){try{await pc.current.addIceCandidate(c)}catch{}}};
 const handleSignal=useCallback(async(signal:BoardCallSignal)=>{if(signal.board_id!==boardId||signal.receiver_id!==userId||seen.current.has(signal.id))return;seen.current.add(signal.id);try{if(signal.kind==="offer"){if(stateRef.current!=="idle"&&signal.sender_id!==peerId){void sendBoardCallSignal(boardId,signal.sender_id,"hangup",{});return}pendingOffer.current=signal.payload as RTCSessionDescriptionInit;setIncomingId(signal.sender_id);if(stateRef.current==="idle"){setCallState("incoming");setOpen(true)}}else if(signal.kind==="answer"&&pc.current&&signal.sender_id===targetId){await pc.current.setRemoteDescription(signal.payload as RTCSessionDescriptionInit);await flushCandidates();setCallState("connecting")}else if(signal.kind==="candidate"&&signal.sender_id===peerId){const c=signal.payload as RTCIceCandidateInit;if(pc.current?.remoteDescription)await pc.current.addIceCandidate(c);else candidateQueue.current.push(c)}else if(signal.kind==="hangup"&&signal.sender_id===peerId){setError("Звонок завершён");reset()}}catch(e){setError(e instanceof Error?e.message:"Ошибка видеозвонка")}},[boardId,userId,targetId,peerId,reset]);
 useEffect(()=>{const since=new Date(Date.now()-15000).toISOString();const off=subscribeBoardCallSignals(userId,s=>void handleSignal(s));void listRecentBoardCallSignals(boardId,since).then(rows=>rows.forEach(s=>void handleSignal(s))).catch(()=>{});return()=>{off();closePeer();stopMedia()}},[boardId,userId,handleSignal]);
 const call=async(otherId:string)=>{setError("");setChooser(false);setTargetId(otherId);setOpen(true);setMinimized(false);setCallState("calling");try{const peer=await createPeer(otherId);const offer=await peer.createOffer();await peer.setLocalDescription(offer);await sendBoardCallSignal(boardId,otherId,"offer",offer)}catch(e){setError(e instanceof Error?e.message:"Не удалось начать звонок");reset()}};
 const accept=async()=>{const offer=pendingOffer.current,otherId=incomingId;if(!offer||!otherId)return;setError("");setCallState("connecting");try{const peer=await createPeer(otherId);await peer.setRemoteDescription(offer);await flushCandidates();const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await sendBoardCallSignal(boardId,otherId,"answer",answer)}catch(e){setError(e instanceof Error?e.message:"Не удалось принять звонок");reset()}};
 const hangup=async()=>{const otherId=peerId;try{if(otherId)await sendBoardCallSignal(boardId,otherId,"hangup",{})}catch{}reset()};
 const toggleMute=()=>{const next=!muted;stream.current?.getAudioTracks().forEach(t=>t.enabled=!next);setMuted(next)};
 const toggleCamera=()=>{const next=!cameraOff;cameraTrack.current&&(cameraTrack.current.enabled=!next);setCameraOff(next)};
 const shareScreen=async()=>{if(sharingScreen){await stopScreen();return}if(!navigator.mediaDevices?.getDisplayMedia){setError("Демонстрация экрана не поддерживается этим браузером");return}try{const display=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const track=display.getVideoTracks()[0];if(!track)return;const sender=pc.current?.getSenders().find(s=>s.track?.kind==="video");if(sender)await sender.replaceTrack(track);screenTrack.current=track;setSharingScreen(true);const preview=new MediaStream([track,...(stream.current?.getAudioTracks()??[])]);if(localVideo.current)localVideo.current.srcObject=preview;track.onended=()=>void stopScreen()}catch(e){if((e as DOMException)?.name!=="NotAllowedError")setError(e instanceof Error?e.message:"Не удалось начать демонстрацию экрана")}};
 const startDrag=(e:ReactPointerEvent<HTMLElement>)=>{if(e.button!==0||window.matchMedia("(max-width: 700px)").matches)return;const card=e.currentTarget.closest(".video-call-card") as HTMLElement|null;if(!card)return;const rect=card.getBoundingClientRect();drag.current={dx:e.clientX-rect.left,dy:e.clientY-rect.top};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);setPosition({x:rect.left,y:rect.top})};
 const moveDrag=(e:ReactPointerEvent<HTMLElement>)=>{if(!drag.current)return;const w=minimized?280:Math.min(560,window.innerWidth-24),h=minimized?72:Math.min(520,window.innerHeight-24);setPosition({x:Math.max(8,Math.min(window.innerWidth-w-8,e.clientX-drag.current.dx)),y:Math.max(8,Math.min(window.innerHeight-h-8,e.clientY-drag.current.dy))})};
 const endDrag=()=>{drag.current=null};
 const others=participants.filter(p=>p.userId!==userId);
 const style=position?{left:position.x,top:position.y,right:"auto",bottom:"auto"}:undefined;
 return <div className="board-call-control"><button className={`top-button board-call-button ${activeCall?"active":""}`} disabled={state!=="idle"||others.length===0} onClick={()=>others.length===1?void call(others[0].userId):setChooser(v=>!v)} title={others.length?"Видеозвонок участнику этой доски":"Для звонка нужен ещё один участник на доске"} aria-label="Видеозвонок">📹<span>{activeCall?"В звонке":"Звонок"}</span></button>{chooser&&state==="idle"&&<div className="board-call-chooser"><strong>Позвонить</strong>{others.map(p=><button key={p.userId} onClick={()=>void call(p.userId)}><span>{p.name.trim().charAt(0).toUpperCase()||"U"}</span><b>{p.name}</b></button>)}</div>}{open&&<div className="video-call-layer"><section className={`video-call-card ${minimized?"minimized":""}`} style={style}><header className="video-call-drag-handle" onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}><div><strong>{state==="incoming"?`${peerName} звонит`:state==="connected"?peerName:`Соединяем с ${peerName}`}</strong><span>{state==="incoming"?"Входящий звонок на этой доске":state==="connected"?"Звонок на доске":"Устанавливаем соединение…"}</span></div>{state!=="incoming"&&<button className="video-call-minimize" type="button" onPointerDown={e=>e.stopPropagation()} onClick={()=>setMinimized(v=>!v)} title={minimized?"Развернуть":"Свернуть"}>{minimized?"▣":"−"}</button>}</header>{!minimized&&<><div className="video-call-stage"><video ref={remoteVideo} autoPlay playsInline className="video-call-remote"/><video ref={localVideo} autoPlay muted playsInline className="video-call-local"/><div className="video-call-placeholder">{state==="incoming"?"📞":state==="connected"?"":"Подключаем видео…"}</div>{sharingScreen&&<span className="video-call-sharing-badge">Демонстрация экрана</span>}{iceMode&&<span className="video-call-sharing-badge" title={iceMode==="turn"?"TURN настроен и доступен клиенту":"TURN не получен, используется прямое ICE-соединение"}>{iceMode==="turn"?"TURN":"Прямое соединение"}</span>}</div>{error&&<div className="video-call-error">{error}</div>}<footer>{state==="incoming"?<><button className="video-call-decline" onClick={()=>void hangup()}>Отклонить</button><button className="video-call-accept" onClick={()=>void accept()}>Принять</button></>:<><button className={muted?"active":""} onClick={toggleMute}>{muted?"🔇 Включить":"🎙 Микрофон"}</button><button className={cameraOff?"active":""} onClick={toggleCamera}>{cameraOff?"📷 Включить":"📹 Камера"}</button>{state==="connected"&&<button className={sharingScreen?"active":""} onClick={()=>void shareScreen()}>{sharingScreen?"⏹ Стоп экран":"🖥 Экран"}</button>}<button className="video-call-decline" onClick={()=>void hangup()}>Завершить</button></>}</footer></>}</section></div>}</div>;
}
