import { useEffect,useMemo,useRef,useState } from "react";
import type { AuthUser } from "./authStore";
import { deleteMaterial,downloadMaterial,listMaterials,renameMaterial,uploadMaterial,type Material } from "./materialsStore";
type Props={user:AuthUser;onBack:()=>void};
const size=(n:number)=>n<1024?`${n} Б`:n<1048576?`${Math.round(n/1024)} КБ`:`${Math.round(n/104857.6)/10} МБ`;
const icon=(m:string)=>m==="application/pdf"?"PDF":m.startsWith("image/")?"IMG":m.startsWith("video/")?"VID":m.startsWith("audio/")?"AUD":"FILE";
export default function MaterialsScreen({user,onBack}:Props){
 const [rows,setRows]=useState<Material[]>([]),[query,setQuery]=useState(""),[folder,setFolder]=useState("all"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[edit,setEdit]=useState<Material|null>(null),[editTitle,setEditTitle]=useState(""),[editFolder,setEditFolder]=useState("");const input=useRef<HTMLInputElement>(null);
 const load=async()=>{try{setRows(await listMaterials(user.id))}catch(e){setNotice(e instanceof Error?e.message:"Не удалось загрузить материалы")}};useEffect(()=>{void load()},[user.id]);
 const folders=useMemo(()=>[...new Set(rows.map(x=>x.folder).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ru")),[rows]);
 const visible=rows.filter(x=>(folder==="all"||x.folder===folder)&&(!query.trim()||`${x.title} ${x.fileName} ${x.folder}`.toLowerCase().includes(query.toLowerCase())));
 const upload=async(files:FileList|null)=>{if(!files?.length)return;setBusy(true);let ok=0;try{for(const f of Array.from(files)){await uploadMaterial(user.id,f,folder==="all"?"":folder,f.name);ok++}setNotice(`Загружено файлов: ${ok}`);await load()}catch(e){setNotice(e instanceof Error?e.message:"Ошибка загрузки")}finally{setBusy(false);if(input.current)input.current.value=""}};
 return <main className="materials-shell"><header className="students-header"><div><button className="boards-secondary" onClick={onBack}>← Доски</button><div><strong>Материалы</strong><span>Личная библиотека преподавателя</span></div></div><><input ref={input} hidden type="file" multiple onChange={e=>void upload(e.target.files)}/><button className="boards-create" disabled={busy} onClick={()=>input.current?.click()}>{busy?"Загрузка…":"+ Загрузить"}</button></></header><section className="materials-content">
 <nav className="dashboard-nav"><button onClick={onBack}>Доски</button><button onClick={()=>location.href="/?section=students"}>Ученики</button><button onClick={()=>location.href="/?section=assignments"}>Задания</button><button onClick={()=>location.href="/?section=progress"}>Прогресс</button><button onClick={()=>location.href="/?section=schedule"}>Расписание</button><button className="active">Материалы</button></nav>
 {notice&&<div className="access-notice">{notice}</div>}<div className="materials-toolbar"><input type="search" placeholder="Поиск по материалам" value={query} onChange={e=>setQuery(e.target.value)}/><select value={folder} onChange={e=>setFolder(e.target.value)}><option value="all">Все папки</option>{folders.map(x=><option key={x}>{x}</option>)}</select><span>{visible.length} файлов · {size(visible.reduce((n,x)=>n+x.size,0))}</span></div>
 <div className="materials-layout"><aside className="materials-folders"><button className={folder==="all"?"active":""} onClick={()=>setFolder("all")}>Все материалы <b>{rows.length}</b></button>{folders.map(f=><button className={folder===f?"active":""} key={f} onClick={()=>setFolder(f)}>{f}<b>{rows.filter(x=>x.folder===f).length}</b></button>)}<button className={folder===""?"active":""} onClick={()=>setFolder("")}>Без папки <b>{rows.filter(x=>!x.folder).length}</b></button></aside>
 <section>{visible.length===0?<div className="boards-empty"><strong>{rows.length?"Ничего не найдено":"Библиотека пока пуста"}</strong><span>Загрузите PDF, изображения, документы, аудио или видео до 50 МБ.</span></div>:<div className="materials-grid">{visible.map(m=><article className="material-card" key={m.id}><div className={`material-icon ${m.mime.startsWith("image/")?"image":""}`}>{icon(m.mime)}</div><div><b title={m.title}>{m.title}</b><span>{m.folder||"Без папки"} · {size(m.size)}</span><small>{m.fileName}</small></div><div className="material-actions"><button onClick={()=>void downloadMaterial(m).catch(e=>setNotice(e.message))}>Скачать</button><button onClick={()=>{setEdit(m);setEditTitle(m.title);setEditFolder(m.folder)}}>Изменить</button><button className="danger" onClick={async()=>{if(confirm(`Удалить «${m.title}»?`)){await deleteMaterial(m.id,m.storagePath);await load()}}}>×</button></div></article>)}</div>}</section></div>
 </section>
 {edit&&<div className="access-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEdit(null)}}><section className="access-modal materials-modal"><div className="access-head"><div><h2>Материал</h2><p>{edit.fileName}</p></div><button onClick={()=>setEdit(null)}>×</button></div><label><span>Название</span><input value={editTitle} onChange={e=>setEditTitle(e.target.value)}/></label><label><span>Папка</span><input value={editFolder} onChange={e=>setEditFolder(e.target.value)} placeholder="Например: Алгебра"/></label><div className="session-actions"><button className="students-primary" onClick={async()=>{await renameMaterial(edit.id,editTitle,editFolder);setEdit(null);await load()}}>Сохранить</button><button className="boards-secondary" onClick={()=>setEdit(null)}>Отмена</button></div></section></div>}
 </main>
}
