import { useEffect,useMemo,useRef,useState,type DragEvent } from "react";
import type { AuthUser } from "./authStore";
import { deleteMaterial,downloadMaterial,listMaterials,materialBlob,renameMaterial,setMaterialFavorite,uploadMaterial,type Material } from "./materialsStore";

type Props={user:AuthUser;onBack:()=>void};
type SortMode="recent"|"name"|"size"|"used";
const size=(n:number)=>n<1024?`${n} Б`:n<1048576?`${Math.round(n/1024)} КБ`:`${Math.round(n/104857.6)/10} МБ`;
const icon=(m:string)=>m==="application/pdf"?"PDF":m.startsWith("image/")?"IMG":m.startsWith("video/")?"VID":m.startsWith("audio/")?"AUD":"FILE";
const isPreviewable=(m:Material)=>m.mime.startsWith("image/")||m.mime==="application/pdf"||m.mime.startsWith("video/")||m.mime.startsWith("audio/");
export default function MaterialsScreen({user,onBack}:Props){
 const [rows,setRows]=useState<Material[]>([]),[query,setQuery]=useState(""),[folder,setFolder]=useState("all"),[favoritesOnly,setFavoritesOnly]=useState(false),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[edit,setEdit]=useState<Material|null>(null),[editTitle,setEditTitle]=useState(""),[editFolder,setEditFolder]=useState(""),[sort,setSort]=useState<SortMode>("recent"),[selected,setSelected]=useState<string[]>([]),[dragging,setDragging]=useState(false),[preview,setPreview]=useState<Material|null>(null),[previewUrl,setPreviewUrl]=useState(""),[previewBusy,setPreviewBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
 const load=async()=>{try{setRows(await listMaterials(user.id))}catch(e){setNotice(e instanceof Error?e.message:"Не удалось загрузить материалы")}};useEffect(()=>{void load()},[user.id]);
 useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl]);
 const folders=useMemo(()=>[...new Set(rows.map(x=>x.folder).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ru")),[rows]);
 const visible=useMemo(()=>rows.filter(x=>(!favoritesOnly||x.favorite)&&(folder==="all"||x.folder===folder)&&(!query.trim()||`${x.title} ${x.fileName} ${x.folder}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==="name"?a.title.localeCompare(b.title,"ru"):sort==="size"?b.size-a.size:sort==="used"?(b.useCount||0)-(a.useCount||0):(b.lastUsedAt||b.createdAt).localeCompare(a.lastUsedAt||a.createdAt)),[rows,query,folder,favoritesOnly,sort]);
 const upload=async(files:FileList|null)=>{if(!files?.length)return;setBusy(true);let ok=0;try{for(const f of Array.from(files)){await uploadMaterial(user.id,f,folder==="all"?"":folder,f.name);ok++}setNotice(`Загружено файлов: ${ok}`);await load()}catch(e){setNotice(e instanceof Error?e.message:"Ошибка загрузки")}finally{setBusy(false);if(input.current)input.current.value=""}};
 const drop=async(e:DragEvent)=>{e.preventDefault();setDragging(false);await upload(e.dataTransfer.files)};
 const openPreview=async(m:Material)=>{if(!isPreviewable(m)){setNotice("Для этого типа файла доступно скачивание, но не встроенный просмотр");return}setPreview(m);setPreviewBusy(true);try{const blob=await materialBlob(m);setPreviewUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(blob)})}catch(e){setNotice(e instanceof Error?e.message:"Не удалось открыть файл");setPreview(null)}finally{setPreviewBusy(false)}};
 const toggleSelected=(id:string)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const selectedRows=rows.filter(x=>selected.includes(x.id));
 const moveSelected=async()=>{if(!selectedRows.length)return;const next=prompt("Папка для выбранных материалов:",folder==="all"?"":folder);if(next===null)return;setBusy(true);try{for(const m of selectedRows)await renameMaterial(m.id,m.title,next);setNotice(`Перемещено: ${selectedRows.length}`);setSelected([]);await load()}catch(e){setNotice(e instanceof Error?e.message:"Не удалось переместить материалы")}finally{setBusy(false)}};
 const favoriteSelected=async()=>{if(!selectedRows.length)return;setBusy(true);try{for(const m of selectedRows)await setMaterialFavorite(m.id,true);setNotice(`Добавлено в избранное: ${selectedRows.length}`);setSelected([]);await load()}finally{setBusy(false)}};
 const deleteSelected=async()=>{if(!selectedRows.length||!confirm(`Удалить выбранные материалы (${selectedRows.length})?`))return;setBusy(true);try{for(const m of selectedRows)await deleteMaterial(m.id,m.storagePath);setNotice(`Удалено: ${selectedRows.length}`);setSelected([]);await load()}catch(e){setNotice(e instanceof Error?e.message:"Не удалось удалить материалы")}finally{setBusy(false)}};
 const renameFolder=async(f:string)=>{const next=prompt(`Новое имя папки «${f}»:`,f);if(next===null||next.trim()===f)return;const affected=rows.filter(x=>x.folder===f);setBusy(true);try{for(const m of affected)await renameMaterial(m.id,m.title,next);if(folder===f)setFolder(next.trim());setNotice(`Папка переименована · ${affected.length} файлов`);await load()}finally{setBusy(false)}};
 return <main className={`materials-shell ${dragging?"is-dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={e=>{if(e.currentTarget===e.target)setDragging(false)}} onDrop={e=>void drop(e)}>
 <header className="students-header"><div><button className="boards-secondary" onClick={onBack}>← Доски</button><div><strong>Материалы</strong><span>Личная библиотека преподавателя</span></div></div><><input ref={input} hidden type="file" multiple onChange={e=>void upload(e.target.files)}/><button className="boards-create" disabled={busy} onClick={()=>input.current?.click()}>{busy?"Загрузка…":"+ Загрузить"}</button></></header>
 <section className="materials-content"><nav className="dashboard-nav"><button onClick={onBack}>Доски</button><button onClick={()=>location.href="/?section=students"}>Ученики</button><button onClick={()=>location.href="/?section=assignments"}>Задания</button><button onClick={()=>location.href="/?section=progress"}>Прогресс</button><button onClick={()=>location.href="/?section=schedule"}>Расписание</button><button className="active">Материалы</button><button onClick={()=>{window.history.pushState({},"","/?section=notifications");window.dispatchEvent(new PopStateEvent("popstate"))}}>Уведомления</button><button onClick={()=>{window.history.pushState({},"","/?section=profile");window.dispatchEvent(new PopStateEvent("popstate"))}}>Настройки</button></nav>
 {notice&&<div className="access-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
 <div className="materials-stats"><article><b>{rows.length}</b><span>файлов</span></article><article><b>{folders.length}</b><span>папок</span></article><article><b>{rows.filter(x=>x.favorite).length}</b><span>избранных</span></article><article><b>{size(rows.reduce((n,x)=>n+x.size,0))}</b><span>занято</span></article></div>
 <div className="materials-toolbar"><input type="search" placeholder="Поиск по названию, файлу или папке" value={query} onChange={e=>setQuery(e.target.value)}/><select value={folder} onChange={e=>setFolder(e.target.value)}><option value="all">Все папки</option>{folders.map(x=><option key={x}>{x}</option>)}<option value="">Без папки</option></select><select value={sort} onChange={e=>setSort(e.target.value as SortMode)}><option value="recent">Сначала недавние</option><option value="name">По названию</option><option value="size">По размеру</option><option value="used">По использованию</option></select><button className={favoritesOnly?"materials-fav active":"materials-fav"} onClick={()=>setFavoritesOnly(x=>!x)}>★ Избранное</button><span>{visible.length} · {size(visible.reduce((n,x)=>n+x.size,0))}</span></div>
 {selected.length>0&&<div className="materials-bulk"><strong>Выбрано: {selected.length}</strong><button onClick={()=>void favoriteSelected()}>★ В избранное</button><button onClick={()=>void moveSelected()}>Переместить</button><button className="danger" onClick={()=>void deleteSelected()}>Удалить</button><button onClick={()=>setSelected([])}>Снять выбор</button></div>}
 <div className="materials-layout"><aside className="materials-folders"><button className={folder==="all"?"active":""} onClick={()=>setFolder("all")}>Все материалы <b>{rows.length}</b></button>{folders.map(f=><div className="materials-folder-row" key={f}><button className={folder===f?"active":""} onClick={()=>setFolder(f)}>{f}<b>{rows.filter(x=>x.folder===f).length}</b></button><button title="Переименовать папку" onClick={()=>void renameFolder(f)}>✎</button></div>)}<button className={folder===""?"active":""} onClick={()=>setFolder("")}>Без папки <b>{rows.filter(x=>!x.folder).length}</b></button><div className="materials-drop-hint">Перетащите файлы сюда<br/><small>до 50 МБ каждый</small></div></aside>
 <section>{visible.length===0?<div className="boards-empty"><strong>{rows.length?"Ничего не найдено":"Библиотека пока пуста"}</strong><span>Загрузите документы, PDF, изображения, аудио или видео. Файлы можно перетащить прямо в окно.</span></div>:<div className="materials-grid">{visible.map(m=><article className={`material-card ${selected.includes(m.id)?"selected":""}`} key={m.id}><label className="material-select"><input type="checkbox" checked={selected.includes(m.id)} onChange={()=>toggleSelected(m.id)}/><span/></label><button className={`material-icon ${m.mime.startsWith("image/")?"image":""}`} onClick={()=>void openPreview(m)} title="Предпросмотр">{icon(m.mime)}</button><div><b title={m.title}>{m.title}</b><span>{m.folder||"Без папки"} · {size(m.size)}</span><small>{m.fileName}</small><small>{m.useCount?`Использован ${m.useCount} раз`:"Ещё не использован"}</small></div><div className="material-actions"><button className={m.favorite?"favorite active":"favorite"} title="Избранное" onClick={async()=>{await setMaterialFavorite(m.id,!m.favorite);await load()}}>★</button>{isPreviewable(m)&&<button onClick={()=>void openPreview(m)}>Открыть</button>}<button onClick={()=>{sessionStorage.setItem("onlinerepetitor.material.pick",JSON.stringify({id:m.id,title:m.title,fileName:m.fileName,mime:m.mime,storagePath:m.storagePath}));setNotice(m.mime.startsWith("image/")||m.mime==="application/pdf"?"Материал выбран. Откройте нужную доску, чтобы вставить его.":"Этот файл сохранён в библиотеке. На доску сейчас вставляются изображения и PDF.")}}>На доску</button><button onClick={()=>void downloadMaterial(m).catch(e=>setNotice(e.message))}>Скачать</button><button onClick={()=>{setEdit(m);setEditTitle(m.title);setEditFolder(m.folder)}}>Изменить</button><button className="danger" onClick={async()=>{if(confirm(`Удалить «${m.title}»?`)){await deleteMaterial(m.id,m.storagePath);await load()}}}>×</button></div></article>)}</div>}</section></div></section>
 {dragging&&<div className="materials-drop-overlay"><strong>Отпустите файлы</strong><span>Они будут загружены в {folder==="all"?"библиотеку":folder||"«Без папки»"}</span></div>}
 {edit&&<div className="access-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEdit(null)}}><section className="access-modal materials-modal"><div className="access-head"><div><h2>Материал</h2><p>{edit.fileName}</p></div><button onClick={()=>setEdit(null)}>×</button></div><label><span>Название</span><input value={editTitle} onChange={e=>setEditTitle(e.target.value)}/></label><label><span>Папка</span><input value={editFolder} onChange={e=>setEditFolder(e.target.value)} placeholder="Например: Алгебра"/></label><div className="session-actions"><button className="students-primary" onClick={async()=>{await renameMaterial(edit.id,editTitle,editFolder);setEdit(null);await load()}}>Сохранить</button><button className="boards-secondary" onClick={()=>setEdit(null)}>Отмена</button></div></section></div>}
 {preview&&<div className="access-backdrop material-preview-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setPreview(null);setPreviewUrl("")}}}><section className="access-modal material-preview-modal"><div className="access-head"><div><h2>{preview.title}</h2><p>{preview.fileName} · {size(preview.size)}</p></div><button onClick={()=>{setPreview(null);setPreviewUrl("")}}>×</button></div><div className="material-preview-stage">{previewBusy?<span>Загрузка…</span>:previewUrl?(preview.mime.startsWith("image/")?<img src={previewUrl} alt={preview.title}/>:preview.mime==="application/pdf"?<iframe src={previewUrl} title={preview.title}/>:preview.mime.startsWith("video/")?<video src={previewUrl} controls/>:<audio src={previewUrl} controls/>):null}</div><div className="session-actions"><button className="students-primary" onClick={()=>void downloadMaterial(preview)}>Скачать</button><button className="boards-secondary" onClick={()=>{setPreview(null);setPreviewUrl("")}}>Закрыть</button></div></section></div>}
 </main>
}
