import { isRemoteBackendEnabled,remoteRequest,remoteStorageRequest } from "./backend";
export type Material={id:string;ownerId:string;folder:string;title:string;fileName:string;mime:string;size:number;storagePath:string;createdAt:string;favorite:boolean;useCount:number;lastUsedAt:string|null};
const KEY="onlinerepetitor.materials.v44";
const read=():Material[]=>{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}};
const write=(v:Material[])=>localStorage.setItem(KEY,JSON.stringify(v));
const map=(r:any):Material=>({id:r.id,ownerId:r.owner_id,folder:r.folder||"",title:r.title,fileName:r.file_name,mime:r.mime,size:Number(r.size_bytes||0),storagePath:r.storage_path,createdAt:r.created_at,favorite:r.favorite===true,useCount:Number(r.use_count||0),lastUsedAt:r.last_used_at||null});
const safe=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/g,"_").slice(-100)||"file";
export async function listMaterials(userId:string){if(!isRemoteBackendEnabled())return read().filter(x=>x.ownerId===userId).map(x=>({...x,favorite:x.favorite===true,useCount:x.useCount||0,lastUsedAt:x.lastUsedAt||null})).sort((a,b)=>(b.favorite?1:0)-(a.favorite?1:0)||(b.lastUsedAt||b.createdAt).localeCompare(a.lastUsedAt||a.createdAt));return (await remoteRequest<any[]>("/rest/v1/materials?select=*&order=favorite.desc,last_used_at.desc.nullslast,created_at.desc")).map(map)}
export async function uploadMaterial(userId:string,file:File,folder:string,title:string){if(file.size>50*1024*1024)throw new Error("Максимальный размер файла 50 МБ");const id=crypto.randomUUID(),path=`${userId}/${id}/${safe(file.name)}`,m:Material={id,ownerId:userId,folder:folder.trim(),title:title.trim()||file.name,fileName:file.name,mime:file.type||"application/octet-stream",size:file.size,storagePath:path,createdAt:new Date().toISOString(),favorite:false,useCount:0,lastUsedAt:null};if(!isRemoteBackendEnabled()){write([m,...read()]);return m}await remoteStorageRequest("materials",path,file);try{await remoteRequest("/rest/v1/materials",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({id,folder:m.folder,title:m.title,file_name:m.fileName,mime:m.mime,size_bytes:m.size,storage_path:path})})}catch(e){await remoteStorageRequest("materials",path,null,"DELETE").catch(()=>null);throw e}return m}
export async function deleteMaterial(id:string,path:string){if(!isRemoteBackendEnabled()){write(read().filter(x=>x.id!==id));return}await remoteRequest(`/rest/v1/materials?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});await remoteStorageRequest("materials",path,null,"DELETE").catch(()=>null)}
export async function renameMaterial(id:string,title:string,folder:string){if(!isRemoteBackendEnabled()){write(read().map(x=>x.id===id?{...x,title,folder}:x));return}await remoteRequest(`/rest/v1/materials?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({title:title.trim(),folder:folder.trim()})})}
export async function setMaterialFavorite(id:string,favorite:boolean){if(!isRemoteBackendEnabled()){write(read().map(x=>x.id===id?{...x,favorite}:x));return}await remoteRequest(`/rest/v1/materials?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({favorite})})}
export async function materialBlob(m:Material){if(!isRemoteBackendEnabled())throw new Error("Для повторного использования файла нужна серверная библиотека");const blob=await remoteStorageRequest("materials",m.storagePath);if(!blob)throw new Error("Файл не найден");return blob}
export async function downloadMaterial(m:Material){const blob=await materialBlob(m);const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=m.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export async function markMaterialUsed(id:string){const now=new Date().toISOString();if(!isRemoteBackendEnabled()){write(read().map(x=>x.id===id?{...x,useCount:(x.useCount||0)+1,lastUsedAt:now}:x));return}await remoteRequest("/rest/v1/rpc/mark_material_used",{method:"POST",body:JSON.stringify({p_material_id:id})})}
