import { useEffect,useMemo,useState } from "react";
import type { AuthUser } from "./authStore";
import { listNotifications,markAllNotificationsRead,markNotificationRead,type AppNotification,type NotificationKind } from "./notificationsStore";
type Props={user:AuthUser;onBack:()=>void};
const label=(k:NotificationKind)=>k==="assignment"?"Задание":k==="submission"?"Работа":k==="review"?"Проверка":k==="lesson"?"Занятие":"Материал";
export default function NotificationsScreen({user,onBack}:Props){
 const [rows,setRows]=useState<AppNotification[]>([]),[filter,setFilter]=useState<"all"|"unread">("all"),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{setRows(await listNotifications())}finally{setLoading(false)}};useEffect(()=>{void load()},[user.id]);
 const visible=useMemo(()=>rows.filter(x=>filter==="all"||!x.readAt),[rows,filter]);const unread=rows.filter(x=>!x.readAt).length;
 const open=async(n:AppNotification)=>{if(!n.readAt){await markNotificationRead(n.id);setRows(x=>x.map(v=>v.id===n.id?{...v,readAt:new Date().toISOString()}:v))}if(n.href)location.href=n.href};
 return <main className="notifications-shell"><header className="students-header"><div><button className="boards-secondary" onClick={onBack}>← Доски</button><div><strong>Уведомления</strong><span>{unread?`Непрочитанных: ${unread}`:"Всё прочитано"}</span></div></div>{unread>0&&<button className="boards-secondary" onClick={async()=>{await markAllNotificationsRead();setRows(x=>x.map(v=>({...v,readAt:v.readAt||new Date().toISOString()})))}}>Прочитать все</button>}</header><section className="notifications-content"><nav className="dashboard-nav"><button onClick={onBack}>Доски</button><button onClick={()=>location.href="/?section=students"}>Ученики</button><button onClick={()=>location.href="/?section=assignments"}>Задания</button><button onClick={()=>location.href="/?section=progress"}>Прогресс</button><button onClick={()=>location.href="/?section=schedule"}>Расписание</button><button onClick={()=>location.href="/?section=materials"}>Материалы</button><button className="active">Уведомления</button></nav><div className="notification-filters"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Все</button><button className={filter==="unread"?"active":""} onClick={()=>setFilter("unread")}>Непрочитанные <b>{unread}</b></button></div>{loading?<div className="boards-empty"><strong>Загружаем уведомления…</strong></div>:visible.length===0?<div className="boards-empty"><strong>Тихо и спокойно 🔔</strong><span>Здесь появятся события по заданиям, занятиям и материалам.</span></div>:<div className="notification-list">{visible.map(n=><button key={n.id} className={`notification-card ${n.readAt?"":"unread"}`} onClick={()=>void open(n)}><span className="notification-dot"/><div><small>{label(n.kind)} · {new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(n.createdAt))}</small><strong>{n.title}</strong>{n.body&&<p>{n.body}</p>}</div><span>›</span></button>)}</div>}</section></main>
}