import { useEffect,useState } from "react";
import type { AuthUser } from "./authStore";
import { applyProfileAppearance,getProfileSettings,saveProfileSettings,type ProfileSettings } from "./profileStore";
type Props={user:AuthUser;onBack:()=>void};
export default function ProfileScreen({user,onBack}:Props){
 const [s,setS]=useState<ProfileSettings>({displayName:user.name,theme:"system",compactUi:false,defaultBoardZoom:100}),[saved,setSaved]=useState("");
 useEffect(()=>{void getProfileSettings(user).then(x=>{setS(x);applyProfileAppearance(x)})},[user.id]);
 const patch=<K extends keyof ProfileSettings>(k:K,v:ProfileSettings[K])=>{const n={...s,[k]:v};setS(n);applyProfileAppearance(n)};
 return <main className="profile-shell"><header className="students-header"><div><button className="boards-secondary" onClick={onBack}>← Доски</button><div><strong>Профиль и настройки</strong><span>{user.email}</span></div></div><button className="boards-create" onClick={async()=>{await saveProfileSettings(s);setSaved("Сохранено");setTimeout(()=>setSaved(""),1800)}}>Сохранить</button></header><section className="profile-content"><nav className="dashboard-nav"><button onClick={onBack}>Доски</button><button onClick={()=>location.href="/?section=students"}>Ученики</button><button onClick={()=>location.href="/?section=assignments"}>Задания</button><button onClick={()=>location.href="/?section=progress"}>Прогресс</button><button onClick={()=>location.href="/?section=schedule"}>Расписание</button><button onClick={()=>location.href="/?section=materials"}>Материалы</button><button onClick={()=>location.href="/?section=notifications"}>Уведомления</button><button className="active">Настройки</button></nav>{saved&&<div className="access-notice">{saved}</div>}<div className="profile-grid"><section className="profile-card"><h2>Профиль</h2><label><span>Отображаемое имя</span><input value={s.displayName} maxLength={80} onChange={e=>patch("displayName",e.target.value)}/></label><label><span>Email</span><input value={user.email} disabled/></label><small>Имя видно участникам совместных досок и ученикам.</small></section><section className="profile-card"><h2>Интерфейс</h2><label><span>Тема</span><select value={s.theme} onChange={e=>patch("theme",e.target.value as ProfileSettings["theme"])}><option value="system">Как в системе</option><option value="light">Светлая</option><option value="dark">Тёмная</option></select></label><label className="profile-check"><span>Компактный интерфейс</span><input type="checkbox" checked={s.compactUi} onChange={e=>patch("compactUi",e.target.checked)}/></label></section><section className="profile-card"><h2>Доска</h2><label><span>Масштаб новых досок</span><select value={s.defaultBoardZoom} onChange={e=>patch("defaultBoardZoom",Number(e.target.value))}><option value={75}>75%</option><option value={90}>90%</option><option value={100}>100%</option><option value={110}>110%</option><option value={125}>125%</option></select></label><small>Настройка сохраняется в профиле и будет использоваться следующими версиями доски как стартовый масштаб.</small></section></div></section></main>
}