import { useEffect,useMemo,useState } from "react";
import type { AuthUser } from "./authStore";
import { getStudentsForTeacher,type StudentRecord } from "./studentsStore";
import { getUserBoards,type BoardSummary } from "./boardStore";
import { createScheduledLessons,deleteScheduledLesson,listScheduledLessons,updateScheduledLesson,type ScheduledLesson,type ScheduleRecurrence } from "./scheduleStore";
type Props={user:AuthUser;onBack:()=>void;onOpenBoard:(b:BoardSummary)=>void};
const localInput=(d:Date)=>{const p=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
const fmt=(iso:string)=>new Intl.DateTimeFormat("ru-RU",{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(iso));
const dayKey=(d:Date)=>`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
export default function ScheduleScreen({user,onBack,onOpenBoard}:Props){
 const [rows,setRows]=useState<ScheduledLesson[]>([]),[students,setStudents]=useState<StudentRecord[]>([]),[boards,setBoards]=useState<BoardSummary[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
 const [weekOffset,setWeekOffset]=useState(0),[modal,setModal]=useState(false),[studentId,setStudentId]=useState(""),[boardId,setBoardId]=useState(""),[title,setTitle]=useState(""),[starts,setStarts]=useState(""),[duration,setDuration]=useState("60"),[recurrence,setRecurrence]=useState<ScheduleRecurrence>("none"),[weeks,setWeeks]=useState("8"),[note,setNote]=useState("");
 const load=async()=>{setLoading(true);try{const [r,s,b]=await Promise.all([listScheduledLessons(user.id),getStudentsForTeacher(user).catch(()=>[]),getUserBoards(user)]);setRows(r);setStudents(s);setBoards(b)}catch(e){setNotice(e instanceof Error?e.message:"Не удалось загрузить расписание")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[user.id]);
 const monday=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);const wd=(d.getDay()+6)%7;d.setDate(d.getDate()-wd+weekOffset*7);return d},[weekOffset]);
 const days=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);return d});
 const teacher=students.length>0||rows.some(x=>x.teacherId===user.id);
 const visible=rows.filter(x=>x.status!=="cancelled"&&new Date(x.startsAt)>=monday&&new Date(x.startsAt)<new Date(monday.getTime()+7*86400000));
 const upcoming=rows.filter(x=>x.status==="planned"&&new Date(x.startsAt)>=new Date()).slice(0,6);
 const openNew=(date?:Date)=>{const s=students[0];setStudentId(s?.userId||"");setBoardId(s?.boardIds[0]||"");setTitle("");const d=date?new Date(date):new Date(Date.now()+3600000);d.setMinutes(Math.ceil(d.getMinutes()/30)*30,0,0);setStarts(localInput(d));setDuration("60");setRecurrence("none");setWeeks("8");setNote("");setModal(true)};
 const save=async()=>{const st=students.find(s=>s.userId===studentId);if(!st||!starts){setNotice("Выберите ученика и время");return}const b=boards.find(x=>x.id===boardId);try{await createScheduledLessons({teacherId:user.id,studentId:st.userId,studentName:st.name,boardId,boardTitle:b?.title||"Без доски",title:title||"Занятие",startsAt:new Date(starts).toISOString(),durationMinutes:Math.max(15,Number(duration)||60),recurrence,note,weeks:Number(weeks)||8});setModal(false);setNotice(recurrence==="weekly"?"Серия занятий создана":"Занятие добавлено");await load()}catch{setNotice("Не удалось сохранить занятие")}};
 const start=(x:ScheduledLesson)=>{const b=boards.find(v=>v.id===x.boardId);if(!b){setNotice("У занятия нет доступной доски");return}sessionStorage.setItem("onlinerepetitor.schedule.start",JSON.stringify({studentId:x.studentId,studentName:x.studentName,topic:x.title,scheduleId:x.id}));onOpenBoard(b)};
 return <main className="schedule-shell"><header className="students-header"><div><button className="boards-secondary" onClick={onBack}>← Доски</button><div><strong>Расписание</strong><span>План занятий и быстрый запуск урока</span></div></div>{teacher&&<button className="boards-create" onClick={()=>openNew()}>+ Занятие</button>}</header><section className="schedule-content">
  <nav className="dashboard-nav"><button onClick={onBack}>Доски</button><button onClick={()=>{window.history.pushState({},"","/?section=students");window.dispatchEvent(new PopStateEvent("popstate"))}}>Ученики</button><button onClick={()=>{window.history.pushState({},"","/?section=assignments");window.dispatchEvent(new PopStateEvent("popstate"))}}>Задания</button><button onClick={()=>{window.history.pushState({},"","/?section=progress");window.dispatchEvent(new PopStateEvent("popstate"))}}>Прогресс</button><button className="active">Расписание</button><button onClick={()=>{window.history.pushState({},"","/?section=materials");window.dispatchEvent(new PopStateEvent("popstate"))}}>Материалы</button><button onClick={()=>{window.history.pushState({},"","/?section=notifications");window.dispatchEvent(new PopStateEvent("popstate"))}}>Уведомления</button></nav>
  {notice&&<div className="access-notice">{notice}</div>}<div className="schedule-toolbar"><button onClick={()=>setWeekOffset(x=>x-1)}>←</button><button onClick={()=>setWeekOffset(0)}>Сегодня</button><strong>{new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long"}).format(monday)} – {new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",year:"numeric"}).format(days[6])}</strong><button onClick={()=>setWeekOffset(x=>x+1)}>→</button></div>
  {loading?<div className="boards-empty"><strong>Загружаем расписание…</strong></div>:<div className="schedule-layout"><div className="week-grid">{days.map(d=><section key={dayKey(d)} className={`schedule-day ${dayKey(d)===dayKey(new Date())?"today":""}`}><header><b>{new Intl.DateTimeFormat("ru-RU",{weekday:"short"}).format(d)}</b><span>{d.getDate()}</span></header><div>{visible.filter(x=>dayKey(new Date(x.startsAt))===dayKey(d)).sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).map(x=><article key={x.id} className={`schedule-event ${x.status}`}><time>{new Intl.DateTimeFormat("ru-RU",{hour:"2-digit",minute:"2-digit"}).format(new Date(x.startsAt))}</time><b>{x.title}</b><span>{x.studentName}</span><small>{x.durationMinutes} мин · {x.boardTitle}</small><div>{x.teacherId===user.id&&<button onClick={()=>start(x)}>Начать</button>}{x.teacherId===user.id&&<button onClick={async()=>{await updateScheduledLesson(x.id,{status:"completed"});await load()}}>✓</button>}{x.teacherId===user.id&&<button className="danger" onClick={async()=>{const series=!!x.recurrenceGroupId&&confirm("Удалить всю серию? Нажмите «Отмена», чтобы удалить только это занятие.");await deleteScheduledLesson(x.id,series,x.recurrenceGroupId);await load()}}>×</button>}</div></article>)}{teacher&&<button className="schedule-add-day" onClick={()=>{const x=new Date(d);x.setHours(18,0,0,0);openNew(x)}}>+</button>}</div></section>)}</div>
   <aside className="schedule-side"><h3>Ближайшие занятия</h3>{upcoming.length===0?<div className="student-history-empty">Ближайших занятий нет.</div>:upcoming.map(x=><article key={x.id}><time>{fmt(x.startsAt)}</time><b>{x.title}</b><span>{x.teacherId===user.id?x.studentName:"Занятие с преподавателем"}</span><small>{x.durationMinutes} мин · {x.boardTitle}</small>{x.teacherId===user.id&&<button onClick={()=>start(x)}>Открыть доску →</button>}</article>)}</aside></div>}
 </section>
 {modal&&<div className="access-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><section className="access-modal schedule-modal"><div className="access-head"><div><h2>Запланировать занятие</h2><p>Можно сразу создать еженедельную серию.</p></div><button onClick={()=>setModal(false)}>×</button></div><div className="schedule-form"><label><span>Ученик</span><select value={studentId} onChange={e=>{setStudentId(e.target.value);setBoardId(students.find(s=>s.userId===e.target.value)?.boardIds[0]||"")}}>{students.map(s=><option key={s.userId} value={s.userId}>{s.name}</option>)}</select></label><label><span>Доска</span><select value={boardId} onChange={e=>setBoardId(e.target.value)}><option value="">Без доски</option>{boards.filter(b=>students.find(s=>s.userId===studentId)?.boardIds.includes(b.id)).map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><label className="wide"><span>Название / тема</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Алгебра · квадратные уравнения"/></label><label><span>Дата и время</span><input type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)}/></label><label><span>Длительность</span><select value={duration} onChange={e=>setDuration(e.target.value)}><option value="45">45 мин</option><option value="60">60 мин</option><option value="90">90 мин</option><option value="120">120 мин</option></select></label><label><span>Повтор</span><select value={recurrence} onChange={e=>setRecurrence(e.target.value as ScheduleRecurrence)}><option value="none">Не повторять</option><option value="weekly">Каждую неделю</option></select></label>{recurrence==="weekly"&&<label><span>Количество недель</span><input type="number" min="2" max="24" value={weeks} onChange={e=>setWeeks(e.target.value)}/></label>}<label className="wide"><span>Заметка</span><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Что подготовить к занятию…"/></label></div><div className="session-actions"><button className="students-primary" onClick={()=>void save()}>Сохранить</button><button className="boards-secondary" onClick={()=>setModal(false)}>Отмена</button></div></section></div>}
 </main>
}
