import { useEffect,useMemo,useState } from "react";
import { createQaReport,listQaReports,type QaReport,type QaSeverity } from "./qaFeedbackStore";
import type { AccountRole } from "./accountRoleStore";
import type { AuthUser } from "./authStore";

type Props={user:AuthUser;accountRole:AccountRole;isAppAdmin:boolean;onBack:()=>void};
type RoleFilter="all"|"teacher"|"student";
type TestItem={id:string;title:string;steps:string[];expect:string;roles:RoleFilter[];device?:string};
type Section={id:string;icon:string;title:string;lead:string;tests:TestItem[]};
type ReportDraft={testId:string;title:string;description:string;expected:string;severity:QaSeverity};
const A:RoleFilter[]=["all"],T:RoleFilter[]=["teacher"],S:RoleFilter[]=["student"];

const sections:Section[]=[
{id:"start",icon:"🚪",title:"1. Вход и аккаунт",lead:"Проверяем только обычные пользовательские сценарии. Административные функции в эту инструкцию не входят.",tests:[
{id:"register",title:"Регистрация",roles:A,steps:["Выйдите из аккаунта.","Создайте новый аккаунт: имя, email и пароль.","Перезагрузите страницу.","Войдите созданным аккаунтом."],expect:"Регистрация проходит без перезагрузки приложения, ошибки формы понятны, зарегистрированный аккаунт сохраняется и повторно входит."},
{id:"login",title:"Вход и выход",roles:A,steps:["Войдите существующим аккаунтом.","Откройте «Настройки».","Выйдите из аккаунта.","Войдите повторно."],expect:"После выхода кабинет недоступен; после повторного входа открывается тот же пользователь."},
{id:"guest",title:"Гостевой вход по приглашению",roles:A,steps:["Откройте ссылку-приглашение в приватном окне.","Продолжите как гость.","Введите имя и войдите на доску.","Закройте вкладку и при необходимости повторите с новой гостевой сессией."],expect:"Гость попадает только в разрешённый сценарий совместной доски и не превращается в постоянный зарегистрированный аккаунт. Гостевые записи автоматически очищаются сервером примерно через 6 часов."},
{id:"teacher-request",title:"Запрос роли преподавателя",roles:S,steps:["В аккаунте ученика откройте настройки/профиль, где доступен запрос роли.","Отправьте запрос преподавателя.","Перезагрузите приложение."],expect:"До внешнего одобрения пользователь остаётся учеником, преподавательские разделы и инструменты не появляются самопроизвольно."}
]},
{id:"cabinet",icon:"🗂️",title:"2. Главный кабинет и доски",lead:"Проверяем навигацию, список досок и обычный жизненный цикл рабочего пространства.",tests:[
{id:"dashboard",title:"Главный экран",roles:A,steps:["Откройте кабинет.","Проверьте карточку профиля, основные разделы и список досок.","Измените размер окна."],expect:"Главные действия видимы, карточки не перекрываются, профиль открывается по своей плитке."},
{id:"create-board",title:"Создание и открытие доски",roles:T,steps:["Создайте новую доску.","Откройте её.","Вернитесь в кабинет.","Откройте доску повторно."],expect:"Доска создаётся один раз, открывается без потери содержимого и остаётся в списке."},
{id:"board-list",title:"Поиск, фильтры и сортировка",roles:A,steps:["Откройте список из нескольких досок.","Используйте поиск по названию.","Переключите доступные фильтры.","Проверьте сортировку."],expect:"Список соответствует поиску и выбранному режиму, карточки не дублируются."},
{id:"rename",title:"Переименование доски",roles:T,steps:["Переименуйте свою доску.","Откройте её и вернитесь назад.","Обновите страницу."],expect:"Новое название одинаково отображается внутри доски и в кабинете."},
{id:"trash",title:"Удаление и корзина",roles:T,steps:["Удалите тестовую доску.","Откройте корзину.","Восстановите доску.","Повторно удалите и проверьте окончательное удаление, если оно доступно."],expect:"Обычное удаление обратимо, восстановление возвращает доску и её содержимое."},
{id:"backup",title:"Экспорт и импорт",roles:T,steps:["Скачайте резервную копию своей доски/пространства.","Импортируйте копию.","Откройте восстановленную доску."],expect:"Импорт не портит исходную доску; поддерживаемые вложения и объекты восстанавливаются."}
]},
{id:"sharing",icon:"🔗",title:"3. Приглашения и доступ",lead:"Для этих проверок нужны преподаватель и второй обычный аккаунт/гость.",tests:[
{id:"invite-edit",title:"Ссылка с редактированием",roles:T,steps:["Создайте ссылку-приглашение с правом редактирования.","Откройте её вторым аккаунтом.","Измените обычный объект."],expect:"Приглашённый редактор видит доску и разрешённые изменения синхронизируются."},
{id:"invite-view",title:"Ссылка только для просмотра",roles:T,steps:["Создайте viewer-ссылку.","Откройте её отдельно.","Попробуйте изменить объект."],expect:"Просмотр работает, а изменение содержимого действительно заблокировано."},
{id:"share-password",title:"Пароль ссылки",roles:T,steps:["Создайте защищённую ссылку, если настройка доступна.","Введите неправильный пароль.","Введите правильный."],expect:"Неверный пароль не открывает доску, правильный открывает."},
{id:"presence",title:"Присутствие и удалённые курсоры",roles:A,steps:["Откройте одну доску двумя участниками.","Двигайте курсоры.","Закройте одну вкладку."],expect:"Участники и курсоры появляются и исчезают без ручного обновления."}
]},
{id:"tools",icon:"🧰",title:"4. Доска: навигация, рисование и создание",lead:"Проверяем фактический набор инструментов текущей версии.",tests:[
{id:"hand",title:"Рука · H / Р",roles:A,steps:["Выберите «Рука».","Потяните пустое место.","Тапните по объекту.","Потяните уже выбранный обычный объект."],expect:"Пустое место двигает камеру; тап выбирает объект; выбранный разрешённый объект можно перемещать, не переключаясь на «Выделение»."},
{id:"select",title:"Выделение · V / М",roles:A,steps:["Выделите один объект.","Добавьте несколько объектов.","Переместите выделение.","Для доступного объекта проверьте resize и поворот."],expect:"Рамка и маркеры читаемы, объект не прыгает и изменения сохраняются."},
{id:"lasso",title:"Петля · Q / Й",roles:A,steps:["Обведите несколько объектов.","Повторите вокруг другой группы."],expect:"Петля выделяет нужную группу без случайного создания объектов."},
{id:"pen",title:"Карандаш · P / З",roles:A,steps:["Измените цвет/толщину.","Нарисуйте линию и короткий штрих."],expect:"Рисование плавное, выбранные параметры применяются."},
{id:"marker",title:"Маркер · M / Ь",roles:A,steps:["Проведите маркером поверх текста или фигуры.","Измените толщину."],expect:"Маркер полупрозрачный и не закрывает содержимое сплошной краской."},
{id:"eraser",title:"Ластик · E / У",roles:A,steps:["Нарисуйте карандашом и маркером.","Проведите ластиком через штрихи."],expect:"Ластик стирает рукописные линии, а не удаляет произвольные объекты."},
{id:"text",title:"Текст · T / Е",roles:A,steps:["Создайте текст.","Введите несколько строк.","Закончите редактирование и откройте снова."],expect:"Текст печатается слева направо, курсор ведёт себя нормально, содержимое сохраняется."},
{id:"sticky",title:"Стикер · S / Ы",roles:A,steps:["Создайте стикер.","Измените текст, размер и положение."],expect:"Стикер остаётся редактируемым после сохранения."},
{id:"shape",title:"Фигуры · R / К",roles:A,steps:["Создайте несколько доступных типов фигур.","Измените размеры и поворот."],expect:"Фигуры корректно отображаются и редактируются."},
{id:"connector",title:"Связь / стрелка · C / С",roles:A,steps:["Создайте две фигуры.","Соедините их.","Переместите фигуры.","Проверьте доступные варианты стрелки/маршрута."],expect:"Связь остаётся привязанной и перестраивается вслед за объектами."},
{id:"comment",title:"Комментарий · N / Т",roles:A,steps:["Добавьте комментарий на доске.","Откройте обсуждение.","Ответьте и закройте/разрешите ветку, если действие доступно."],expect:"Комментарий синхронизируется и ведёт к нужному месту/обсуждению."},
{id:"media",title:"Фото / PDF · I / Ш",roles:T,steps:["Добавьте изображение.","Добавьте PDF.","Измените размер и положение.","Перезагрузите доску."],expect:"Файлы сохраняются и повторно открываются."},
{id:"linkmedia",title:"Видео / аудио по ссылке · L / Д",roles:T,steps:["Добавьте поддерживаемую ссылку.","Измените название.","Откройте плеер."],expect:"Ссылка распознаётся и сохраняется вместе с доской."}
]},
{id:"teacher-tools",icon:"🎓",title:"5. Инструменты преподавателя",lead:"Эти объекты создаёт преподаватель. Ученик должен взаимодействовать с заданием, но не менять его конструкцию.",tests:[
{id:"frame",title:"Фрейм · F / А",roles:T,steps:["Создайте фрейм.","Переименуйте.","Поместите внутрь объекты.","Проверьте порядок презентации и заметки, если доступны."],expect:"Фрейм сохраняет содержимое и используется как раздел/слайд."},
{id:"table",title:"Таблица · B / И",roles:T,steps:["Создайте таблицу.","Измените ячейки.","Добавьте/удалите строки и столбцы."],expect:"Структура и текст таблицы сохраняются."},
{id:"formula",title:"Формула · X / Ч",roles:T,steps:["Создайте формулу.","Используйте символы/шаблоны.","Измените размер шрифта."],expect:"Формула отображается читаемо и сохраняет конструкцию."},
{id:"graph",title:"График · Y / Н",roles:T,steps:["Создайте график функции.","Введите корректное выражение.","Измените размер."],expect:"График строится внутри объекта и сохраняется."},
{id:"checklist",title:"Чек-лист · K / Л",roles:T,steps:["Создайте задание.","Добавьте пункты.","Откройте эту же доску учеником и отметьте пункты."],expect:"Преподаватель меняет структуру, ученик может выполнять пункты без доступа к конструкции."},
{id:"quiz",title:"Мини-тест · G / П",roles:T,steps:["Создайте вопрос, варианты, правильный ответ и пояснение.","Откройте учеником и ответьте."],expect:"Ученик выбирает ответ и получает предусмотренную проверку, но не редактирует вопрос/правильный вариант."},
{id:"flashcard",title:"Карточка · J / О",roles:T,steps:["Создайте вопрос и ответ.","Переверните карточку.","Проверьте её учеником."],expect:"Карточка переворачивается, ученик не меняет её исходный текст."},
{id:"cover",title:"Шторка · U / Г",roles:T,steps:["Создайте шторку над ответом.","Откройте и закройте.","Повторите учеником."],expect:"Ученик может открыть ответ, но не перестраивать шторку."},
{id:"student-guard",title:"Защита конструкции задания",roles:S,steps:["Выделите созданный преподавателем фрейм/таблицу/формулу/график/чек-лист/тест/карточку/шторку/медиа по ссылке.","Попробуйте перемещение, resize, удаление, дублирование, Alt-drag, стрелки, слои, группировку и контекстное меню.","Откройте Ctrl+K."],expect:"Ученик может решать задание, но не может структурно изменить защищённые объекты или вызвать преподавательский инструмент обходным способом."}
]},
{id:"attachments",icon:"📎",title:"6. Вложения ученика и согласование",lead:"Текущий сценарий требует одновременно открыть доску преподавателем и учеником.",tests:[
{id:"student-attachment",title:"Отправка вложения учеником",roles:S,steps:["На общей доске выберите «Фото / PDF».","Отправьте изображение или PDF.","Не закрывайте доску."],expect:"Файл не появляется на доске сразу. Ученик видит статус «На согласовании»."},
{id:"teacher-approval",title:"Предпросмотр и решение",roles:T,steps:["Пока ученик отправляет файл, держите эту же доску открытой.","Проверьте карточку запроса и предпросмотр.","Одобрите один файл и отклоните другой."],expect:"Одобренный файл появляется на доске, отклонённый не появляется; ученик получает результат."},
{id:"approval-queue",title:"Очередь нескольких вложений",roles:T,steps:["Попросите ученика быстро отправить 2–3 файла.","Переключайтесь между запросами стрелками.","Обработайте их в разном порядке."],expect:"Запросы не затирают друг друга и не дублируются; счётчик очереди корректен."},
{id:"approval-reconnect",title:"Доставка после reconnect",roles:A,steps:["Отправьте вложение при кратком переподключении второго клиента.","Подождите несколько секунд."],expect:"Пока запрос ожидает решения, приложение повторяет его доставку; после решения повторы прекращаются."}
]},
{id:"editing",icon:"🧲",title:"7. Редактирование и история",lead:"Проверяем операции, которые применяются к уже созданным объектам.",tests:[
{id:"context",title:"Контекстное меню",roles:A,steps:["Откройте меню обычного разрешённого объекта.","Проверьте доступные копирование/дублирование/слои/блокировку/удаление."],expect:"Команды относятся к текущему выделению и не затрагивают соседние объекты."},
{id:"group",title:"Группировка и выравнивание",roles:T,steps:["Выделите несколько обычных объектов.","Сгруппируйте и разгруппируйте.","Проверьте доступные варианты выравнивания."],expect:"Позиции сохраняются, объекты не прыгают после операции."},
{id:"layers",title:"Слои",roles:T,steps:["Измените порядок перекрывающихся объектов.","Переместите объект вперёд/назад."],expect:"Визуальный порядок соответствует выполненной команде."},
{id:"undo",title:"Undo / Redo",roles:A,steps:["Сделайте несколько разрешённых изменений.","Последовательно отмените их.","Верните Redo."],expect:"История идёт по шагам без удвоения и потери состояния."},
{id:"search-board",title:"Поиск и Ctrl+K",roles:A,steps:["Откройте поиск/палитру команд.","Введите название инструмента или команды.","Выберите результат клавиатурой."],expect:"Поиск работает с клавиатуры; ученику не предлагаются запрещённые преподавательские инструменты."},
{id:"viewport",title:"Масштаб и личная позиция камеры",roles:A,steps:["Измените масштаб и положение доски.","Перейдите в кабинет.","Вернитесь."],expect:"Личная позиция камеры восстанавливается и не перезаписывает положение второго участника."}
]},
{id:"realtime",icon:"⚡",title:"8. Совместная работа и синхронизация",lead:"Откройте одну доску в двух разных браузерах/профилях.",tests:[
{id:"sync",title:"Синхронизация объектов",roles:A,steps:["Измените разрешённый объект в первом клиенте.","Наблюдайте второй клиент.","Повторите в обратную сторону."],expect:"Изменения приходят без ручного обновления и не создают копии объекта."},
{id:"comments",title:"Обсуждения",roles:A,steps:["Создайте комментарий первым участником.","Ответьте вторым.","Отметьте ветку решённой, если доступно."],expect:"Оба клиента видят актуальную ветку и состояние."},
{id:"follow",title:"Следование за преподавателем",roles:A,steps:["Преподавателем включите управление/показ экрана доски, если доступно.","Учеником включите следование.","Перемещайте камеру преподавателя."],expect:"Ученик следует за преподавателем только в соответствующем режиме и может выйти из него."},
{id:"offline",title:"Offline / reconnect",roles:A,steps:["Откройте доску онлайн.","Кратко отключите сеть.","Включите сеть.","Сравните состояние второго клиента."],expect:"Статус соединения понятен, после reconnect realtime восстанавливается без тихого сброса доски."}
]},
{id:"learning",icon:"📚",title:"9. Ученики, задания, прогресс, расписание и материалы",lead:"Проверяем пользовательские разделы вне самой доски.",tests:[
{id:"students",title:"Ученики преподавателя",roles:T,steps:["Откройте «Ученики».","Проверьте список и доступные действия.","Откройте связанную доску/карточку, если доступно."],expect:"Преподаватель видит только относящихся к нему учеников и рабочие действия."},
{id:"assign-teacher",title:"Создание задания",roles:T,steps:["Откройте «Задания».","Создайте задание ученику с названием/описанием/сроком и связанной доской, если поля доступны.","Сохраните."],expect:"Задание появляется у преподавателя и у назначенного ученика."},
{id:"assign-student",title:"Задание ученика",roles:S,steps:["Откройте «Задания».","Откройте назначенное задание.","Выполните доступное действие/переход на доску."],expect:"Ученик видит только свои задания и не получает преподавательские действия создания/проверки."},
{id:"progress",title:"Прогресс",roles:T,steps:["Откройте «Прогресс».","Выберите ученика/период, если фильтры доступны.","Проверьте связанные занятия и задания."],expect:"Данные соответствуют выбранному ученику и не смешиваются между аккаунтами."},
{id:"schedule-t",title:"Расписание преподавателя",roles:T,steps:["Откройте «Расписание».","Создайте/измените тестовое занятие.","Перезагрузите страницу."],expect:"Занятие сохраняется с учеником, датой, временем и темой."},
{id:"schedule-s",title:"Расписание ученика",roles:S,steps:["Откройте «Расписание».","Проверьте ближайшие и будущие занятия."],expect:"Ученик видит относящиеся к нему занятия без преподавательских кнопок редактирования."},
{id:"materials",title:"Материалы",roles:T,steps:["Откройте «Материалы».","Загрузите поддерживаемые файлы.","Используйте поиск/папки/избранное, если доступны.","Отправьте изображение или PDF на доску."],expect:"Материал сохраняется и выбранный поддерживаемый файл переносится на доску."},
{id:"templates",title:"Шаблоны",roles:T,steps:["Откройте «Шаблоны».","Создайте новую доску из существующего шаблона.","Откройте созданную доску."],expect:"Новая доска получает содержимое шаблона, оригинал не изменяется."}
]},
{id:"ai",icon:"🤖",title:"10. AI-инструменты",lead:"AI на доске доступен преподавателю и создаёт учебный материал с предпросмотром.",tests:[
{id:"board-ai",title:"AI-помощник на доске",roles:T,steps:["Откройте кнопку с роботом.","Введите «кубические уравнения с целыми корнями».","Создайте предпросмотр.","Повторите с «задачи по теореме Пифагора» и «дроби на сложение»."],expect:"Содержание результата меняется вместе с запросом, а не только заголовок. Материал не вставляется на доску до подтверждения."},
{id:"ai-modes",title:"Режимы генерации",roles:T,steps:["Проверьте примеры, уравнения, дроби, геометрию, функции, проценты, текстовые задачи и смешанный режим.","Измените уровень, количество и показ ответов."],expect:"Настройки отражаются в предпросмотре и вставленном материале."},
{id:"ai-student",title:"AI у ученика",roles:S,steps:["Откройте доску ученика.","Проверьте панели инструментов и Ctrl+K."],expect:"Инструмент создания AI-материалов ученику не доступен."}
]},
{id:"notifications",icon:"🔔",title:"11. Уведомления",lead:"Проверяем центр уведомлений и пользовательские настройки.",tests:[
{id:"notifications",title:"Центр уведомлений",roles:A,steps:["Создайте событие другим аккаунтом, если оно формирует уведомление.","Откройте «Уведомления».","Проверьте непрочитанные и открытие связанного объекта."],expect:"Счётчик и состояние прочтения обновляются, переход ведёт в связанный раздел."},
{id:"notify-settings",title:"Настройки уведомлений",roles:A,steps:["Откройте настройки уведомлений.","Измените доступные категории.","Сохраните и откройте настройки повторно."],expect:"Пользовательские настройки сохраняются."}
]},
{id:"account",icon:"⚙️",title:"12. Профиль, настройки и тарифы",lead:"Профиль и общие настройки проверяются отдельно.",tests:[
{id:"profile",title:"Профиль",roles:A,steps:["Нажмите плитку профиля.","Проверьте имя, email и роль.","Вернитесь назад."],expect:"Профиль открывается отдельным экраном и не смешивается с общими настройками."},
{id:"settings",title:"Настройки",roles:A,steps:["Откройте «Настройки».","Проверьте тему, интерфейс и доступные пользовательские параметры.","Перезагрузите приложение."],expect:"Настройки сохраняются и применяются после перезагрузки."},
{id:"billing",title:"Тарифы",roles:A,steps:["Откройте экран тарифов из настроек.","Проверьте текущий тариф и доступные варианты интерфейса."],expect:"Экран тарифов открывается без ошибок и корректно показывает доступную пользователю информацию. Реальную оплату проверяйте только после подключения платёжного провайдера."},
{id:"pwa",title:"Установка приложения (PWA)",roles:A,steps:["В поддерживаемом браузере откройте установку приложения.","Запустите установленную версию.","Вернитесь в браузерную версию."],expect:"PWA открывает актуальное приложение, а обычная браузерная версия продолжает работать."}
]},
{id:"mobile",icon:"📱",title:"13. Телефон и планшет",lead:"Мобильную версию обязательно проверяем на реальном touch-устройстве.",tests:[
{id:"portrait",title:"Телефон: portrait",roles:A,device:"≤700 px",steps:["Откройте доску вертикально.","Проверьте верхнюю панель и нижний док.","Откройте полную палитру инструментов.","Проверьте экранную клавиатуру."],expect:"Верхняя панель не исчезает, подписи не раздувают док, отдельная панель масштаба не перекрывает инструменты, клавиатура не закрывает активное поле."},
{id:"landscape",title:"Телефон: landscape",roles:A,device:"≤1100 px",steps:["Поверните телефон горизонтально.","Проверьте инструменты, модальные окна и доску.","Вернитесь в portrait."],expect:"Интерфейс перестраивается без перезагрузки и не оставляет элементы за экраном."},
{id:"touch",title:"Touch: Smart Hand и вложения",roles:A,steps:["В режиме «Рука» тапните обычный объект.","Потяните выбранный объект.","Отдельно проверьте разрешённое изображение/PDF.","Сделайте pinch-to-zoom двумя пальцами."],expect:"Выбранный объект следует за пальцем без рывка назад; pinch масштабирует доску, а не браузерную страницу."},
{id:"tablet",title:"Планшет",roles:A,device:"701–1180 px",steps:["Проверьте portrait и landscape.","Откройте основные панели и модальные окна.","Поработайте мышью/стилусом и touch, если доступны."],expect:"Интерфейс использует доступное пространство, кнопки не перекрываются и не требуют слишком точного попадания."}
]}
];

const roleLabel=(r:RoleFilter)=>r==="teacher"?"Преподаватель":r==="student"?"Ученик":"Обе роли";
const statusKey=(id:string)=>`onlinerepetitor.qa.v213.${id}`;

export default function TestingGuideScreen({user,accountRole,onBack}:Props){
 const [query,setQuery]=useState(""),[role,setRole]=useState<RoleFilter>("all"),[onlyPending,setOnlyPending]=useState(false),[tick,setTick]=useState(0),[open,setOpen]=useState<Record<string,boolean>>({});
 const [reportDraft,setReportDraft]=useState<ReportDraft|null>(null),[reports,setReports]=useState<QaReport[]>([]),[reportBusy,setReportBusy]=useState(false),[reportNotice,setReportNotice]=useState("");
 const loadReports=()=>listQaReports(false).then(setReports).catch(()=>{});
 useEffect(()=>{void loadReports()},[user.id]);
 const allTests=sections.flatMap(x=>x.tests),done=(id:string)=>localStorage.getItem(statusKey(id))==="1";
 const setDone=(id:string,value:boolean)=>{if(value)localStorage.setItem(statusKey(id),"1");else localStorage.removeItem(statusKey(id));setTick(x=>x+1)};
 const visible=useMemo(()=>sections.map(section=>({...section,tests:section.tests.filter(test=>{const q=query.trim().toLowerCase(),hay=`${section.title} ${test.title} ${test.steps.join(" ")} ${test.expect}`.toLowerCase();return(!q||hay.includes(q))&&(role==="all"||test.roles.includes("all")||test.roles.includes(role))&&(!onlyPending||!done(test.id))})})).filter(x=>x.tests.length),[query,role,onlyPending,tick]);
 const completed=allTests.filter(x=>done(x.id)).length,percent=Math.round(completed/allTests.length*100),suggestedRole:RoleFilter=accountRole;
 const reset=()=>{if(!confirm("Сбросить все отметки этой инструкции на устройстве?"))return;allTests.forEach(x=>localStorage.removeItem(statusKey(x.id)));setTick(x=>x+1)};
 const openReport=(test:TestItem)=>setReportDraft({testId:test.id,title:test.title,description:"",expected:test.expect,severity:"medium"});
 const submitReport=async()=>{if(!reportDraft||!reportDraft.description.trim()||reportBusy)return;setReportBusy(true);setReportNotice("");try{await createQaReport({...reportDraft,description:reportDraft.description.trim(),environment:`${navigator.userAgent} · ${window.innerWidth}×${window.innerHeight}`});setReportDraft(null);setReportNotice("Сообщение об ошибке отправлено.");await loadReports()}catch(e){setReportNotice(e instanceof Error?e.message:"Не удалось отправить сообщение")}finally{setReportBusy(false)}};
 return <main className="testing-guide-shell"><header className="students-header testing-guide-header"><div><button className="boards-secondary" onClick={onBack}>← Доски</button><div><strong>🧪 Полная проверка приложения</strong><span>Актуальная инструкция v213 · без административных функций</span></div></div><div className="testing-guide-header-actions"><button className="boards-secondary" onClick={()=>setOpen(Object.fromEntries(sections.map(x=>[x.id,true])))}>Развернуть всё</button><button className="boards-secondary" onClick={()=>setOpen({})}>Свернуть</button></div></header>
 <section className="testing-guide-content">
  <div className="testing-guide-hero"><div><span className="testing-guide-kicker">QA · v213</span><h1>OnlineRepetitor: проверка от входа до мобильной доски</h1><p>Инструкция заново сверена с текущими функциями приложения. Администратор, админ-панель и выдача тарифов здесь намеренно не рассматриваются. Основные роли только две: преподаватель и ученик.</p></div><div className="testing-guide-score"><strong>{percent}%</strong><span>{completed} из {allTests.length} проверок</span><div><i style={{width:`${percent}%`}}/></div></div></div>
  <div className="testing-guide-rules"><article><b>① Два аккаунта</b><span>Для полного прогона нужны преподаватель и ученик. Совместные функции проверяйте одновременно в двух браузерах или профилях.</span></article><article><b>② Реальные устройства</b><span>Минимум desktop и настоящий телефон в portrait/landscape. Touch-поведение не заменяйте одной эмуляцией мышью.</span></article><article><b>③ Фиксируйте регрессии</b><span>Укажите раздел, пункт, шаг, фактический результат и устройство. Кнопка сообщения об ошибке есть в каждом тесте.</span></article></div>
  <div className="testing-guide-toolbar"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="🔎 Найти функцию или проверку…"/><select value={role} onChange={e=>setRole(e.target.value as RoleFilter)}><option value="all">Преподаватель + ученик</option><option value="teacher">Преподаватель</option><option value="student">Ученик</option></select><button className={onlyPending?"active":""} onClick={()=>setOnlyPending(x=>!x)}>☐ Только непроверенные</button><button onClick={()=>setRole(suggestedRole)}>Моя роль: {roleLabel(suggestedRole)}</button><button className="danger" onClick={reset}>Сбросить отметки</button></div>
  <div className="testing-guide-icon-legend"><b>Инструменты доски:</b><span>↖ выделение</span><span>✋ рука</span><span>➰ петля</span><span>✏️ карандаш</span><span>🖍️ маркер</span><span>⌫ ластик</span><span>↗ связь</span><span>▣ фрейм</span><span>💬 комментарий</span><span>T текст</span><span>🗒️ стикер</span><span>◯ фигуры</span><span>▦ таблица</span><span>∑ формула</span><span>📈 график</span><span>☑ чек-лист</span><span>❓ тест</span><span>🎴 карточка</span><span>🙈 шторка</span><span>🖼️ фото/PDF</span><span>▶️ медиа</span><span>🤖 AI</span></div>
  <div className="testing-guide-sections">{visible.map(section=>{const secDone=section.tests.filter(x=>done(x.id)).length,expanded=open[section.id]??true;return <section className="testing-guide-section" key={section.id}><button className="testing-guide-section-head" onClick={()=>setOpen(x=>({...x,[section.id]:!expanded}))}><span className="testing-guide-section-icon">{section.icon}</span><span><strong>{section.title}</strong><small>{section.lead}</small></span><b>{secDone}/{section.tests.length}</b><i>{expanded?"⌃":"⌄"}</i></button>{expanded&&<div className="testing-guide-tests">{section.tests.map(test=><article className={`testing-guide-test ${done(test.id)?"done":""}`} key={test.id}><label className="testing-guide-check"><input type="checkbox" checked={done(test.id)} onChange={e=>setDone(test.id,e.target.checked)}/><span>{done(test.id)?"✓":"○"}</span></label><div className="testing-guide-test-body"><div className="testing-guide-test-title"><strong>{test.title}</strong><span>{test.roles.map(roleLabel).join(" · ")}{test.device?` · ${test.device}`:""}</span></div><ol>{test.steps.map((step,i)=><li key={i}>{step}</li>)}</ol><div className="testing-guide-expect"><b>Ожидаемый результат</b><span>{test.expect}</span></div><button className="testing-guide-report-button" onClick={()=>openReport(test)}>⚑ Сообщить о проблеме</button></div></article>)}</div>}</section>})}</div>
  {visible.length===0&&<div className="boards-empty"><strong>Ничего не найдено</strong><span>Измените поиск, роль или фильтр.</span></div>}
  <section className="qa-report-log"><div className="qa-report-log-head"><div><span>МОИ СООБЩЕНИЯ QA</span><h2>Отправленные ошибки</h2></div><b>{reports.length}</b></div>{reportNotice&&<div className="qa-report-notice">{reportNotice}</div>}{reports.length===0?<div className="qa-report-empty">Пока сообщений нет.</div>:<div className="qa-report-list">{reports.map(r=><article key={r.id}><div className="qa-report-row"><span className={`qa-severity ${r.severity}`}>{r.severity==="critical"?"Критично":r.severity==="high"?"Высокая":r.severity==="low"?"Низкая":"Средняя"}</span><strong>{r.title}</strong><time>{new Date(r.createdAt).toLocaleString("ru-RU")}</time></div><p>{r.description}</p><small>{r.environment}</small><div className="qa-report-foot"><span>{r.testId}</span><b>{r.status==="open"?"Открыт":r.status==="in_progress"?"В работе":r.status==="fixed"?"Исправлен":"Закрыт"}</b></div></article>)}</div>}</section>
  {reportDraft&&<div className="modal-backdrop" onMouseDown={()=>!reportBusy&&setReportDraft(null)}><section className="modal-card qa-report-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="testing-guide-kicker">QA · ОШИБКА</span><h2>Сообщить о проблеме</h2></div><button onClick={()=>setReportDraft(null)} disabled={reportBusy}>×</button></div><label><span>Проверка</span><input value={reportDraft.title} onChange={e=>setReportDraft({...reportDraft,title:e.target.value})}/></label><label><span>Серьёзность</span><select value={reportDraft.severity} onChange={e=>setReportDraft({...reportDraft,severity:e.target.value as QaSeverity})}><option value="low">Низкая</option><option value="medium">Средняя</option><option value="high">Высокая</option><option value="critical">Критичная</option></select></label><label><span>Что произошло *</span><textarea rows={5} autoFocus value={reportDraft.description} onChange={e=>setReportDraft({...reportDraft,description:e.target.value})} placeholder="Опишите шаг и фактический результат…"/></label><label><span>Что ожидалось</span><textarea rows={3} value={reportDraft.expected} onChange={e=>setReportDraft({...reportDraft,expected:e.target.value})}/></label><div className="qa-report-device">Браузер и размер экрана добавятся автоматически.</div><div className="modal-actions"><button className="boards-secondary" onClick={()=>setReportDraft(null)} disabled={reportBusy}>Отмена</button><button className="boards-primary" onClick={()=>void submitReport()} disabled={reportBusy||!reportDraft.description.trim()}>{reportBusy?"Отправляем…":"Отправить"}</button></div></section></div>}
 </section></main>
}
